            <div class="section-x" style="height: 243px;">
				<div class="title">Measure. Control.</div>
				Here are 5 new tools which put you, as a supplier on ShipServ Pages, in control – able to measure, on a daily basis, the return on your lead gen and marketing spend on Pages.<br /><br />
                These tools are free for all suppliers but you need to be a Pages User and connected to your company on Pages to see and use them.  It’s easy (and free) to sign up.  <a href="/help/sellerfaq/register">For more help on this click here</a>.<br /><br />
                If the ability to measure and monitor the benefits you get from a Premium profile (and <a href="/info/pages-for-suppliers/additional-member-solutions/banner-advertising/">targeted banner advertising</a>) on Pages makes you more interested in upgrading, <a href="/info/pages-for-suppliers/get-more-rfqs/premium-profile-3/">learn more about Premium profile here.</a>
			</div>
			<div class="section-x" style="height: 148px;">
				<div class="title">Brand verification</div>
				Brand verification enables owners to check a supplier claims of authorisation for their brand. If you list a brand on your profile and claim that you are an authorised agent, the brand owner company will be notified, and can verify that and then approve it for you.<br /><br />
                This has a major impact on your ranking in search results.
			</div>
            <div class="section-x">
				<img src="/images/new/img_pcs.jpg" />
				<div class="title">Your Company's Profile Complete Score</div>
				The higher your profile the more new business you'll get. Click <a href="/help/premium">here</a> to see why your Pages profile is so important to you.<br /><br />
			</div>
			<div class="section-x" style="height:106px;">
				<img src="/images/new/img_sir.jpg" />
				<div class="title">Your Supplier Insight Report</div>
				Tracks how many new business RFQs you've had from ShipServ Pages. Also profile views and contact views.  It's an interactive tool.<br /><br />
			</div>
			
			<div class="section-x" style="height: 115px;">
				<img src="/images/new/img_inbox.jpg" />
				<div class="title">Your RFQ Inbox</div>
				If you want to know the detail of your RFQs, or respond to them, click here to go to your RFQs Inbox. See how many RFQs have been opened and viewed - you might well be missing out on new business.<br /><br />
			</div>
			
			<div class="section-x" style="height: 106px;">
				<img src="/images/new/img_block.jpg" />
				<div class="title">Block buyer</div>
				You can block certain senders from sending you Pages RFQs again if you think they are sending you non-relevant RFQs.  <a href="/help/sellerfaq/maximise">Click here</a> for more information.<br /><br />		
			</div>
			<br />
			<div style="color: #939ba1">
				<b>CONTACT YOUR ACCOUNT MANAGER FOR MORE HELP</b><br />
				If you are a Premium Lister, you can email your <a href="/reports">account manager</a> (look on the bottom right of the Supplier Insight Report for their name).<br />
            </div>