
<div class="error">
	<div class="error-message" style="text-align: center; margin-top: 50px; height: 300px;">
		<div class="error-icon" style="margin-bottom: 15px;"><img src="/images/layout_v2/error_icon.gif" width="45" height="40" border="0"/></div>
		<div class="error-text">
			<h1><?php echo $this->action['msg']; ?></h1>					
		</div>
		<div class="error-button"></div>
		<div class="clear"></div>
	</div>
</div>