<footer class="mainFooter">
	<div class="wrapper">
		<div class="footerTopRow">
			<div class="footerLogo">
				<img src="/img/shipmate/wp/footer_logo.svg" alt="ShipServ">
			</div>
			<div class="socialMedia">
				<ul>
					<li><a href="https://www.facebook.com/pages/ShipServ-Maritime-Trading-Network/209142614873" target="blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
					<li><a href="https://twitter.com/ShipServ" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
					<li><a href="https://www.linkedin.com/company/shipserv" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
				</ul>
			</div> 
			<div class="clear"></div>
		</div>
        <!-- Do not delete the ID, as it is nessesary to pass it to the new architecture -->
		<div id="shipservFooterRow" class="footerMiddleRow">
			<!--<div class="column">
				<h6>About us</h6>
				<ul class="footerNav">
					<li><a href="/info/about-us">About ShipServ</a></li>
					<li><a href="/info/contact-us">Contact Us</a></li>
					<li><a href="/info/pages-for-suppliers/webstore">Store</a></li>
					<li><a href="/info/contact-us">Support</a></li>
					<li><a href="/info/save-time-and-money-with-tradenet">Buyer Solutions</a></li>
					<li><a href="/info/pages-for-suppliers">Supplier Solutions</a></li>
				</ul>
			</div>
			<div class="column">
				<h6>Search Suppliers</h6>
				<ul class="footerNav">
					<li><a href="/supplier/category">By category</a></li>
					<li><a href="/supplier/brand">By brand</a></li>
					<li><a href="/supplier/country">By country</a></li>
					<li><a href="/supplier/browse">Supplier A-Z</a></li>
				</ul>
			</div>-->
			<div class="column">
				<h6>Important Legal Matters</h6>
				<ul class="footerNav">
					<li><a href="/info/terms-of-use">Pages - Terms of Use</a></li>
					<li><a href="/info/service-conditions">Pages - Service Conditions</a></li>
					<li><a href="/info/service-guidelines">Pages - Service Guidelines</a></li>
					<li><a href="/info/privacy-policy">Privacy Policy</a></li>
					<li><a href="/info/legal-notes/cookie-policy">Cookie Policy</a></li>
					<li><a href="/info/legal-notes">Other ShipServ conditions</a></li>
					<li><a href="/info/shipserv-membership-and-definitions">ShipServ Membership terms</a></li>
				</ul>
			</div>
		</div>
		<div class="footerBottomRow">
			<p>Copyright &copy; <?= date('Y'); ?> ShipServ Limited. All rights reserved.</p>
		</div>
	</div>
</footer>
