<!--[if lte IE 9]>
<div style='text-align: center; clear: both; width: 90%; position: fixed; left: 0; top: 50%; margin: -40px 5%; z-index: 9999;'>
    <div style='display: inline-block; position: relative; border: 1px solid #F7941D; background: #FEEFDA; min-height: 80px; padding-top: 10px; width: 100%; max-width: 800px; -webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75); -moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75); box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.75);'>
        <div style='position: absolute; right: 3px; top: 3px;'><a href='#' onclick='javascript:this.parentNode.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
            <div style='display: inline-block; vertical-align: top; width: 75px;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div>
            <div style='display: inline-block; vertical-align: top; max-width: 275px; font-family: Arial, sans-serif;'>
                <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
                <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
            </div>
        <div style='display: inline-block; vertical-align: top; padding: 8px 0;'>
            <div style='display: inline-block; vertical-align: top; width: 70px; height: 52px; overflow: hidden'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
            <div style='display: inline-block; vertical-align: top; width: 70px; height: 52px; overflow: hidden'><a href='http://www.firefox.com' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
            <div style='display: inline-block; vertical-align: top; width: 70px; height: 52px; overflow: hidden'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
            <div style='display: inline-block; vertical-align: top; width: 70px; height: 50px; overflow: hidden'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 9'/></a></div>
        </div>
        <div class="clear"></div>
</div>
</div>
<![endif]-->