    <?php
	$this->compressedScript()->appendFile('/js/lib/selectmenu/jquery.ui.widget.js')
							 ->appendFile('/js/lib/selectmenu/jquery.ui.selectmenu.js')
							 ->appendFile('/js/lib/selectmenu/jquery.ui.position.js')
							 ->appendFile('/js/lib/selectmenu/jquery.ui.core.js')
							 ->appendFile('/js/lib/datatables.js');

	$this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic')
					 ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic')
                     ->appendStylesheet('/css/jquery.ui.tabs.css')
					 ->appendStylesheet('/css/jquery.ui.smoothness.css')
					 ->appendStylesheet('/css/buyer-connect-admin.css')
					 ->appendStylesheet('/css/grid.css')
					 ->appendStylesheet('/css/datatables.css')
					 ->appendStylesheet('/css/selectmenu/jquery.ui.selectmenu.css');

	$this->getHelper('Requirejs')
	   ->addModule('backbone/buyer-connect-admin/views/mainView');
?>

<div class="header-container">
	<h1>Buyer Connect Admin</h1>
</div>

<div id="waiting" style="display: none;">
	<div class="waitingMessage">Loading...</div>
	<div class="waitingMask"></div>
</div>

<div id="body">
	<div id="mainContent" class="container">
	</div>
</div>
<div class="clear"></div>
