<?php

$this->headLink()
    ->appendStylesheet('/css/jquery.calendar.min.css')
    ->appendStylesheet('https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic')
    ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic')
    ->appendStylesheet('/css/shipmate/supplier-insight-report-pct.css', 'all');

$this->getHelper('Requirejs')
    ->addModule('backbone/shipmate/supplier-insight-report-pct/views/MainView')
    ->addDefinition('supplier/profile', json_encode($this->selectedSupplier));

?>

<div class="header-container">
    <h1>Supplier Insight Report<a href="#" id="exelexport" class="btn green">Export to Excel</a></h1>
</div>

<div id="waiting" style="display: none;">
    <div class="waitingMessage">Loading...</div>
    <div class="waitingMask"></div>
</div>

<div id="body">
    <div id="content">
        <div id="renderContainer" class="container">
            <div id="report_content">
                <?php include APPLICATION_PATH.'/views/scripts/alert/outdatedAlert.phtml'; ?>
                <div id="filter"></div>
                <div id="report"></div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
