<?php
	$this->headLink()->appendStylesheet('/css/wp-styles.css');
	$this->headLink()->appendStylesheet('/css/default-new.css');
	$this->requirejs()	->addModule('backbone/shipmate/design-guidelines/views/mainView');
	$user = Shipserv_User::isLoggedIn();
?>

<section class="hero img">
	<h3>SUPPLIER SOLUTIONS</h3>
	<h5>ShipServ provides a set of solutions enabling suppliers to improve their performance at every stage of the sales funnel to WIN MORE ORDERS.</h5>
	<a class="btn red">Watch our short video  <i class="fa fa-play-circle-o" aria-hidden="true"></i></a>
</section>

&nbsp;

<section class="hero img">
	<h3>SHIPOWNER & MANAGER SOLUTIONS</h3>
	<div class="p-group">
		<h5>Reduce OPEX</h5>
		<h5>Analyze & control spend</h5>
		<h5>Automate procurement</h5>
	</div>
	<a class="btn red">Request a demo</a>
	<a class="btn blue">Contact us</a>
</section>

&nbsp;

<section class="hero img">
	<h3>MONITORING &amp; ANALYTICS</h3>
	<h4>Unique business intelligence at your fingertips</h4>
	<button class="btn red">Request a demo</button>
	<nav class="inpage">
		<ul>
			<li><a href="">PROCUREMENT KPI's<i class="fa fa-angle-down" aria-hidden="true"></i></a></li>
			<li><a href="">SUPPLIER PERFORMANCE REPORTING<i class="fa fa-angle-down" aria-hidden="true"></i></a></li>
			<li><a href="">PRICE BENCHMARKING<i class="fa fa-angle-down" aria-hidden="true"></i></a></li>
		</ul>
	</nav>
</section>

&nbsp;

<section class="hero img">
	<div class="hero-text">
		<h3>HELP</h3>
		<h5>Welcome to the ShipServ Help and Support Centre</h5>
	</div>
</section>

&nbsp;

<section class="hero img">
	<h3>SHIPOWNERS & MANAGERS</h3>
	<div class="p-group">
		<h5>Reduce OPEX</h5>
		<h5>Analyze & control spend</h5>
		<h5>Automate procurement</h5>
	</div>
	<a class="btn transparent">Find out more</a>
</section>

&nbsp;

<section class="hero img">
	<h3>SUPPLIER SUPPORT</h3>
	<h5>How can we help you?</h5>
	<div class="hero-search-container">
		<form>
			<input class="top-search" type="text" placeholder="Search">
			<input type="submit"> 
		</form>
	</div>
</section>

&nbsp;

<section class="intro darkGrey">					
	<div class="wrapper">
		<div class="intro-icon">
			<p><i class="fa fa-bar-chart" aria-hidden="true"></i></p>
		</div>
		<div class="intro-content">
			<h3>TRANSACTION EFFICIENCY</h3>
			<p>Say goodbye to manual – with fully automated procurement</p>
			<a href="#" class="btn white">Request a demo</a>
			<a href="#" class="btn transparent">Contact us</a>
		</div>
		<a href="#" class="btn transparent back-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
		<div class="clear"></div>
	</div>	
</section>

&nbsp;

<section class="intro darkGrey">

	<div class="wrapper">
		<div class="intro-icon">
			<p><i class="fa fa-bar-chart" aria-hidden="true"></i></p>
		</div>
		<div class="intro-content">
			<h3>SMART SUPPLIER</h3>
			<p>Quoting efficiency saves you time to quote quicker</p>
			<a href="#" class="btn white">Contact us</a>
		</div>
		<a href="#" class="btn transparent back-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
		<div class="clear"></div>
	</div>	
</section>

&nbsp;

<section class="intro darkGrey">
	<div class="wrapper">
		<div class="intro-icon">
			<p><i class="fa fa-bar-chart" aria-hidden="true"></i></p>
		</div>
		<div class="intro-content">
			<h3>SMART SUPPLIER HELP</h3>
		</div>
		<a href="#" class="btn transparent back-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
		<div class="clear"></div>	
	</div>	
</section>

&nbsp;

<section class="intro darkGrey">
	<div class="wrapper">
		<div class="intro-content align-center">
			<h3>SMART SUPPLIER HELP</h3>
			<p>Quoting efficiency saves you time to quote quicker</p>
		</div>
		<a href="#" class="btn transparent back-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
		<div class="clear"></div>	
	</div>	
</section>

&nbsp;

<section class="intro grey">
	<div class="wrapper">
		<h4 class="center">Looking to manage and reduce costs but don’t know where to start?</h4>
		<p class="center">Our new and unique Spend Management solutions including SpendBenchmarking and  SpotSource makes it easy for your purchasing team to stay in control of spend, ensure compliance and reduce costs.</p>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">HOW CAN WE HELP YOU?</h4>
		<div class="help">
			<div class="help-block midBlue">
				<div class="icon midBlue">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">I WANT TO GET MORE RFQs </h5>
					<p>Win more orders from the thousands of buyers using ShipServ</p>
					<a href="">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
				</div>
			</div>
			<div class="help-block darkNavy">
				<div class="icon darkNavy">
					<i class="fa fa-exchange" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">I WANT TO QUOTE QUICKER</h5>
					<p>Prioritise, quote quicker and increase your win rate </p>
					<a href="">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
				</div>
			</div>
			<div class="help-block linkBlue">
				<div class="icon linkBlue">
					<i class="fa fa-bullhorn" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">I WANT TO INCREASE OUR BRAND PRESENCE</h5>
					<p>Win more orders from the thousands of buyers using ShipServ</p>
					<a href="">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">I NEED HELP WITH</h4>
		<div class="help">
			<div class="help-block midBlue shorter">
				<div class="icon midBlue">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">START SUPPLIER</h5>
				</div>
			</div>
			<div class="help-block darkNavy shorter">
				<div class="icon darkNavy">
					<i class="fa fa-exchange" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">SMART SUPPLIER</h5>
				</div>
			</div>
			<div class="help-block cyanBlue shorter">
				<div class="icon cyanBlue">
					<i class="fa fa-bullhorn" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">SUPPLIER INSIGHT REPORT</h5>
				</div>
			</div>
			<div class="help-block darkGrey shorter">
				<div class="icon darkGrey">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">PREMIUM PROFILE</h5>
				</div>
			</div>
			<div class="help-block darkNavy shorter">
				<div class="icon darkNavy">
					<i class="fa fa-exchange" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">CATALOGUE</h5>
				</div>
			</div>
			<div class="help-block linkBlue shorter">
				<div class="icon linkBlue">
					<i class="fa fa-bullhorn" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">BRAND ZONE & VERIFICATION</h5>
				</div>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey icons-list">
	<div class="wrapper">
		<h4 class="center">I NEED HELP WITH</h4>
		<ul>
			<li>Up to 30% reduction in ordering cycle times due to more efficient transaction process</li>
			<li>Increased productivity – more vessels per purchaser or time freed up for more value added tasks</li>
			<li>Save up to 30% on OPEX cost on broad range of spares and stores through Supplier Recommendation system</li>
			<li>Track and benchmark supplier performance</li>
			<li>Employee satisfaction (fewer data errors, less retying, less supplier chasing</li>
		</ul>
	</div>
</section>

&nbsp;

<section class="testimony grey leftImg">
	<div class="wrapper">
		<h4 class="center">TESTIMONIAL</h4>
		<div>
			<div class="icon"><i class="fa fa-quote-left" aria-hidden="true"></i></div>
			<p>
				&quot;Since we used ShipServ we have calculated that each member of the 
				purchasing team gains <strong>three hours a day</strong> due to a reduction in manual processing.&quot;<br><br>
				<strong class="person">
					Roar Misje - Purchasing Manager<br>
					Grieg Shipping
				</strong>
			</p>
			<div class="clear"></div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey two-columns">
	<div class="wrapper">
		<h4 class="center">Benchmark, control and reduce your spend</h4>
		<div class="row">
			<div class="icon"><i class="fa fa-quote-left" aria-hidden="true"></i></div>
			<div class="content">
				<p>ShipServ’s spend management solutions allow you to analyse and benchmark your existing trade with suppliers and save money by:</p>
				<ul>
					<li>Giving you complete visibility of your procurement activity with real-time reporting tools</li>
					<li>Benchmarking your activity against other ShipServ users</li>
					<li>Providing alternative supplier recommendations for certain products</li>
					<li>Enter supplier negotiations with key business intelligence</li>
				</ul>
				<a href="#" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>               
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">HOW DOES IT WORK?</h4>
		<div class="content-block">
			<div class="left">
				<p>By leveraging our unrivalled 16 years of trading data our Sourcing Engine is able to identify suppliers in a specific segment of spares or stores that are:</p>
				<ul>
					<li>Highly competitive</li>
					<li>Highly responsive</li>
					<li>High quality</li>
				</ul>
			</div>
			<div class="right">
				<p>Once enabled, Supplier Recommendations obtains comparison quotes from recommended suppliers whenever you send an RFQ to one of your normal suppliers. After a short while, there are enough comparison quotes to see if the recommended suppliers can outperform your normal suppliers.</p>
				<p>You can then review the results via your spend benchmarking report and judge the suppliers in terms of price, quality and other factors to decide whether to approve and start using them to realise the savings.</p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey three-columns">
	<div class="wrapper">
		<h4 class="center">Fully automated procurement</h4>
		<div class="row">
			<div class="icon"><i class="fa fa-quote-left" aria-hidden="true"></i></div>
			<div class="primary-content">
				<p>Many procurement departments are operating sub-optimally in regards to cost and risk because transactions (RFQs, quotes, POs etc) are sent manually and in different formats (fax, phone, email).</p>

				<p>With one connection from your existing procurement system to ShipServ you get a single connection to a network of over 60,000 suppliers including all your existing ones. From then onwards all transactions occur digitally and in the same standard format in and out of your procurement system.</p>
				<a href="#" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>               
			</div>
			<div class="secondary-content">
				<h4>Benefits</h4>
				<ul>
					<li>Reducing cycle time</li>
					<li>Reduce workload by 30%</li>
					<li>Reduce data errors</li>
				</ul>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="testimony white leftImg">
	<div class="wrapper">
		<h4 class="center">TESTIMONIAL</h4>
		<div>
			<div class="icon grey"><i class="fa fa-quote-left" aria-hidden="true"></i></div>
			<p>
				&quot;Since we used ShipServ we have calculated that each member of the purchasing team gains <strong>three hours a day</strong> due to a reduction in manual processing.&quot;<br><br>
				<strong class="person">
					Roar Misje - Purchasing Manager<br>
					Grieg Shipping
				</strong>
			</p>
			<div class="clear"></div>
		</div>
	</div>
</section>

&nbsp;

<section class="testimony white leftImg">
	<div class="wrapper">
		<h4 class="center">TESTIMONIAL</h4>
		<div>
			<div class="icon grey"><i class="fa fa-quote-left" aria-hidden="true"></i></div>
			<p>
				&quot;Since we used ShipServ we have calculated that each member of the purchasing team gains <strong>three hours a day</strong> due to a reduction in manual processing.&quot;<br><br>
				<a href="#" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
			</p>
			<div class="clear"></div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<div class="testimonials">
			<div class="testimonial-block">
				<div class="icon grey">
					<i class="fa fa-quote-left" aria-hidden="true"></i>
				</div>
				<p class="center">“ShipServ Pages has revolutionised the way we do business and put our brand into new and exciting markets that would not have been possible using any other channel.”</p>
				<p class="client">Greg Pech - CEO</p>
				<p class="company">Satellite Phone Store</p>
			</div>
			<div class="testimonial-block">
				<div class="icon grey">
					<i class="fa fa-quote-left" aria-hidden="true"></i>
				</div>
				<p class="center">“ShipServ Pages has revolutionised the way we do business and put our brand into new and exciting markets that would not have been possible using any other channel.”</p>
				<p class="client">Greg Pech - CEO</p>
				<p class="company">Satellite Phone Store</p>
			</div>
			<div class="testimonial-block no-border">
				<div class="icon grey">
					<i class="fa fa-quote-left" aria-hidden="true"></i>
				</div>
				<p class="center">“ShipServ Pages has revolutionised the way we do business and put our brand into new and exciting markets that would not have been possible using any other channel.”</p>
				<p class="client">Greg Pech - CEO</p>
				<p class="company">Satellite Phone Store</p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">A TYPICAL SHIPSERV ONBOARD PACKAGE</h4>
		<p>A typical ShipServ Onboard package includes:</p>
		<div class="packages">
			<div class="package-block">
				<div class="package-icon">
					<div class="circle"></div>
				</div>
				<div class="package-excerpt">
					<p>A Premium profile on ShipServ Onboard and ShipServ Pages</p>
				</div>
			</div>
			<div class="package-block">
				<div class="package-icon">
					<div class="circle"></div>
				</div>
				<div class="package-excerpt">
					<p>A Premium profile on ShipServ Onboard and ShipServ Pages</p>
				</div>
			</div>
			<div class="package-block">
				<div class="package-icon">
					<div class="circle"></div>
				</div>
				<div class="package-excerpt">
					<p>A Premium profile on ShipServ Onboard and ShipServ Pages</p>
				</div>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper center">
		<h4 class="center">PRICE</h4>
		<div class="p-group">
			<p>Access all these tools by becoming a Member.</p> 
			<p>A ShipServ Membership includes:</p>
		</div>
		<div class="services-container">
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">PREMIUM PROFILE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SPOTSOURCE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SUPPLIER INSIGHT REPORT</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SMART SUPPLIER</a>
			</div>
		</div>
		<a class="btn red">Contact us</a>
		<a class="btn blue">Get membership</a>
		<div class="clear"></div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper center">
		<h4 class="center">PRICE</h4>
		<div class="p-group">
			<p>Access all these tools by becoming a Member.</p> 
			<p>A ShipServ Membership includes:</p>
		</div>
		<div class="services-container">
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">PREMIUM PROFILE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SPOTSOURCE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SUPPLIER INSIGHT REPORT</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SMART SUPPLIER</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SHIPSERV ONBOARD</a>
				<p>*You can only purchase with ShipServ Membership</p>
			</div>
		</div>
		<a class="btn red">Contact us</a>
		<a class="btn blue">Get membership</a>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper center">
		<h4 class="center">PRICE</h4>
		<div class="p-group">
			<p>Access all these tools by becoming a Member.</p> 
			<p>A ShipServ Membership includes:</p>
		</div>
		<div class="services-container with-border">
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">PREMIUM PROFILE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SPOTSOURCE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SUPPLIER INSIGHT REPORT</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SMART SUPPLIER</a>
			</div>
		</div>
		<p class="with-margin">You can only purchase Integration and E-invoicing with a ShipServ Membership:</p>
		<div class="services-container centered">
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">PREMIUM PROFILE</a>
			</div>
			<div class="service">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<a href="#">SPOTSOURCE</a>
			</div>
		</div>
		<a class="btn red">Contact us</a>
		<a class="btn blue">Get membership</a>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-1">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 

			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-2">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-3">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-4">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-5">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>The Outbound Integration is more affordable, easier, and less complicated to carry out than a full Outbound/Inbound Integration.</p>
				<p>Such full integration usually requires a significant investment, however, we can now integrate your company for a much more affordable price.</p> 
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">WHAT IS OUTBOUND INTEGRATION?</h4>
		<div class="row variation-6">
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
			<div class="content">
				<p>Get our great guide to 2017 Marine Trade Shows here etc</p>
				<a href="#" class="btn red">Download guide</a>
			</div>
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">BULLETED LIST</h4>
		<ul>
			<li>Allows you to influence at the requisition stage</li>
			<li>Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ</li>
		</ul>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">BULLETED LIST + IMAGE</h4>
		<div class="row">
			<ul>
				<li>Allows you to influence at the requisition stage</li>
				<li>Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ</li>
			</ul>
			<div class="thumb">
				<img src="/img/shipmate/wp/Example_16_9.jpg">
			</div>
		</div>		
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">BULLETED LIST + TEXT BLOCK</h4>
		<div class="row variation-7">
			<div class="content">
				<p>Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ</p>	
				<ul>
					<li>Allows you to influence at the requisition stage</li>
					<li>Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ</li>
				</ul>		
			</div>			
		</div>		
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">BULLETED LIST + ICON</h4>
		<div class="row variation-8">
			<div class="content">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
			</div>
			<ul>
				<li>Allows you to influence at the requisition stage</li>
				<li>Chances of winning an order are significantly increased if your product/part number if specified in the requisition/RFQ</li>
			</ul>
		</div>		
	</div>
</section>

&nbsp;

<section class="grey icons-list">
	<div class="wrapper">
		<h4 class="center">ICON LIST, 2 COLUMNS</h4>
		<div class="row">
			<ul>
				<li>Up to 30% reduction in ordering cycle times due to more efficient transaction process</li>
				<li>Increased productivity – more vessels per purchaser or time freed up for more value added tasks</li>
				<li>Save up to 30% on OPEX cost on broad range of spares and stores through Supplier Recommendation system</li>
				<li>Track and benchmark supplier performance</li>
				<li>Employee satisfaction (fewer data errors, less retying, less supplier chasing)</li>
			</ul>
			<ul>
				<li>Up to 30% reduction in ordering cycle times due to more efficient transaction process</li>
				<li>Increased productivity – more vessels per purchaser or time freed up for more value added tasks</li>
				<li>Save up to 30% on OPEX cost on broad range of spares and stores through Supplier Recommendation system</li>
				<li>Track and benchmark supplier performance</li>
				<li>Employee satisfaction (fewer data errors, less retying, less supplier chasing)</li>
			</ul>
		</div>		
	</div>
</section>

&nbsp;

<section class="testimony grey leftImg">
	<div class="wrapper">
		<h4 class="center">ICON TEXT + BULLETS</h4>

		<div class="trading">
			<div class="icon-container">
				<div class="icon">
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
			</div>
			<div class="trading-text">
				<p>Many procurement departments are operating sub-optimally in regards to cost and risk because transactions (RFQs, quotes, POs etc) are sent manually and in different formats (fax, phone, email).	
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
				</p>
			</div>
			<div class="free-solution">
				<h6>BENEFITS:</h6>
				<ul>
					<li>Reducing cycle time</li>
					<li>Reduce workload by 30%</li>
					<li>Reduce data errors</li>
				</ul>
			</div>
		</div>

		<div class="clear"></div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">NUMBER LIST</h4>
		 <div class="row">			
			<ol class="numbered">
				<li>One simple connection to ShipServ gives you access to a network of over 60,000 suppliers</li>
				<li>Save time and money because your procurement process is now fully automated</li>
				<li>Benchmark, control and reduce your spend with our tools including spend analytics and supplier recommendations</li>
			</ol>
			<div class="featured-image">
				<img src="/img/shipmate/wp/screenshot.png" border="0" alt="screenshot">
			</div>
		</div> 
	</div>
</section>

&nbsp; -->


<!-- <section class="white">
	<div class="wrapper">
		<h4 class="center">FREQUENTLY ASKED QUESTIONS</h4>

		<ul class="togglebox">

			<li class="accordionItem">
				<input type="checkbox" name="toggle1" id="toggle1" checked>
				<label for="toggle1">What is ShipServ Pages?</label>	  
				<div class="content">
					<h5>Send us your details</h5>
					<form>
						<fieldset>
							<div class="labels">
								<label for="name">Name:*</label>
								<label for="email">Email:*</label>
								<label for="company">Your company:*</label>
								<label for="title">Job title:*</label>
								<label for="phone">Phone number:*</label>
								<label for="website">Your website:*</label>
								<label for="message">Message:*</label>
								<label for="required">*Required fields</label>
							</div>
							<div class="fields">
								<input type="text" name="name">
								<input type="email" name="email">
								<input type="text" name="company">
								<input type="text" name="title">
								<input type="text" name="phone">
								<input type="text" name="website" placeholder="http://">
								<textarea name="message"></textarea>
							</div>
							<div class="clear"></div>
							<div class="interactions">
								<input class="btn link-blue large" type="submit" value="Submit">
							</div>
						</fieldset>
					</form>
					<div class="contacts-container">
						<div class="contact-block">
							<p class="location">Europe, Middle East, Africa</p>
							<p class="tel">Tel: +45 332 3120</p>
						</div>
						<div class="contact-block">
							<p class="location">Hong Kong</p>
							<p class="tel">Tel: +852 3953 3262</p>
						</div>
						<div class="contact-block">
							<p class="location">Singapore</p>
							<p class="tel">Tel: +65 6809 5045</p>
						</div>
						<div class="contact-block">
							<p class="location">Japan</p>
							<p class="tel">Tel: +81 3 5157 8757</p>
						</div>
						<div class="contact-block">
							<p class="location">Americas</p>
							<p class="tel">Tel: +1 732 738 6500</p>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</li>

			<li class="accordionItem">
				<input type="checkbox" name="toggle2" id="toggle2">
				<label for="toggle2">Why should I use ShipServ Pages to find a supplier?</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</li>

			<li class="accordionItem">
				<input type="checkbox" name="toggle3" id="toggle3">
				<label for="toggle3">Tell me more about TradeRank</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</li>


			<li class="accordionItem">
				<input type="checkbox" name="toggle4" id="toggle4">
				<label for="toggle4">Why should I use Pages to send my RFQs?</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</div>

		</ul>	
	</div>
</section> -->

<section class="white">
	<div class="wrapper">
		<h4 class="center">SECTION TITLE</h4>
		<div class="tabs">
			<ul>
				<li class="tab selected">Tab 1</li>
				<li class="tab">Tab 2</li>
				<li class="tab">Tab 3</li>
			</ul>
			<div class="clear"></div>
			<div class="content active">
				<ul class="togglebox">

			<li class="accordionItem">
				<input type="checkbox" name="toggle1" id="toggle1" checked>
				<label for="toggle1">What is ShipServ Pages?</label>	  
				<div class="content">
					<h5>Send us your details</h5>
					<form>
						<fieldset>
							<div class="labels">
								<label for="name">Name:*</label>
								<label for="email">Email:*</label>
								<label for="company">Your company:*</label>
								<label for="title">Job title:*</label>
								<label for="phone">Phone number:*</label>
								<label for="website">Your website:*</label>
								<label for="message">Message:*</label>
								<label for="required">*Required fields</label>
							</div>
							<div class="fields">
								<input type="text" name="name">
								<input type="email" name="email">
								<input type="text" name="company">
								<input type="text" name="title">
								<input type="text" name="phone">
								<input type="text" name="website" placeholder="http://">
								<textarea name="message"></textarea>
							</div>
							<div class="clear"></div>
							<div class="interactions">
								<input class="btn link-blue large" type="submit" value="Submit">
							</div>
						</fieldset>
					</form>
					<div class="contacts-container">
						<div class="contact-block">
							<p class="location">Europe, Middle East, Africa</p>
							<p class="tel">Tel: +45 332 3120</p>
						</div>
						<div class="contact-block">
							<p class="location">Hong Kong</p>
							<p class="tel">Tel: +852 3953 3262</p>
						</div>
						<div class="contact-block">
							<p class="location">Singapore</p>
							<p class="tel">Tel: +65 6809 5045</p>
						</div>
						<div class="contact-block">
							<p class="location">Japan</p>
							<p class="tel">Tel: +81 3 5157 8757</p>
						</div>
						<div class="contact-block">
							<p class="location">Americas</p>
							<p class="tel">Tel: +1 732 738 6500</p>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</li>

			<li class="accordionItem">
				<input type="checkbox" name="toggle2" id="toggle2">
				<label for="toggle2">Why should I use ShipServ Pages to find a supplier?</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</li>

			<li class="accordionItem">
				<input type="checkbox" name="toggle3" id="toggle3">
				<label for="toggle3">Tell me more about TradeRank</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</li>


			<li class="accordionItem">
				<input type="checkbox" name="toggle4" id="toggle4">
				<label for="toggle4">Why should I use Pages to send my RFQs?</label>		  
				<div class="content">
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
					<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, sit, quam. Accusantium esse voluptate explicabo illo ea dignissimos nobis, fugiat, quo praesentium rerum odio provident eius nihil quas? Id, iure.
					</p>
				</div>
			</div>

		</ul>
			</div>
			<div class="content">
				<p>Content 2</p>
			</div>
			<div class="content">
				<p>Content 3</p>
			</div>
		</div>
	</div>
</section>


<section class="white">
	<div class="wrapper">
		<h4 class="center">HOW SHIPSERV COMPARES</h4>
		<table>
			<thead>
				<tr>
					<th></th>
					<th>ShipServ</th>
					<th>Other vendors/ <br>
					 Software procurement <br>
					 modules</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Ability to send RFQs and purchase Orders</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>KPI Reports</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td>Some</td>
				</tr>
				<tr>
					<td>24/7 Support</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td>Some</td>
				</tr>
				<tr>
					<td>Free Supplier connectivity for all Suppliers</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td>Some</td>
				</tr>
				<tr>
					<td>Supplier Directory</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td>Some</td>
				</tr>
				<tr>
					<td>Attachment handling</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td>Some</td>
				</tr>
				<tr>
					<td>Supplier Recommendations</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Sourcing hard to find parts</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>KPI Benchmarking</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Supplier performance reporting and benchmarking</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Onboard Catalogues and requisition tool</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Integration to all major maritime software systems</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Two-Way Logistics Integration</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Back-up data centre </td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>Worldwide coverage with 60,000 connected suppliers</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td>E-invoicing</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
					<td><i class="fa fa-times" aria-hidden="true"></i></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">MEMBERSHIP PRICE</h4>
		<table class="greyHeader">
			<caption>
				<p>The PO% fee is the rate that is charged on the value of every Purchase Order you receive through ShipServ.</p>
			</caption>
			<thead>
				<tr>
					<th>Coverage</th>
					<th>Subscription Fee</th>
					<th></th>
					<th>Purchase Order Fee</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>12 months</td>
					<td>$2,000</td>
					<td>Plus</td>
					<td>1.5%</td>
				</tr>
				<tr>
					<td>24 months</td>
					<td>$3,000</td>
					<td>Plus</td>
					<td>1.5%</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">Our Partners</h4>
		<table class="greyHeader allAligned">
			<thead>
				<tr>
					<th>Company</th>
					<th>Website</th>
					<th>Product</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ABS Nautical Systems</td>
					<td><a href="#">www.abs-ns.com</a></td>
					<td>ABS NS</td>
				</tr>
				<tr>
					<td>Bass</td>
					<td><a href="#">www.bassnet.no</a></td>
					<td>BASSnet</td>
				</tr>
				<tr>
					<td>Danaos</td>
					<td><a href="#">www.danaos.ger</a></td>
					<td>Danaos</td>
				</tr>
				<tr>
					<td>DNV/GL Maritime</td>
					<td><a href="#">www.gl-maritime-software.com</a></td>
					<td>DNV GL ShipManager</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">Buyers</h4>
		<table class="greyHeader buyers">
			<thead>
				<tr>
					<th>Company name</th>
					<th></th>
					<th>Location</th>
					<th>TNID</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><img src="/img/shipmate/wp/maersk.png"></td>
					<td><a href="">A.P. Moller-Maersk A/S</a></td>
					<td>Denmark</td>
					<td>54021</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">Buyers</h4>
		<table class="allWhite">
			<tbody>
				<tr>
					<td><strong>Premium Profile</strong></td>
					<td>Priority in search results</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Upload company logo</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Full company description</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Upload datasheets, videos, catalogues</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Highlight up to 60 ports served</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Unlimited search categories</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td><strong>SpotSource</strong></td>
					<td>Priority in search results</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td></td>
					<td>Access to new buyers</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
				<tr>
					<td><strong>SpotSource</strong></td>
					<td>Priority in search results</td>
					<td><i class="fa fa-check" aria-hidden="true"></i></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">Buyers</h4>
		<table class="alternate">
			<thead>
				<tr>
					<th><strong>You pay</strong></th>
					<th><strong>We add bonus credits</strong></th>
					<th><strong>You get</strong></th>
					<th></th>
				</tr>				
			</thead>
			<tbody>
				<tr>
					<td>$500</td>
					<td>$0</td>
					<td>$500</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$1,000</td>
					<td>$50</td>
					<td>$1,050</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$3,000</td>
					<td>$200</td>
					<td>$3,200</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$5,000</td>
					<td>$400</td>
					<td>$,5400</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$10,000</td>
					<td>$900</td>
					<td>$10,900</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$25,000</td>
					<td>$2,500</td>
					<td>$27,500</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$50,000</td>
					<td>$5,750</td>
					<td>$55,750</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
				<tr>
					<td>$75,000</td>
					<td>$9,500</td>
					<td>$84,500</td>
					<td><a href="#" class="btn red">Buy</a></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">ADDITIONAL SHIPSERV SOLUTIONS</h4>
		<table class="allWhite no-border-header">
			<thead>
				<tr>
					<th>Members have the benefit of purchasing additional solutions</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Banner advertising</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
				<tr>
					<td>AdNetwork & e-newsletters</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
				<tr>
					<td>ShipServ Onboard</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
				<tr>
					<td>Brand Zone</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
				<tr>
					<td>Integration</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
				<tr>
					<td>E-invoicing</td>
					<td><a href="#" class="btn red">Contact us</a></td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">BUYERS</h4>
		
		<p>Over 200 ship owners, managers, yards and drilling contractors</p>
        
        <div class="button-container">
        	<a href="#" class="btn blue-outline selected">View A-F</a>
        	<a href="#" class="btn blue-outline">View G-M</a>
        	<a href="#" class="btn blue-outline">View N-W</a>
        </div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">LATEST NEWS & WHITE PAPERS</h4>
		<div class="blog-post-container">
			<div class="blog-post">
				<div class="featured-image">
					<img src="http://lorempixel.com/400/200/">
				</div>
				<h6>MaK (Caterpillar) uses ShipServ’s Brand Zone and Verification</h6>
				<p class="excerpt">ShipServ today announced that leading OEM Caterpillar Motoren GmbH, under its MaK brand, is…</p>
			</div>
			<div class="blog-post">
				<div class="featured-image">
					<img src="http://lorempixel.com/400/200/">
				</div>
				<h6>MaK (Caterpillar) uses ShipServ’s Brand Zone and Verification</h6>
				<p class="excerpt">ShipServ today announced that leading OEM Caterpillar Motoren GmbH, under its MaK brand, is…</p>
			</div>
			<div class="blog-post">
				<div class="featured-image">
					<img src="http://lorempixel.com/400/200/">
				</div>
				<h6>MaK (Caterpillar) uses ShipServ’s Brand Zone and Verification</h6>
				<p class="excerpt">ShipServ today announced that leading OEM Caterpillar Motoren GmbH, under its MaK brand, is…</p>
			</div>
			<div class="blog-post">
				<div class="featured-image">
					<img src="http://lorempixel.com/400/200/">
				</div>
				<h6>MaK (Caterpillar) uses ShipServ’s Brand Zone and Verification</h6>
				<p class="excerpt">ShipServ today announced that leading OEM Caterpillar Motoren GmbH, under its MaK brand, is…</p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<a class="btn transparent transparent-blue">View more</a>	
	</div>
</section>

&nbsp;	

<section class="gallery white">
	<div class="wrapper">
		<h4 class="center">EXAMPLE CUSTOMER LOGO</h4>
		<div class="gallery-container">
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo1.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo2.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo3.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo4.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo5.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo6.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo7.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo8.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo1.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo2.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo3.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo4.jpg">
			</div>
		</div>
	</div>
</section>

&nbsp;	

<section class="grey">
	<div class="wrapper">
		<div class="columns">
			<div class="featured-img">
				<div class="thumb">
					<img src="/img/shipmate/wp/Kim_profile_pic.jpg">
				</div>
			</div>
			<div class="content">
				<h5>KIM SKAARUP</h5>
				<p class="title">CHIEF OPERATING OFFICER</p>
				<p>Having worked for ShipServ for most of its 16 year history and most recently as Chief Operating Officer, Kim has taken over the day-to-day reins of the company. 
				With over 25 years of shipping and IT experience, Kim started his career as a graduate trainee at J.Lauritzen  A/S, then one of the world’s largest Reefer operators. 
				After a period in accounting he became the company’s first IT Manager introducing, amongst other things,  one of the world’s earliest e-mail systems in the early 80’s. He then worked as Assistant to the Chairman of the Lauritzen Group (Denmark’s third largest conglomerate) before moving back to J.Lauritzen, as head of all purchasing activities and outsourced services. He was subsequently promoted to Senior Vice President of IT/Procurement. 
				Kim joined ShipServ in December 2000 and has been a council member of IMPA (International Marine Purchasing Association) since 1994. He has a B.Com from Copenhagen Business School and a degree from INSEAD.</p>
			</div>
		</div>
	</div>
</section>

&nbsp;	

<section class="white">
	<div class="wrapper">
		<div class="columns columns-right-thumb">
			<div class="featured-img">
				<div class="thumb">
					<img src="/img/shipmate/wp/Kim_profile_pic.jpg">
				</div>
			</div>
			<div class="content">
				<h5>STEPHEN COXHEAD</h5>
				<p class="title">CHIEF FINANCIAL OFFICER</p>
				<p>Steve joined ShipServ in October 2012 as Chief Financial Officer.
				In Steve’s early career he worked as a Financial Controller in the food Manufacturer British Bakeries. 

				He has since held senior finance positions in a number of software and telecoms companies including eGain (a NASDAQ listed software company), Agillic, an early stage lifecycle management company and eTrader, an eMarketplace for secondary goods. 
				Stephen has also acted as a consultant to Symantec Inc following their merger with Veritas and on behalf of Venture Capital Companies within stressed portfolio businesses. Steve has proven ability to guide companies through international expansion and difficult trading environments and will play a key role in driving Shipserv’s growth strategy.</p>
			</div>
		</div>
	</div>
</section>

&nbsp;	

<section class="white">
	<div class="wrapper">
		<div class="columns columns-equal-width-columns">
			<div class="featured-img">
				<div class="thumb">
					<img src="/img/shipmate/wp/Kim_profile_pic.jpg">
				</div>
			</div>
			<div class="content">
				<p>ShipServ is the largest e-marketplace for the marine, oil and gas industries, connecting purchasers (shipowners,managers, yards and oil rigs) with suppliers of spares, stores and anything else that is used on a ship.</p>
				<p>In 2015, ShipServ facilitated US$2.6bn of annual trade from over 200 buying companies, managing over 9,000 vessels and trading with over 60,000 suppliers in over 100 countries around the world.</p>
				<p>For buyers, ShipServ works with existing ship management software and helps shipowners, managers and yards to cut OPEX in categories such as spares and stores, reduce cycle timesby 30%, plus gain access to vital data intelligence. For suppliers, 
				ShipServ offers effective solutions to build their brands, get more RFQs, improve their quote rateand increase their win rate and ultimately win more orders with purchasers on a global scale.</p>
			</div>
		</div>
	</div>
</section>

&nbsp;	

<section class="grey">
	<div class="wrapper">
		<h4>OUR GROWTH</h4>
		<img src="http://lorempixel.com/output/abstract-q-c-1169-658-9.jpg">
		<p class="max-width">Like any marketplace, unless trading is happening, there’s no value being realised. That’s why at ShipServ we measure our growth in terms of the total amount of trade on our marketplace. Put simply, this is the total amount of money being spent by our customers.</p>
	</div>
</section>

&nbsp;	

<section class="gallery white">
	<div class="wrapper">
		<h4 class="center">PENETRATION</h4>
		<div class="gallery-container four-columns">
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo1.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo2.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo3.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo4.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo5.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo6.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo7.jpg">
			</div>
			<div class="image-block">
				<img src="/img/shipmate/wp/logos/logo8.jpg">
			</div>
		</div>
	</div>
</section>

&nbsp;	

<section class="grey">
	<div class="wrapper">
		<h4 class="center">OUR OFFICES</h4 >
		<img src="http://lorempixel.com/output/abstract-q-c-1169-658-9.jpg">
		<div class="offices-container">
			<div class="office">
				<address>
					<p><strong>Head Office: London</strong></p>
					<p>Building 3, Chiswick Park</p>
					<p>566 Chiswick High Road</p> 
					<p>London, W4 5YA</p>
					<p>United Kingdom</p> 
					<p>Tel: +44 20 3051 0250</p> 
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>Copenhagen</strong></p>
					<p>Strandvejen 171, 1</p>
					<p>2900 Hellerup</p>
					<p>Denmark</p>
					<p>Tel: +45 3332 3120 </p>
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>Hong Kong</strong></p>
					<p>7/F Nan Fung Tower</p>
					<p>88 Connaught Road Central</p>
					<p>Hong Kong</p>
					<p>Tel: +852 3953 3262</p>   
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>Manila</strong></p>
					<p>18th Floor Wynsum Corporate Plaza</p>
					<p>No.22 F.Ortigas Jr Road</p>
					<p>Ortigas Centre, Pasig City,</p>
					<p>1605</p>
					<p>Manila, Philippines</p>
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>New Jersey</strong></p>
					<p>1090 King Georges Post Road</p>
					<p>Suite 802</p>
					<p>Edison, NJ 08837</p>
					<p>USA</p>
					<p>Tel: +1 732 738 6500</p>
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>Singapore</strong></p>
					<p>12 Marina Boulevard,</p>
					<p>Marina Bay Financial Centre</p>
					<p>Tower 3</p>
					<p>Level 17-01, Singapore</p>
					<p>018982</p>
					<p>Tel: +65 6809 5045</p>
					<p>Fax: +65 6809 50012</p> 
				</address>
			</div>
			<div class="office">
				<address>
					<p><strong>Tokyo (Sales & Marketing)</strong></p>
					<p>MarineNet Co. Ltd.</p>
					<p>Masumoto Bldg. 2F</p>
					<p>1-7-6, Toranomon, Minato-ku</p>
					<p>Tokyo, 105-0001</p>
					<p>Japan</p>
					<p>Tel: +81 (3) 5157 8757</p>
					<p>Fax: +81 (3) 5157 8758</p>
					<p>Email: Japansales@shipserv.com</p>
				</address>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="intro darkGrey withImage">					
	<div class="wrapper">
		<div class="intro-icon">
			<p><i class="fa fa-calendar" aria-hidden="true"></i></p>
		</div>
		<div class="intro-content">
			<h3>EVENTS</h3>
			<p>Another line of text here saying some statement about exhibitions</p>
		</div>
		<a href="#" class="btn transparent back-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
		<div class="clear"></div>
	</div>	
</section>

&nbsp;

<section class="white">					
	<div class="wrapper">
		<div class="eventRow">
			<div class="eventThumb">
				<img src="/img/shipmate/wp/sea_shot.jpg">
			</div>
			<div class="eventExcerpt">
				<h6>Visit us at APM</h6>
				<p>ShipServ will be showcasing its buyer and supplier solutions at this year’s leading maritime trade fair, International Workboat on 3-5th December at the Morial Convention Center, New Orleans, USA. </p>
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
			<div class="eventDate">
				<p><strong>APM</strong></p>
				<p>Singapore</p>
				<p>16th-21th January, 2017</p>
				<p>Stand no: XXX</p>
			</div>
		</div>
		<div class="eventRow">
			<div class="eventThumb">
				<img src="/img/shipmate/wp/sea_shot.jpg">
			</div>
			<div class="eventExcerpt">
				<h6>Visit us at APM</h6>
				<p>ShipServ will be showcasing its buyer and supplier solutions at this year’s leading maritime trade fair, International Workboat on 3-5th December at the Morial Convention Center, New Orleans, USA. </p>
				<a href="" class="btn wp-blue">Find out more <i class="fa fa-arrow-right" aria-hidden="true"></i></a></p>
			</div>
			<div class="eventDate">
				<p><strong>APM</strong></p>
				<p>Singapore</p>
				<p>16th-21th January, 2017</p>
				<p>Stand no: XXX</p>
			</div>
		</div>
	</div>		
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<h4 class="center">KEEP UP TO DATE WITH OUR NEWS & EVENTS</h4>
		<div class="help fourColumns">
			<a href="#" class="help-block midBlue shorter">
				<div class="icon midBlue">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">START SUPPLIER</h5>
				</div>
			</a>
			<a href="#" class="help-block darkNavy shorter">
				<div class="icon darkNavy">
					<i class="fa fa-exchange" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">SMART SUPPLIER</h5>
				</div>
			</a>
			<a href="#" class="help-block cyanBlue shorter">
				<div class="icon cyanBlue">
					<i class="fa fa-bullhorn" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">SUPPLIER INSIGHT REPORT</h5>
				</div>
			</a>
			<a href="#" class="help-block darkGrey shorter">
				<div class="icon darkGrey">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center">PREMIUM PROFILE</h5>
				</div>
			</a>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<div class="help twoColumns">
			<div class="help-block midBlue">
				<div class="icon midBlue">
					<i class="fa fa-sticky-note-o" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center"><a href="#">HELP FOR SUPPLIERS <i class="fa fa-arrow-right" aria-hidden="true"></i></a></h5>
				</div>
			</div>
			<div class="help-block darkNavy">
				<div class="icon darkNavy">
					<i class="fa fa-exchange" aria-hidden="true"></i>
				</div>
				<div class="text">
					<h5 class="center"><a href="#">HELP FOR SHIPOWNERS AND MANAGERS <i class="fa fa-arrow-right" aria-hidden="true"></i></a></h5>
				</div>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<div class="case-study">
			<div class="company">
				<div class="company-logo">
					<img src="http://placehold.it/150x100" alt="Anglo Eastern">
				</div>
				<div class="company-name">
					<p><strong>Anglo Eastern</strong> <br>
					Leading the e-commerce experience</p>
				</div>
			</div>
			<hr>
			<div class="company-testimonial">
				<div class="thumb">
					<img src="http://placehold.it/100x100" alt="Greg Pech">
				</div>
				<div class="excerpt">
					<p>"ShipServ Pages has revolutionised the way we do business and put our brand into new exciting markets that would not have been possible using any other channel."<br>
					<strong>Greg Pech - CEO</strong> <br>
					<strong>Satellite Phone Store</strong></p>
				</div>
			</div>
			<div class="testimonial-content">
				<h5>Summary</h5>
				<ul>
					<li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequatur, enim cum dignissimos</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequatur, enim cum dignissimos</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequatur, enim cum dignissimos</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequatur, enim cum dignissimos</li>
				</ul>
				<hr>
				<h5>Objective</h5>
				<p>Established in the 1980s, Anglo-Eastern Ship Management has established itself as one of the leading ship managers in the world over the last 30 years and now has a pool of over 15,000 professional crewmembers and over 1,100 full-time qualified shore-based staff around the world managing close to 450 ships for some of the biggest names in shipping.</p>

				<p>As a truly global operation with seven different offices around the world handling thousands of suppliers, Anglo-Eastern was to use technology to provide automation and a high-level of control over its global purchasing activities and this has culminated in its strategy of pursuing a Single Point of Contact for all its suppliers, with multiple locations around the world.</p>
				<h5>Solution</h5>
				<hr>	
				<img src="http://placehold.it/200x20">
				<p>What is TradeNet?</p>
				<p>It is the world’s largest maritime e-commerce platform used by over 7,400 vessels from 175 shipowners, shipmanagers and shipyards.</p>
				<p>ShipLink and ShipCat</p>
				<p>ShipLink helps create and send requisitions onboard and send to shore-based department or directly to a supplier via the ShipServ TradeNet service.</p>
				<p>ShipCat allows buyers to browse and tailor supplier catalogues to make onboard purchasing easy.</p>
				<p>How does it work?</p>
				<p>All RFQs, quotes, purchase orders, confirmations and acknowledgements sent over TradeNet using MTML (Marine Trading Mark-up Language), the industry standard.</p>
				<hr>
				<h5>Results</h5>
				<p>Anglo-Eastern has rolled-out its strategy over the last two years starting with its major suppliers. Overcoming initial resistance both from staff and suppliers - the Single Point of Contact is now up and running with Anglo-Eastern’s major suppliers.</p>
				<p>With the help of the ShipServ TradeNet platform, all documentation is sent to a single supplier MTML connection, which allows global branches of the supplier to view and work on requisitions through different timezones resulting in quicker response times.</p>
				<p>Anglo-Eastern has also set-up ShipServ’s ShipLink and ShipCat solution on all of its vessels to speed up onboard requisition and eliminate part number mistakes by using pre-approved catalogues.</p>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="grey">
	<div class="wrapper">
		<div class="platforms-wrapper">
			<div class="circle">
				<h6>200 SHIPPING COMPANIES</h6>
				<p>Representing 9,000 Vessels</p>
				<a href="">View Buyer List</a>
			</div>
			<div class="arrow">
				<i class="fa fa-chevron-right" aria-hidden="true"></i>
			</div>
			<div class="circle blue">
				<h6>SHIPSERV</h6>
				<p>PLATFORM</p>
				<p><span>$2.5<small>bn</small></span>OF TRADE IN 2016</p>
				<a href="">About ShipServ</a>
			</div>
			<div class="arrow">
				<i class="fa fa-chevron-left" aria-hidden="true"></i>
			</div>
			<div class="circle">
				<h6>61,000 SUPPLIERS</h6>
				<p>Worldwide Supplier coverage</p>
				<a href="">View Supplier List</a>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<div class="company-info">
			<article>
				<p>ShipServ is the largest e-marketplace for the marine, oil and gas industries, connecting purchasers (shipowners,managers, yards and oil rigs) with suppliers of spares, stores and anything else that is used on a ship.</p>
				<p>In 2015, ShipServ facilitated US$2.6bn of annual trade from over 200 buying companies, managing over 9,000 vessels and trading with over 60,000 suppliers in over 100 countries around the world.</p>
				<p>For buyers, ShipServ works with existing ship management software and helps shipowners, managers and yards to cut OPEX in categories such as spares and stores, reduce cycle timesby 30%, plus gain access to vital data intelligence. For suppliers, ShipServ offers effective solutions to build their brands, get more RFQs, improve their quote rateand increase their win rate and ultimately win more orders with purchasers on a global scale.</p>
			</article>
			<aside>
				<blockquote>
					<p><span>$2.6bn</span> of trade</p>
				</blockquote>
				<blockquote>
					<p><span>60,000</span> suppliers registered</p>
				</blockquote>
				<blockquote>
					<p><span>Over 200</span> trading shipowners, managers, shipyards and drilling companies</p>
				</blockquote>
				<blockquote>
					<p><span>4.2m</span> trading shipowners, managers, shipyards and drilling companies</p>
				</blockquote>
			</aside>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">PENETRATION</h4>
		<p>Shipserv penetration in selected major shipping sectors:</p>
		<div class="penetration">
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
			<div class="penetration-block">
				<div class="bubble">					
					<p>
						<span>46<small>%</small></span>LNG TANKERS
					</p>
				</div>
				<div class="text">
					<p>265 vessels includes BW Fleet Management, MISC and Gaslog</p>
				</div>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section>
	<div class="wrapper">
		<nav class="thirdLevel">
			<ul>
				<li class="selected">
					<a href="">
						Selected link
					</a>
				</li>
				<li>
					<a href="">
						Other link
					</a>
				</li>
			</ul>
		</nav>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<h4 class="center">INDUSTRY PARTNERS</h4>
		<div class="industry-partners">
			<div class="partner">
				<div class="partner-thumb">
					<img src="http://placehold.it/150x120">
				</div>
				<div class="partner-content">
					<h5>IMPA</h5>
					<p>IMPA was founded in 1978 by a group of senior purchasing executives in the shipping industry with the aim of promoting co-operation and understanding between purchaser and supplier and to improve the art, science and practice of marine purchasing in all applied forms. I
					MPA has a wide membership base of companies and individuals from all over the world including many of the leading ship owning, operating and managing companies, together with major marine manufacturers and ship suppliers.</p>
				</div>
			</div>
			<div class="partner">
				<div class="partner-thumb">
					<img src="http://placehold.it/150x120">
				</div>
				<div class="partner-content">
					<h5>IMPA</h5>
					<p>IMPA was founded in 1978 by a group of senior purchasing executives in the shipping industry with the aim of promoting co-operation and understanding between purchaser and supplier and to improve the art, science and practice of marine purchasing in all applied forms. 
					IMPA has a wide membership base of companies and individuals from all over the world including many of the leading ship owning, operating and managing companies, together with major marine manufacturers and ship suppliers.</p>
				</div>
			</div>
			<div class="partner">
				<div class="partner-thumb">
					<img src="http://placehold.it/150x120">
				</div>
				<div class="partner-content">
					<h5>IMPA</h5>
					<p>IMPA was founded in 1978 by a group of senior purchasing executives in the shipping industry with the aim of promoting co-operation and understanding between purchaser and supplier and to improve the art, science and practice of marine purchasing in all applied forms. 
					IMPA has a wide membership base of companies and individuals from all over the world including many of the leading ship owning, operating and managing companies, together with major marine manufacturers and ship suppliers.</p>
				</div>
			</div>
			<div class="partner">
				<div class="partner-thumb">
					<img src="http://placehold.it/150x120">
				</div>
				<div class="partner-content">
					<h5>IMPA</h5>
					<p>IMPA was founded in 1978 by a group of senior purchasing executives in the shipping industry with the aim of promoting co-operation and understanding between purchaser and supplier and to improve the art, science and practice of marine purchasing in all applied forms. 
					IMPA has a wide membership base of companies and individuals from all over the world including many of the leading ship owning, operating and managing companies, together with major marine manufacturers and ship suppliers.</p>
				</div>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<div class="downloads-wrapper">
			<div class="download-list">
				<h5>Downloadable guides</h5>
				<a href="" class="download-list-item">
					<div class="download-text">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing</p>
					</div>
					<div class="download-icon">
						<i class="fa fa-download" aria-hidden="true"></i>
					</div>
				</a>
				<a href="" class="download-list-item">
					<div class="download-text">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing</p>
					</div>
					<div class="download-icon">
						<i class="fa fa-download" aria-hidden="true"></i>
					</div>
				</a>
				<a href="" class="download-list-item">
					<div class="download-text">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing</p>
					</div>
					<div class="download-icon">
						<i class="fa fa-download" aria-hidden="true"></i>
					</div>
				</a>
				<a href="" class="download-list-item">
					<div class="download-text">
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing</p>
					</div>
					<div class="download-icon">
						<i class="fa fa-download" aria-hidden="true"></i>
					</div>
				</a>
			</div>
		</div>
	</div>
</section>

&nbsp;

<section class="white">
	<div class="wrapper">
		<ol>
			<li>Lorem ipsum</li>
			<li>Lorem ipsum</li>
			<li>Lorem ipsum</li>
		</ol>
	</div>
</section> 