<?php
	$this->headLink()->appendStylesheet('/css/wp-styles.css');
	$this->headLink()->appendStylesheet('/css/default-new.css');
	$this->requirejs()	->addModule('backbone/shipmate/design-guidelines/views/mainView');
	$user = Shipserv_User::isLoggedIn();
?>

<section class="grey registration-header clearfix">
	<div class="wrapper">
		<div class="left">
			<h2>Forgotten Password?</h2>
		</div>
	</div>	
</section>

<section class="white">
	<div class="wrapper">
		<div class="forgotten-password-wrapper">
			<form class="forgotten-password">
				<p>Enter a username or email address:</p>
				<input type="text" name="forgotten-password" id="forgotten-password">
				<input class="btn green" type="submit" value="Send Password">
			</form>	
		</div>
	</div>
</section>