<?php
$this->headLink()->appendStylesheet('/css/trade/rfq-inbox.css');
$this->headLink()->appendStylesheet('/css/match-kpi.css');

$this->headLink()->appendStylesheet('/css/jqueryui-ss/datepicker.css');
$this->requirejs()
	->addModule('match/report')
	->addDefinition('/match/reportType', '"buyer-gmv-breakdown"')
	;

?>
<!--[if IE]>
    <link href="/css/ie/rfq-inbox-ie.css" media="screen" rel="stylesheet" type="text/css">
<![endif]-->
<!--[if IE 7]>
    <link href="/css/ie/ie7-rfq-inbox.css" media="screen" rel="stylesheet" type="text/css">
<![endif]-->
<style>
	table tr.child td {
		background-color:#d6dce4;
	}

	table tr.bold td {
		font-weight:bold;;
	}
	#body #content {
		left: 0 !important;
	}
</style>

<?php
	// -------- BREADCRUMBS ---------------
	$breadcrumbs[] = array('name' => 'ShipServ Pages', 'url'  => '/search');
	$breadcrumbs[] = array('name' => 'Shipmate', 'url'  => '/shipmate');
	$breadcrumbs[] = array('name' => 'GMV Report', 'url'  => '/reports/gmv');
	$breadcrumbs[] = array('name' => 'Buyer', 'url'  => '');
	$breadcrumbs[] = array('name' => 'Drilldown per supplier', 'url'  => '');
	echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs));
?>

<link href="/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/dataTables.tableTools.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/dataTables.fixedHeader.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/dataTables.CSV.css" media="screen" rel="stylesheet" type="text/css">

<div id="body" class="buyerGmvDetail">
	<div id="content">
		<h1 class="styled">GMV Report for Buyer - Supplier list</h1>
		<form method="get" class="new">
		    <table style="margin: auto;  width:100%;">
		    	<tr>
		        	<td>
		        		<form action="/buyer/gmv" id="buyerGmvForm">
			        		<table style="font-size:12px; ">
								<tr>
						            <td width="130">
						            	Buyer TNID:
						            </td>
						            <td>
						               <?= $this->buyer->bybBranchCode?>
						            </td>
								</tr>
								<tr>
						            <td width="130">
						            	Buyer Name:
						            </td>
						            <td>
						               <?= $this->buyer->bybName?>
						            </td>
								</tr>
								<tr>
						            <td width="130">
						            	For period:
						            </td>
						            <td>
						               <?= $this->report->startDate->format('d/M/Y');?> to <?= $this->report->endDate->format('d/M/Y');?>
						            </td>
								</tr>
			        		</table>
		        		</form>
		        	</td>
		        </tr>

		        <tr style="position: relative;">
		            <td colspan="5">
		            	<? if( lg_count($this->results) > 0 ){ ?>
		                <table id="resultsTab" width="100%" style="display:block; ">
		                    <thead>
		                        <tr>
		                            <th class="narrow" style="width:30px;"></th>
		                            <th class="narrow">Supplier TNID</th>
		                            <th class="left" style="width: 340px;">Supplier Name</th>
		                        	<th class="left">Region</th>
		                            <th class="left">Country</th>
									<th class="left">Level</th>
									<th class="left">Prime Supplier</th>
		                           	<th class="narrow">Unique <br />buyers</th>
		                        	<th class="narrow">Order</th>
		                        	<th class="narrow">Units <br />Served</th>
		                        	<th class="narrow">Average <br />Order <br />Value <br />(USD)</th>
		                        	<th class="narrow">Actual GMV (USD)</th>
		                        	<th class="narrow">% GMV</th>
		                        	<th class="narrow">Moneti<br />sation</th>
		                        	<th class="narrow">Revenue (USD)</th>
		                        </tr>
		                    </thead>
		                    <tbody>
		                        <?php
		                        foreach( (array) $this->results as $result )
		                        {
		                        	$totalGMVForBuyer += $result['TOTAL_GMV'];

		                        }

		                        foreach ( (array) $this->results as $result)
		                        {
		                        	++$no;

		                        	$supplier = Shipserv_Supplier::getInstanceById($result['SPB_BRANCH_CODE'], null, $true);
		                        	?>
		                            <tr>
		                            	<td><?= $no?></td>
		                                <td><?= $result['SPB_BRANCH_CODE']?></td>
		                                <td class="left"><a href="<?= $supplier->getUrl()?>" target="_blank"><?= $supplier->name?></a></td>
		                                <td class="left"><?= $supplier->accountRegion?></td>
		                                <td class="left"><?= $supplier->countryName?></td>
										<td class="left"><?= $supplier->getIntegrationType()?></td>
										<td class="left"><?= ($result['SPB_IS_PRIME_SUPPLIER']==1)?"Y":"N"?></td>
		                                <td><?= $result['TOTAL_UNIQUE_BUYER']?></td>
		                                <td><?= $result['TOTAL_ORDERS']?></td>
		                                <td><?= $result['TOTAL_UNIQUE_VESSEL']?></td>
		                                <td class="currency"><?= $result['AVERAGE_COST']?></td>
		                                <td class="currency"><?= $result['TOTAL_GMV']?></td>
		                                <td class="percentage"><?= $result['TOTAL_GMV']/$totalGMVForBuyer * 100?></td>
		                                <td class="percentage"><?= $result['SPB_MONETIZATION_PERCENT']?></td>
		                                <td class="currency"><?= $result['TOTAL_REVENUE']?></td>
		                            </tr>
		                        	<?

		                        	$total['TOTAL_ORDERS'] += $result['TOTAL_ORDERS'];
		                        	$total['TOTAL_UNIQUE_VESSEL'] += $result['TOTAL_UNIQUE_VESSEL'];
		                        	$total['TOTAL_UNIQUE_BUYER'] += $result['TOTAL_UNIQUE_BUYER'];
		                        	$total['AVERAGE_COST'] += $result['AVERAGE_COST'];
		                        	$total['TOTAL_GMV'] += $result['TOTAL_GMV'];
		                        	$total['SPB_MONETIZATION_PERCENT'] += $result['SPB_MONETIZATION_PERCENT'];
		                        	$total['PC_GMV'] += $result['TOTAL_GMV']/$totalGMVForBuyer * 100;
		                        	$total['TOTAL_REVENUE'] += $result['TOTAL_REVENUE'];

		                        }

		                        ?>
		                    </tbody>
		                    </tfoot>
		                            <tr style="background-color: #d6dce4">
		                                <td></td>
		                                <td></td>
		                                <td></td>
		                                <td></td>
		                                <td></td>
										<td></td>
										<td></td>
		                                <td class="">Average</td>
		                                <td>Total</td>
		                                <td class="">Average</td>
		                                <td class="">Average</td>
		                                <td class="">Total</td>
		                                <td class="">Total</td>
		                                <td class="">Average</td>
		                                <td class="">Total</td>
		                            </tr>
		                            <tr>
		                                <td></td>
		                                <td></td>
		                                <td></td>
		                                <td></td>
		                                <td></td>
		                                <td></td>
										<td></td>

		                                <td class="currency"><?= $total['TOTAL_UNIQUE_BUYER']/$no?></td>
		                                <td class="currency"><?= $total['TOTAL_ORDERS']?></td>
		                                <td class="percentage"><?= @$total['TOTAL_UNIQUE_VESSEL']/$no?></td>
		                                <td class="percentage"><?= @$total['AVERAGE_COST']/$no?></td>
		                                <td class="currency"><?= $total['TOTAL_GMV']?></td>
		                                <td class="percentage"><?= $total['PC_GMV']?></td>
		                                <td class="percentage"><?= @$total['SPB_MONETIZATION_PERCENT']/$no?></td>
		                                <td class="currency"><?= $total['TOTAL_REVENUE']?></td>
		                            </tr>
		                    </tfoot>
		                </table>
		                <?php }?>
		            </td>
		        </tr>
		    </table>
		</form>
	</div>
</div>
<div class="clear"></div>
<script type="text/javascript">
	function changeParentId(parentId){
		$('#parentId').val(parentId);
		$("#buyerGmvForm").submit();
	}
</script>
