<?php
$this->headLink()->appendStylesheet('/css/shipmate.css')
->appendStylesheet('/css/uniform.rfq.css');


$this->headLink()->appendStylesheet('/css/trade/rfq-inbox.css');
$this->headLink()->appendStylesheet('/css/match-kpi.css');

$this->headLink()->appendStylesheet('/css/jqueryui-ss/datepicker.css');
$this->requirejs()->addModule('match/match');

?>

<style>
	td{
		font-size:12px;
	}
	td b{
		font-size:16px;
		line-height:20px;
	}
</style>
<div id="body" style="width:1150px;">
	<div id="content" style="width: 1105px;">
		<h1 class="styled">GMV Trend Report for <b><?= $this->buyer->bybName . '</b> - TNID: ' . $this->buyer->bybBranchCode . (($this->params['parent']==1)?' including its children':'') ?></h1>
		<div class="innerContent">
			<div>
				<?= $this->partial('buyer/gmv-trend-chart.phtml', array('data' => $this->data, 'vesselData' => $this->vesselData, 'totalVesselData' => $this->totalVesselData, 'periodForTrends' => $this->periodForTrends, 'showVesselChart' => true)); ?>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
