<?php
	$this->headLink()->appendStylesheet('/css/buyer/rfq-outbox.css')
					 ->appendStylesheet('/css/uniform.rfq.css');
	$this->getHelper('Requirejs')->addModule('backbone/buyer/rfq-outbox/views/mainView');
	
	$hash = $this->hash;
	if ($this->params['page']){
		$page = $this->params['page'];
	} else {
		$page = 1;
	}
	if ($this->params['branchId']){
		$branchId = $this->params['branchId'];
	} else {
		$branchId = "false";
	}
	if ($this->params['setFilter']){
		$setFilter = "true";
	} else {
		$setFilter = "false";
	}
	$this->getHelper('Requirejs')->addDefinition('buyer/rfq-outbox/tnid', $this->activeCompany->company->id)
								 ->addDefinition('buyer/rfq-outbox/branchId', $branchId)
								 ->addDefinition('buyer/rfq-outbox/setFilter', $setFilter);
?>

<div id="body" class="liquid">
	<div id="sidebar">
		<div class="filterSection"></div>
	</div>
	<div id="content">
		<h1 class="styled header"><strong><span class="sum"></span> RFQs</strong> found</h1>
		<table class="rfqList" cellpadding="0" cellspacing="0" border>
			<thead>
				<tr>
					<th class="setorder int" title="integration">
						<img src="/img/buyer/rfq-outbox/integration-dblue.png" border="0" alt="Integration" />
					</th>
					<th class="setorder priority" title="priority">
						<img src="/img/buyer/rfq-outbox/priority-dblue.png" border="0" alt="Priority" />
					</th>
					<th class="setorder ref" title="ref_no">
						<div>Reference</div>
					</th>
					<th class="setorder vessel" title="vessel">
						<div>Vessel</div>
					</th>
					<th class="setorder subj" title="subject">
						<div>Subject</div>
					</th>
					<!--<th class="setorder cat" title="category">
						<div>Category</div>
					</th>-->
					<!--<th class="setorder resp" title="responses">-->
					<th class="resp">
						<!--<div>-->Resp.<!--</div>-->
					</th>
					<th class="setorder sent ordered desc" title="date_sent">
						<div>RFQ sent</div>
					</th>
					<th class="setorder stat" title="status">
						<div>RFQ status</div>
					</th>
					<th class="last">
						Action
					</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
		<div class="pagination"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
<div id="modal">
    <div class="modalControls"><div class="close" data-dismiss="modal" aria-hidden="true">Close</div></div>
    <div class="modalBody"></div>
</div>
<div id="waiting">
	<div class="waitingMessage">Loading...</div>
	<div class="waitingMask"></div>
</div>