<?php		
if ($this->showEmailConfirmedSuccess)
{
	?>
	<div class="message-header"></div>
	<div class="message-container">
		<h3 class="email-confirmed">Thank you! Your email address is now confirmed</h3>
	</div>
	<div class="message-footer"></div>
	<?php
}
else if ($this->showEmailConfirmedError)
{
	?>
	<div class="message-header"></div>
	<div class="message-container">
		<h3 class="email-confirmed-error"><?php echo $this->emailConfirmedErrorMsg; ?></h3>
	</div>
	<div class="message-footer"></div>
	<?php
}
