		<ul>
			<li <?php if($this->selected == 'inbox'){ echo 'class="on"'; }?>>
				<a href="/match/inbox">Inbox</a>
			</li>
			<li <?php if($this->selected == 'internal'){ echo 'class="on"'; }?>>
				<a href="/match/adoption-kpi">Reports</a>
			</li>
			<li <?php if($this->selected == 'setting'){ echo 'class="on"'; }?>>
				<a href="/match/update-algo-values">Settings for Engine</a>
			</li>			
		</ul>
