<style type="text/css">
.sidebar_apply_button input:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/apply_small_sprite.png) 0 -24px no-repeat; cursor:pointer; }
.content_header h5 a:hover{-moz-border-radius:6px; -webkit-border-radius:6px; background:#fff; }
.content_slim{width:591px; margin:0 auto 30px; padding:0; }
.content_slim_wrapper{margin:0; padding:30px; }
.content_slim_header{background:url(https://cdn1.shipserv.com/images/layout_v2/content_slim_header.jpg) no-repeat; width:537px; height:65px; position:relative; }
.content_slim_header h1{color:#fff; font-size:20px; padding:24px 20px 0 30px; }
.content_slim_header a.i_dont_have_account:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/i_dont_have_account_sprite.png) 0 -22px no-repeat; }
.content_slim_header a.i_already_have_account:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/i_already_have_account_sprite.png) 0 -22px no-repeat; }
.content_wide_header a.send_enquiry_button:hover,.content-shaded-header a.send_enquiry_button:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/send_enquiry_sprite.png) 0 -43px no-repeat; cursor:pointer; }
.content_wide_footer_shadow{width:100%; height:8px; background:url(https://cdn1.shipserv.com/images/layout_v2/footer_shadow.jpg) repeat-x; }
#searchResults .searchResultdetail .top .affiliations ul li.1{background:url(https://cdn1.shipserv.com/images/layout_v2/impa_cal.png) 0 6px no-repeat; }
#searchResults .searchResultdetail .top .affiliations ul li.2{background:url(https://cdn1.shipserv.com/images/layout_v2/issa_cal.png) 0 6px no-repeat; }
ul.jqueryfiletree a:hover{background:#bdf; }
#modal_form{width:537px; background:#fff url(https://cdn1.shipserv.com/images/layout_v2/side_shadow.jpg) 531px repeat-y; padding-top:10px; padding-bottom:20px; position:relative; }
.modal_left{float:right; width:541px; }
#modal_form .form_inner{width:491px; margin:0 25px; }
#modal_form p{font-weight:700; color:#00478a; font-size:16px; text-align:left; margin:0; padding:15px 35px 10px; }
#modal_form .modal_right input[type=checkbox]{position:absolute; top:4px; left:0; margin:0; padding:0; }
#modal_form .form_inner_body{width:489px; margin-bottom:20px; margin-left:-30px; padding:0; }
input.sign_in_and_continue:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/sign_in_and_continue_sprite.png) 0 -43px no-repeat; cursor:pointer; }
input.send_password:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/send_password_sprite.png) 0 -43px no-repeat; cursor:pointer; }
input.registerSubmit:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/register_me_send_sprite.png) 0 -43px no-repeat; cursor:pointer; }
input.registerSubmit_2:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/register_me_sprite.png) 0 -43px no-repeat; cursor:pointer; }
#success_box a.new_search:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/new_search_sprite.png) 0 -43px no-repeat; }
#modal_form input{font-weight:700; width:460px; font-size:14px; border:3px solid #ccc; margin:0 30px; padding:6px; }
#modal_form input[type=checkbox]{width:20px; border:none; background:none; }
#modal_form input.send_button:hover{ background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/send_sprite.png) 0 -43px no-repeat; cursor:pointer; }
#modal_form input.attach_files:hover{ background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/attach_sprite.png) 0 -21px no-repeat; cursor:pointer; outline:none; }
.form_error { background:#DF2929; width:480px; position:relative; margin:10px 30px 20px; padding:10px 0; }
#modal_form .form_error p.label{font-weight:700; color:#fff; font-size:16px; text-align:left; margin:0; padding:5px 10px; }
.error_msg_arrow{width:20px; height:11px; background:url(https://cdn1.shipserv.com/images/layout_v2/error_msg_arrow.gif) no-repeat; position:absolute; bottom:-11px; left:30px; }
#modal_form .form_error p{line-height:20px; color:#fff; font-size:12px; font-weight:400; padding:5px 10px; }
.form_error_2{border:1px solid red; background:#DF2929; width:480px; margin:0 30px; padding:10px 0; }
.form_error_2 p{line-height:20px; color:red; font-size:12px; font-weight:400; padding:5px 10px; }
#modal_form .form_info h2{line-height:20px; color:#00478a; font-size:16px; font-weight:700; padding:10px 10px 5px; }
#modal_form .form_info{border:1px solid #7fc0e5; background:#d7e3ee; width:480px; margin:0 30px; padding:10px 0; }
#modal_form .form_info p{line-height:20px; color:#00478a; font-size:13px; font-weight:400; padding:5px 10px; }
.sidewidget_body input[type=checkbox]{margin:0 6px 0 0; padding:0; }
a.back:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/back_sprite.png) 0 -20px no-repeat; }
a.view_more_countries:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/view_more_countries_sprite.png) 0 -22px no-repeat; }
a.browse_all_categories:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/browse_all_categories_sprite.png) 0 -22px no-repeat; }
.the_corner_piece{width:11px; height:11px; background:url(https://cdn1.shipserv.com/images/layout_v2/corner.jpg) no-repeat; position:absolute; bottom:-6px; right:0; }
#tradePerfTab:hover{background:url('/images/layout_v2/tr_popup/button_tradingperformance_a_sprite.gif') 0 -36px no-repeat; }
#revTab:hover{background:url('/images/layout_v2/tr_popup/button_reviews_a_sprite.gif') 0 -36px no-repeat; }
#verSysTab:hover{background:url('/images/layout_v2/tr_popup/button_verificationsys_a_sprite.gif') 0 -36px no-repeat; }
#search_box.zone_search_box a.search-button:hover #searchButtonIcon{background:url(/images/layout_v2/zones/search_icon_hover.png) no-repeat; width:20px; height:20px; position:relative; top:7px; left:11px; }
#search_box.zone_search_box a.search-button:hover{background:url(/images/layout_v2/zones/searchzone_sprite_button.png) 0 -35px no-repeat; }
#search_box.zone_search_box a.zone-exit-button:hover{background:url(/images/layout_v2/zones/backtodirectory_sprite_button.png) 0 -35px no-repeat; }
#competitors ul li .block:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/profile/competitor-background.gif) 0 -121px no-repeat; }
.profile-body-right p.label-header{margin-left:5px!important; margin-bottom:8px!important; line-height:14px; }
.profile-submit-button:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/profile/save-changes.png) 0 -44px no-repeat!important; }
.profile-update-pass-button:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/profile/update-password.png) 0 -44px no-repeat!important; }
#profile-emlconf-no input:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/profile/resend_email_now_spritebutton.gif) 0 -28px no-repeat; cursor:pointer; }
.review-request-action,.review-action,.brand-action,.category-action{float:right; padding-left:8px; font:normal 11px Arial; }
.company-name-search button:hover{background:url(/images/layout_v2/profile/cancel-sprite.gif) no-repeat scroll 0 -30px transparent; }
a:hover,.zone_block a:hover,.zone_block h3 a:hover,#searchResults .premium h3 a:hover,#searchResults .searchResult h3 a:hover,.zone-exit-box:hover .zone-exit-link{text-decoration:underline; }
.content_wide_nav a.enquiry_send:hover,.content_wide_nav_top a.enquiry_send:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/send_enquiry_down_sprite.png) 0 -43px no-repeat; }
.content_wide_footer #search_next_previous,.content_wide_footer_cat #search_next_previous{border-right:1px solid #ccc; width:auto; float:left; }
.content_wide_footer a.enquiry_send_bottom:hover,.content_wide_footer_cat a.enquiry_send_bottom:hover{background:url(https://cdn1.shipserv.com/images/layout_v2/buttons/send_enquiry_up_sprite.png) 0 -43px no-repeat; }
.content_wide_footer #search_next_previous a,.content_wide_footer #search_pagination a,#search_pagination span,.content_wide_footer_cat #search_next_previous a,.content_wide_footer_cat #search_pagination a {display:block; float:left; margin:0; }
.content_wide_body_left p.links:hover,#searchResults .searchResult p.link:hover,span.shipserv_icon:hover,#searchResults .searchResult .tradenettop:hover,h1.supplier_cell:hover,.tradenet_large_top:hover,.content_wide_body_left .tradenettop:hover,.content_wide_body_left p.links a:hover,.ss-ver-system:hover{cursor:help; }
#search_pagination a:hover {color:#000; }
.rejected-block h3 {color:#999; }
</style>

<div id="main_content_area">

	<div class="content_slim">
		<div class="content_slim_wrapper">
			<div class="content_slim_header">
				<h1>Access Code Reminder</h1>
			</div>
			<div id="modal_form">
				<div class="modal_left" style="float:none;">
					<div class="form_inner">
						<div class="form_inner_body">
							<?php if ($this->message) {?>
							<div class="form_info" style="margin-bottom:10px;margin-right:0;">
								<?php echo $this->message;?>
							</div>
							<?php }
							if ($this->display == "reminderForm")
							{
							?>
							<form id="accessCodeReminderForm" enctype="application/x-www-form-urlencoded" action="/selfservice/reminder" method="post">
								<input type="hidden" name="hdnAction" value="requestAccessCode"/>
								<div <?if($this->errors['email']){?>class="form_error"<?}?>>
								<p class="label">Email*</p>
								<?if($this->errors['email']){foreach ($this->errors['email'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['email']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="email" <?if($this->errors['email']){?>class="error"<?}?> name="email" maxlength="100" value="<?php echo $this->formValues['email']; ?>" />

								<input type="submit" value="Request Access Code" style="margin:20px 0 0 140px; width:230px;"/>
							</form>
							<?php
							}
							if ($this->display == "emailToSupportForm")
							{
							?>
							<form id="emailToSupportForm" enctype="application/x-www-form-urlencoded" action="/selfservice/reminder" method="post">
								<input type="hidden" name="hdnAction" value="emailToSupport"/>
								<div <?if($this->errors['email']){?>class="form_error"<?}?>>
								<p class="label">Email*</p>
								<?if($this->errors['email']){foreach ($this->errors['email'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['email']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="email" <?if($this->errors['email']){?>class="error"<?}?> name="email" maxlength="100" value="<?php echo $this->formValues['email']; ?>" />

								<div <?if($this->errors['companyName']){?>class="form_error"<?}?>>
								<p class="label">Company Name*</p>
								<?if($this->errors['companyName']){foreach ($this->errors['companyName'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['companyName']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="companyName" <?if($this->errors['companyName']){?>class="error"<?}?> name="companyName" maxlength="100" value="<?php echo $this->formValues['companyName']; ?>" />
								
								<div <?if($this->errors['tnid']){?>class="form_error"<?}?>>
								<p class="label">TradeNet ID</p>
								<?if($this->errors['tnid']){foreach ($this->errors['tnid'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['tnid']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="tnid" <?if($this->errors['tnid']){?>class="error"<?}?> name="tnid" maxlength="100" value="<?php echo $this->formValues['tnid']; ?>" />

								<div <?if($this->errors['contactName']){?>class="form_error"<?}?>>
								<p class="label">Your Name*</p>
								<?if($this->errors['contactName']){foreach ($this->errors['contactName'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['contactName']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="contactName" <?if($this->errors['contactName']){?>class="error"<?}?> name="contactName" maxlength="100" value="<?php echo $this->formValues['contactName']; ?>" />

								<div <?if($this->errors['contactPosition']){?>class="form_error"<?}?>>
								<p class="label">Your Position</p>
								<?if($this->errors['contactPosition']){foreach ($this->errors['contactPosition'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['contactPosition']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="contactPosition" <?if($this->errors['contactPosition']){?>class="error"<?}?> name="contactPosition" maxlength="100" value="<?php echo $this->formValues['contactPosition']; ?>" />


								<div <?if($this->errors['contactPhone']){?>class="form_error"<?}?>>
								<p class="label">Contact Phone Number</p>
								<?if($this->errors['contactPhone']){foreach ($this->errors['contactPhone'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['contactPhone']){?><div class="error_msg_arrow"></div><?}?>
								</div>
								<input type="text" id="contactPhone" <?if($this->errors['contactPhone']){?>class="error"<?}?> name="contactPhone" maxlength="100" value="<?php echo $this->formValues['contactPhone']; ?>" />

								<div <?if($this->errors['country']){?>class="form_error"<?}?>>
								<p class="label">Country</p>
								<?if($this->errors['country']){foreach ($this->errors['country'] as $key => $value){?>
									<p><?echo $value;?></p>
								<?}}?>
								<?if($this->errors['country']){?><div class="error_msg_arrow"></div><?}?>
								</div>

								<input type="text" id="country" <?if($this->errors['country']){?>class="error"<?}?> name="country" maxlength="100" value="<?php echo $this->formValues['country']; ?>" />

								<input type="submit" value="Request Access Code" style="margin:20px 0 0 140px; width:230px;"/>
							</form>
							<?php
							}
							?>
						</div>
					</div>
				</div>
				<div class="clear"></div>
				<div class="the_corner_piece"></div>
			</div>
			<div class="content_wide_footer_shadow"></div>
		</div>
	</div>
</div>