<?
$this->headLink()->appendStylesheet('/css/store/banner.css');
$this->getHelper('Requirejs')->addModule('backbone/store/banner/views/help');
?>
<div id="breadcrumbs">
	<span class="title">You are here: </span>
	<ul>
		<li>
			<a href="/">Home</a>
		</li>
		<li>
			<span></span>
			<a href="/info/pages-for-suppliers/webstore">WebStore</a>
		</li>
		<li class="current">
			<span></span>
			Banner Advertising
		</li>
	</ul>
</div>
<div id="body">
	<div id="content">
		<h1 class="styled">
			<a href="/info/contact-us/" class="button medium dblue" target="_blank">Contact us</a>
			<span>Banner Advertising</span>
		</h1>
		<div class="section">
			<p>
				Build your brand on ShipServ Pages with a flexible range of banner advertising. All of ShipServ’s visitors are purchasing professionals looking to source new suppliers. There are no casual browsers on Pages! This means you get your company in front of real buyers looking to buy real products with:
			</p>
			<ul class="checkList">
				<li>Over 2 million <span>Visits per Year</span></li>
				<li>Over 5 million <span>Page Views</span></li>
				<li>Over 3 million <span>Searches performed on ShipServ Pages</span></li>
			</ul>
			<table cellpadding="0" cellspacing="0" border="0" >
				<tbody>
					<tr>
						<td>
							<h2>General Banner Ad</h2>
							<p>Appear on the right-hand side of <strong>all search results and supplier profile pages</strong>. Ads are displayed when no Targeted Ads (see below) are available. A cost effective way to get started with advertising.</p>
						</td>
						<td rowspan="2"><a href="/img/store/banners_general_large.png" class="popup" rel="General Banner Ad"><img src="/img/store/general-banner.png" border="0" /></a></td>
					</tr>
					<tr>
						<td class="dark">
							<a href="/info/pages-for-suppliers/additional-member-solutions/banner-advertising/" class="button white medium" target="_blank">Find out more</a> 120,000 impressions from <strong>$4,500</strong><br /><br />
							<a href="/info/contact-us/" target="_blank">or contact us for more options</a>
						</td>
					</tr>
				</tbody>
			</table>
			<table cellpadding="0" cellspacing="0" border="0" >
				<tbody>
					<tr>
						<td>
							<h2>Targeted Banner Ad</h2>
							<p>A Targeted Banner Ad truly gives you the chance to focus your marketing spend on your <strong>target audience</strong>. With a Targeted Ad <strong>you can target specific categories, countries or even ports</strong> (e.g. Pumps in Singapore). Meaning your ad only appears against the specific searches relating to what your company sells.</p>
						</td>
						<td rowspan="2"><a href="/img/store/banners_targeted_large.png" class="popup" rel="Targeted Banner Ad"><img src="/img/store/targeted-banner.png" border="0" /></a></td>
					</tr>
					<tr>
						<td class="dark">
							<a href="/info/pages-for-suppliers/additional-member-solutions/banner-advertising/" class="button white medium" target="_blank">Find out more</a> Price from: <strong>$2,500</strong><br /><br />
							<a href="/contact-us/" target="_blank">Special offers currently available on targeted banners, contact us for more options</a>
						</td>
					</tr>
				</tbody>
			</table>
			<table cellpadding="0" cellspacing="0" border="0" >
				<tbody>
					<tr>
						<td>
							<h2>Targeted Banner Ad with Spotlight</h2>
							<p>Get even more visibility with a <strong>Targeted Banner Ad with Spotlight</strong>. This approach gives you the best chance of securing a PO by dominating a specified page. <strong>Spotlight listings appear above all premium listing and there can only be one per category.</strong></p>
						</td>
						<td rowspan="2"><a href="/img/store/banners_spotlight_large.png" class="popup" rel="Targeted Banner Ad with Spotlight"><img src="/img/store/targeted-spotlight-banner.png" border="0" /></a></td>
					</tr>
					<tr>
						<td class="dark">
							<a href="/info/pages-for-suppliers/additional-member-solutions/banner-advertising/" class="button white medium" target="_blank">Find out more</a> Price from: <strong>$5,000</strong><br /><br />
							<a href="/info/contact-us/" target="_blank">Special offers currently available on targeted banners with Spotlight, contact us for more options</a>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="contactBox">
				<p class="details">
					<strong>Tel:</strong> +44 203 111 9700 <br />
					<strong>Email:</strong> <a href="mailto:pages@shipserv.com">pages@shipserv.com</a>
				</p>
				<p class="contact">Contact our dedicated Supplier Sales Hotline:</p>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<div id="sidebar">
		<div class="topBar"></div>
		<ul id="nav">
			<li><a href="/info/pages-for-suppliers/webstore">ShipServ Membership</a></li>
			<li class="selected">Banner Advertising</li>
		</ul>
	</div>
	<div class="clear"></div>
</div>
<div id="modal">
    <div class="modalControls"><div class="close" data-dismiss="modal" aria-hidden="true">Close</div></div>
    <div class="modalBody"></div>
</div>