<?
$this->headLink()->appendStylesheet('/css/store/membership.css');
$this->getHelper('Requirejs')->addModule('backbone/store/membership/views/help');
?>
<div id="breadcrumbs">
	<span class="title">You are here: </span>
	<ul>
		<li>
			<a href="/">Home</a>
		</li>
		<li class="current">
			<span></span>
			WebStore
		</li>
		<li class="current">
			<span></span>
			ShipServ Membership
		</li>
	</ul>
</div>
<div id="body">
	<div id="content">
		<h1 class="styled">
			<a href="/info/contact-us/" class="button medium dblue" target="_blank">Contact us</a>
			<span>WebStore - Buy ShipServ Supplier Membership</span>
		</h1>
		<div class="section">
			<p class="sub">
				As a <strong>ShipServ Member</strong> you will receive access to all our core products. Win more business with a <strong>Premium Profile</strong> &amp; deal with your transactions more efficiently with <strong>SmartSupplier</strong>.
			</p>
			<table cellpadding="0" cellspacing="0" border="0" class="membershipTable">
				<thead>
					<tr>
						<th colspan="2">
							ShipServ Membership
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="memberInfo" />Membership Fee
						</td>
						<td class="right">
							<strong>$2,000</strong> per year
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="poInfo" />PO Fee
						</td>
						<td class="right">
							<strong>1.5%</strong> of PO value
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="creditsInfo" />Free credits
						</td>
						<td class="right">
							<strong>$150</strong><br />
							<span>
								With a PO fee of 1.5% this gives you $10,000 worth of orders through ShipServ
							</span>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="listingInfo" />Listing on Pages
						</td>
						<td class="right list">
							<strong>Premium Profile</strong>
							<ul>
								<li><span>Above basic listings</span></li>
								<li><span>More content than basic</span></li>
								<li><span>Higher ranking than basic</span></li>
								<li><span>Generates on average 20 times more responses than basic</span></li>
							</ul>
							<a href="#" class="xmpl">See example</a>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="orderInfo" />RFQ and Order Management tool
						</td>
						<td class="right">
							<strong>SmartSupplier</strong><br />
							<span>
								Easy to use outlook style order management system
							</span><br />
							<a href="#" class="smart">See example</a>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="trackInfo" class="upper" /><span class="upper">Track results with Supplier Insight Report</span>
						</td>
						<td class="right">
							<div class="check"></div>
							<a href="#" class="sir">See example</a>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="catInfo" class="up" /><span class="up">Upload online catalogue</span>
						</td>
						<td class="right">
							<div class="check"></div>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="logoInfo" class="up" /><span class="up">Show company logo</span>
						</td>
						<td class="right">
							<div class="check"></div>
						</td>
					</tr>
					<tr>
						<td>
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="salesDocInfo" class="up" /><span class="up">Attach sales documents to profile</span>
						</td>
						<td class="right">
							<div class="check"></div>
						</td>
					</tr>
					<tr>
						<td class="last">
							<input type="image" src="/img/icons/small/help_light.png" alt="Info" name="accManInfo" class="up" /><span class="up">Named Account Manager & 24/7 Support</span>
						</td>
						<td class="right last">
							<div class="check"></div>
						</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td>
							&nbsp;
						</td>
						<td class="right">
							<a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=51" class="button large green">Add to cart</a><div class="clear"></div>
							<p class="small italic">(Once purchased you will be contacted by a ShipServ Representative to get you Setup)</p>
						</td>
					</tr>
				</tfoot>
			</table>
			<h2>More information:</h2>
			<div class="benefits">
				<div class="checklist"></div>
				<h3>Membership Benefits</h3>
				<div class="buttons">
					<a href="/info/pages-for-suppliers/" class="button medium white" target="_blank">Learn More</a>
					<a href="/img/mu/member_2016.pdf" class="button medium white pdf" target="_blank"><img src="/img/icons/medium/pdf.png" border="0">Download PDF</a>
				</div>
				<div class="clear"></div>
			</div>
			<h2>Credit Packs &amp; Current Bonus Levels</h2>
			<p>
				Purchase pre-paid credit packs &amp; receive bonus credits from ShipServ. By buying larger packs you will receive a larger percentage of free credits, see table below.
			</p>
			<p>
				All value event charges need to be paid through credits. Value event charges are debited against your credit balance on a daily basis. Your balance needs to remain in credit at all times.
			</p>

 			<table cellpadding="0" cellspacing="0" border="0" class="creditPayments">
				<thead>
					<tr>
						<th>You pay</th>
						<th>&nbsp;</th>
						<th>We add bonus credits<sup>*</sup></th>
						<th>You get</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>$ 500</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=52" class="button small green">Buy</a></td>
						<td>$ 0</td>
						<td>$ 500</td>

					</tr>
					<tr>
						<td>$ 1,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=53" class="button small green">Buy</a></td>
						<td>$ 50</td>
						<td>$ 1,050</td>
					</tr>
					<tr>

					<tr>
						<td>$ 3,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=56" class="button small green">Buy</a></td>
						<td>$ 200</td>
						<td>$ 3,200</td>
					</tr>
					<tr>
						<td>$ 5,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=55" class="button small green">Buy</a></td>
						<td>$ 400</td>
						<td>$ 5,400</td>
					</tr>
					<tr>
						<td>$ 10,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=57" class="button small green">Buy</a></td>
						<td>$ 900</td>
						<td>$ 10,900</td>
					</tr>

					<tr>
						<td>$ 25,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=58" class="button small green">Buy</a></td>
						<td>$ 2,500</td>
						<td>$ 27,500</td>
					</tr>

					<tr>
						<td>$ 50,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=59" class="button small green">Buy</a></td>
						<td>$ 5,750</td>
						<td>$ 55,750 </td>
					</tr>

					<tr>
						<td>$ 75,000</td>
						<td><a href="http://store.shipserv.com/index.asp?function=CART&mode=ADD&productid=60" class="button small green">Buy</a></td>
						<td>$ 9,500</td>
						<td>$ 84,500</td>
					</tr>
					
				</tbody>
			</table>
			<p class="details">
				<sup>*</sup>Please note, the bonus credits are a special offer and subject to change or withdrawal at any time.<br /><br />
			</p>

			<div class="contactBox">
				<p class="details">
					<strong>Tel:</strong> +44 203 111 9700 <br />
					<strong>Email:</strong> <a href="mailto:pages@shipserv.com">pages@shipserv.com</a>
				</p>
				<p class="contact">Contact our dedicated Supplier Sales Hotline:</p>
				<div class="clear"></div>
			</div>
			<p>
				<a href="/store/banner">Learn more about Banner Advertising</a>
			</p>
			<p class="small"><a href="http://store.shipserv.com/terms-conditions.asp">Terms &amp; conditions</a> apply for all these services.</p>
		</div>
	</div>
	<div id="sidebar">
		<div class="topBar"></div>
		<ul id="nav">
			<li class="selected">ShipServ Membership</li>
			<li><a href="/store/banner">Banner Advertising</a></li>
		</ul>
	</div>
	<div class="clear"></div>
</div>
<div id="modal">
    <div class="modalControls"><div class="close" data-dismiss="modal" aria-hidden="true">Close</div></div>
    <div class="modalBody"></div>
</div>
<div id="modalBig">
    <div class="modalControls"><div class="close" data-dismiss="modal" aria-hidden="true">Close</div></div>
    <div class="modalBody"></div>
</div>