<? $this->headLink()->appendStylesheet('/css/erroneous-trans-landing.css'); ?>
<div id="body">
   <div id="content" class="size3">
        <h1 class="styled">Erroneous Transaction</h1>    
        <div class="inner_content">
            <div class="greenInfo"><i class="fa fa-exclamation-triangle"></i></i> Whoops, Something went wrong</div>
            <a href="/" class="homePageBtn">Go to Homepage</a>
       </div>        
	</div>
</div>