<?php
    $this->headLink()->appendStylesheet('/css/reports/match.css')
                     ->appendStylesheet('/css/uniform.rfq.css');

    $this->getHelper('Requirejs')->addModule('backbone/reports/matchReport/views/mainView')
                                 ->addDefinition('reports/match/buyerId', $this->buyerId)
                                 ->addDefinition('reports/match/vesselName', '"' . $this->vesselName . '"')
                                 ->addDefinition('reports/match/fromDate', '"' . $this->fromDate . '"')
                                 ->addDefinition('reports/match/toDate', '"' . $this->toDate . '"');

    $user = Shipserv_User::isLoggedIn();

    $shipservUser = $user->isShipservUser();
?>
<div id="breadcrumbs">
    <span class="title">You are here: </span>
    <ul>
        <li>
            <a href="/">Home</a>
        </li>
        <li>
            <span></span>
            <a href="/reports/match-supplier-report">Analyse</a>
        </li>
        <li class="current">
            <span></span>
            Sourcing Engine Transactions
        </li>
    </ul>
</div>

<div id="body" class="liquid">
    <div id="content">
        <h1 class="styled header">Transactions Processed by the Sourcing Engine</h1>
        <div class="summarySection"></div>
        <div class="filterSection"></div>
        <table class="rfqList" cellpadding="0" cellspacing="0">
            <thead>

            </thead>
            <tbody>

            </tbody>
        </table>
        <input type="button" class="button medium dblue" name="back" value="Back to RFQs">
        <div class="pagination"></div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<div id="modal">
    <div class="modalControls"><div class="close" data-dismiss="modal" aria-hidden="true">Close</div></div>
    <div class="modalBody"></div>
</div>
<div id="waiting">
    <div class="waitingMessage">Loading...</div>
    <div class="waitingMask"></div>
</div>
