<?php 	
	echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>ShipServ TradeNet Application Login</title>
<meta name='robots' content='noindex,nofollow' />
<?php
	echo $this->CDNLink()."\n";
	echo $this->headLink()."\n";
	echo $this->headMeta()."\n";
	$this->requirejs()->render();
	echo $this->headScript()."\n";
	echo $this->compressedScript()."\n";
?>
	
</head>
<body>
	<!-- Google Tag Manager -->
	<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PD4KM6" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-PD4KM6');</script>
	<!-- End Google Tag Manager -->
	<?php echo $this->layout()->content ?>
	<script src="https://www.google.com/recaptcha/api.js" async defer></script>
</body>
</html>

