<!DOCTYPE html>
<html>
	<?= $this->partial('application-signature.phtml', array());?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<?php if ($_SERVER['HTTP_HOST'] !== 'www.shipserv.com') {?> 
		<meta name="robots" content="noindex">
	<?php } ?>
	<?php if ($_SERVER['APPLICATION_ENV'] !== 'development') {?>
		<script type="text/javascript">
			window.onerror = function catchAndLogError(msg, url, lineno, colno, error) {
				console.log('catchAndLogError SS func>>> Error message: '+msg+'\nURL: '+url+'\nLine: '+lineno+' Col: '+colno+'\nError: '+error);
				return true;
			}
		</script>
	<?php } ?>
	<!--[if lt IE 9]>
  	<script src="/js/<?php echo Myshipserv_Config::getCachebusterTagAddition() ?>lib/html5shiv.min.js"></script>
  	<![endif]-->
	<?php
	echo $this->headTitle()."\n";
	
	$req = Zend_Controller_Front::getInstance()->getRequest();
	echo $this->CDNLink()->prependStylesheet('/css/default.css')->prependStylesheet('/css/reset.css');

	if (!($_SERVER['HTTP_X_REQUESTED_WITH'] == "XMLHttpRequest") && !($_SERVER['REQUEST_URI'] == "/favicon.ico" )) {
		if ($this->canonical != '') {
	    	$pageURL = $this->canonical;
		} else {
	        switch ($_SERVER['HTTP_HOST']) {
	        	case 'www.shipserv.net':
	            case 'www.shipserv.com.tr':
	            	$server = 'www.shipserv.com';
	                break;
	            default:
	            	$server = $_SERVER['HTTP_HOST'];
	   	 	}

	        $pageURL = 'http://' . $server . str_replace('?' . $_SERVER['QUERY_STRING'], '', $_SERVER['REQUEST_URI']);
	        $pageURL = preg_replace('/\/$/i', '', $pageURL);
	        $pageURL = preg_replace('/\/zone$/i', '', $pageURL);
		}
		if ($this->canonical !== false) {
			$this->headLink()->headLink(array('rel'  => 'canonical', 'href' => $pageURL), 'PREPEND');
		}
	}

	echo $this->headLink()."\n";
	echo $this->headMeta()."\n";
	if (!$this->isCorporate) {
		$this->requirejs()->render();
	} else {
		?>
		<script type="text/javascript" src="/js/<?php echo Myshipserv_Config::getCachebusterTagAddition() ?>modules/backbone/lib/jquery.min.1.8.3.js"></script>
		<?php
	}

	echo $this->headScript()."\n";
	echo $this->compressedScript()."\n";

	?>
	<script type="text/javascript" src="/js/<?php echo Myshipserv_Config::getCachebusterTagAddition() ?>lib/cookieAlert.js"></script>
	<script type="text/javascript" src="/js/<?php echo Myshipserv_Config::getCachebusterTagAddition() ?>navigation.js"></script>
	<?php
	if ($this->isCorporate || ($req->getModuleName() === 'search' && $req->getControllerName() === 'index' && $req->getActionName() === 'index')) {
		?>
		<script type="text/javascript" src="/js/<?php echo Myshipserv_Config::getCachebusterTagAddition() ?>ie-flex-fix.js"></script>
		<?php
	}
	
	if ((Myshipserv_Config::isInProduction() || Myshipserv_Config::isInUat()) && isset($this->params['enableConsoleLog']) == false) { ?>
		<script type="text/javascript">
			var console = {};
			console.log = function(){};
		</script>
	<?php } ?>
	</head>
	<body>
		<?= $this->partial('layout/upgrade-browser-warning.phtml'); ?>
		<?= $this->partial('layout/tag-manager.phtml', array('config' => $this->config));?>
		<header>
			<a href="/search"><img src="/img/logo.svg" alt="ShipServ logo" width="150"></a>
		</header>
		<div class="headerSpace"></div>
		<?= $this->partial('layout/corporate-tabs-lev2.phtml'); ?>
		<div class="scrollWrapper">
			<main>
				<?= $this->layout()->content ?>
			</main>
		</div>
		<div id="preHeader"></div>
	</body>
</html>