<?php echo nl2br($this->text)?>
<br/><br/>
Dear Supplier,<br/><br/>

<?php echo $this->companyInfo["name"];?> is inviting you to join ShipServ Pages, the premier on-
line directory of marine suppliers.<br/><br/>

Pages is a specialised listing service and search engine for
operational ship supplies which helps suppliers market their business
to maritime purchasers world-wide. Marine suppliers also use Pages to
promote their resellers and agents: <?php echo $this->companyInfo["name"];?> would like to add
you to their Pages network in this capacity.<br/><br/>

Signing up to ShipServ Pages is quick and simple. Follow this link now
to set up a free listing and join <?php echo $this->companyInfo["name"];?> supply network:<br/><br/>

<a href="<?php echo $this->link;?>"><?php echo $this->link;?></a>