Dear ShipServ User<br /><br />

A new account has been created for you on ShipServ Pages, the on-line maritime<br />
supplier directory.<br /><br />

Username: <?php echo $this->data['user']->username ?><br />
Password: <?php echo $this->data['password'] ?><br /><br />

Come and visit us here:<br /><br />

<a href="<?php echo $this->data['links']['homepage'] ?>"><?php echo $this->data['links']['homepage'] ?></a><br />
