<?php
	$displayErrorCount = 3;
	$ordDate = '';
	$isPayingCustomer = ((float)$this->supplier->monetisationPercent > 0);
	if ($this->order->ordSubmittedDate) {
	    $date = new DateTime($this->order->ordSubmittedDate);
	   // $ordDate = $date->format('Y-m-d H:i:s') . ' UTC';
	    $ordDate = $date->format('d M Y');
	}

	$isStartSupplier = ($this->supplier->getIntegrationType() ==  'START_SUPPLIER');
?>
	<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td>&nbsp;</td>
			<td style="height: 30px; font-size: 1px; width: 600px; max-width: 600px;">&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>
				<table style="width: 600px; max-width:600px; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0" width="600">
					<tr>
						<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
						<td style="height: 80px; vertical-align: middle; background-color: #002f5f;">
							<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/logo.png" border="0" style="margin: 0; padding: 0;" alt="ShipServ">
						</td>
						<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
							<? if( $this->sendToGsd === true ): ?>
								Dear ShipServ support,<br><br>
								It has been <?php echo  Myshipserv_Poller_ErroneousTransactionMonitor::DAYS_BEFORE_SECOND_REMINDER + Myshipserv_Poller_ErroneousTransactionMonitor::DAYS_BEFORE_ALERTING_GSD ?> days since they sent this erroneous transaction.<br>
								Please contact both of them for assistance.
							<? else: ?>
								Dear ShipServ customer, <?= ($this->isSecond) ? '(reminder)' : '' ; ?>
							<? endif ?>
						</td>
						<td style="width: 20px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? if ($this->recepientType === Myshipserv_NotificationManager_Email_ErroneousTransaction::RECIPIENT_BUYER): ?>
						<tr>
							<td style="width: 20px;">&nbsp;</td>
							<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
								Your supplier has indicated that a purchase order that you have issued<br>
								to them is incorrect
							</td>
							<td style="width: 20px;">&nbsp;</td>
						</tr>
						<tr>
							<td style="width: 20px; font-size: 1px;">&nbsp;</td>
							<td style="height: 15px; font-size: 1px;">
								&nbsp;
							</td>
							<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						</tr>
						<? if (strlen($this->buyerMessage) > 0): ?>
							<tr>
								<td style="width: 20px;">&nbsp;</td>
								<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #14b5eb; font-weight:bold;">
									Message from the supplier
								</td>
								<td style="width: 20px;">&nbsp;</td>
							</tr>
							<tr>
								<td style="width: 20px; font-size: 1px;">&nbsp;</td>
								<td style="height: 15px; font-size: 1px;">
									&nbsp;
								</td>
								<td style="width: 20px; font-size: 1px;">&nbsp;</td>
							</tr>
							<tr>
								<td style="width: 20px;">&nbsp;</td>
								<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
									<?= nl2br(htmlentities($this->buyerMessage)); ?>
								</td>
								<td style="width: 20px;">&nbsp;</td>
							</tr>
						<? endif ?>
					<? else: ?>
						<tr>
							<td style="width: 20px;">&nbsp;</td>
							<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
								You have received a Purchase Order that <span style="font-weight: bold; color: #D0021B;">may be incorrect.</span>
							</td>
							<td style="width: 20px;">&nbsp;</td>
						</tr>
					<? endif ?>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? if( $this->sendToGsd === false ): ?>
					<tr>
						<td style="width: 20px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
						<td style="height: 10px; font-size: 1px; background: #FBE6E8;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
					</tr>

					<? if ($this->recepientType === Myshipserv_NotificationManager_Email_ErroneousTransaction::RECIPIENT_BUYER): ?>
						<tr>
							<td style="width: 20px; background: #FBE6E8;">&nbsp;</td>
							<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; background: #FBE6E8; vertical-align: middle; line-height: 28px; height: 28px;">
								<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/attention.png" border="0" style="margin: 0; padding: 0; vertical-align: top;" alt="Attention">&nbsp;&nbsp;You need to re-issue the PO with the mistake(s) rectified.
							</td>
							<td style="width: 20px; background: #FBE6E8;">&nbsp;</td>
						</tr>
					<? else: ?>
						<tr>
							<td style="width: 20px; background: #FBE6E8;">&nbsp;</td>
							<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; background: #FBE6E8; vertical-align: middle; line-height: 28px; height: 28px;">
								<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/attention.png" border="0" style="margin: 0; padding: 0; vertical-align: top;" alt="Attention">&nbsp;&nbsp;Please check this PO carefully and respond by selecting one of the two options below to make sure your invoice, Sales Funnel and Supplier Insight Report on www.shipserv.com appear correctly.
							</td>
							<td style="width: 20px; background: #FBE6E8;">&nbsp;</td>
						</tr>
					<? endif ?>
					<tr>
						<td style="width: 20px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
						<td style="height: 10px; font-size: 1px; background: #FBE6E8;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
					</tr>
					<? endif ?>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
						<td style="background: #EFF1F5;">
							<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width: 410px; height: 60px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #005AAD; line-height: 60px; vertical-align: middle; border-bottom: 1px solid #979797;">
										Purchase Order: <?php echo htmlentities($this->order->ordRefNo); ?>
									</td>
									<td style="vertical-align: middle; text-align: right; border-bottom: 1px solid #979797;">
										<a href="<?php echo $this->order->getUrl()?>" style="text-decoration: none;">
											<img style="border: none;" src="<?= Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname;?>/images/email/buttons/view-order.png" alt="View this order">
										</a>
									</td>
								</tr>
								<tr>
									<td style="height: 10px;">&nbsp;</td>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td colspan="2" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
										<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="width:115px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">Subject:</td>
												<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;"><?php echo htmlentities($this->order->ordSubject); ?></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td style="height: 10px;">&nbsp;</td>
									<td>&nbsp;</td>
								</tr>
								<? if ($this->recepientType === Myshipserv_NotificationManager_Email_ErroneousTransaction::RECIPIENT_BUYER): ?>
									<tr>
										<td colspan="2" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
											<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="width:115px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">Supplier:</td>
												<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;"><?php echo htmlentities($this->supplier->name); ?> (<?php echo $this->supplier->tnid; ?>)</td>
											</tr>
										</table>
										</td>
									</tr>
								<? else: ?>
									<tr>
										<td colspan="2" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
											<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td style="width:115px;font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">Buyer:</td>
													<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;"><?php echo htmlentities($this->buyer->bybName); ?> (<?php echo $this->buyer->bybBranchCode; ?>)</td>
												</tr>
											</table>
										</td>
									</tr>
								<? endif ?>
								<tr>
									<td style="height: 10px;">&nbsp;</td>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td colspan="2" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
										<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="width:115px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">Vessel:</td>
												<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;"><?php echo htmlentities($this->order->ordVesselName); ?> <?php if (strlen($this->order->ordImoNo)) { echo '(' . htmlentities($this->order->ordImoNo) . ')'; } ?></td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td style="height: 10px;">&nbsp;</td>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
										<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="width:115px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">PO sent date:</td>
												<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;"><?php echo $ordDate; ?></td>
											</tr>
										</table>
									</td>
									<td>&nbsp;</td>
								</tr>
							</table>
						</td>
						<td style="width: 20px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px; background: #EFF1F5;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? if(  $this->data['BIG_ORDER_CHECK'] == 1 ): ?>
					<tr>
						<td colspan="3">
							<table style="width: 600px; max-width: 600px; border-collapse: collapse; table-layout: fixed; border-top: 1px solid #000000; border-left: 1px solid #000000;" cellpadding="0" cellspacing="0" border="0" width="600">
								<tr>
									<td style="width: 20px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-right: 1px solid #000000; border-bottom: 1px solid #000000; height: 50px; width: 385px; line-height: 110%; vertical-align: middle;">
										Purchase Order
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; line-height: 110%; vertical-align: middle;">
										Possible error
									</td>
									<td style="width: 20px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-size: 1px; background: #FBE6E8;">
										&nbsp;
									</td>
									<td style="width: 20px; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
								
								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; border-right: 1px solid #000000; width: 385px; vertical-align: top;">
										Total order value: <?= $this->data['ORD_CURRENCY'] ?> <?= Myshipserv_Helper_NumberFormat::bankerNumberFormat($this->data['ORD_TOTAL_COST']); ?>
									</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #D0021B; background: #FBE6E8; vertical-align: top;">
										Unusually high order value
									</td>
									<td style="width: 20px;border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000; background: #FBE6E8;">&nbsp;</td>
									<td style="font-size: 1px; border-bottom: 1px solid #000000; background: #FBE6E8;">
										&nbsp;
									</td>
									<td style="width: 20px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
							</table>
							
						</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? endif ?>
					<?if( $this->data['CURRENCY_CHECK'] == 1 ): ?>
					<tr>
						<td colspan="3">
							
							<table style="width: 600px; border-collapse: collapse; table-layout: fixed; border-top: 1px solid #000000; border-left: 1px solid #000000;" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width: 20px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-right: 1px solid #000000; border-bottom: 1px solid #000000; height: 50px; line-height: 120%; vertical-align: middle; width: 150px;">
										Quote
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-right: 1px solid #000000; border-bottom: 1px solid #000000; height: 50px; line-height: 120%; vertical-align: middle; width: 150px;">
										Purchase Order
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; line-height: 120%; vertical-align: middle; width: 230px;">
										Possible error
									</td>
									<td style="width: 20px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-size: 1px; background: #FBE6E8;">
										&nbsp;
									</td>
									<td style="width: 20px; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>

								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; border-right: 1px solid #000000; vertical-align: top;">
										Quote amount: <br>
										<strong><?= Myshipserv_Helper_NumberFormat::bankerNumberFormat($this->data['QOT_TOTAL_COST']);?></strong><br><br>

										Quote currency: <br>
										<strong><?= $this->data['QOT_CURRENCY'] ?></strong>
									</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; border-right: 1px solid #000000; vertical-align: top;">
										PO amount: <br>
										<strong><?= Myshipserv_Helper_NumberFormat::bankerNumberFormat($this->data['ORD_TOTAL_COST']); ?></strong><br><br>

										PO currency: <br>
										<strong><?= $this->data['ORD_CURRENCY'] ?></strong>
									</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #D0021B; background: #FBE6E8; vertical-align: top;">
										PO currency type is different from quote currency type but price value has not changed accordingly.
									</td>
									<td style="width: 20px;border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 20px; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">&nbsp;</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? endif ?>
					<? if(  $this->data['UNIT_PRICE_CHECK'] == 1 ): ?>
					<tr>
						<td colspan="3">
							
							<table style="width: 600px; border-collapse: collapse; table-layout: fixed; border-top: 1px solid #000000; border-left: 1px solid #000000;" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width: 20px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-bottom: 1px solid #000000; height: 60px; line-height: 120%; vertical-align: middle;width:25px; word-break: none;">
										No
									</td>
									<td style="width: 20px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>

									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; line-height: 120%; vertical-align: middle;width:100px;">
										PO Item
									</td>
									<td style="width: 20px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; vertical-align: middle ; text-align: center;">
										Quote<br>
										price/unit<br>
										(<?= $this->data['QOT_CURRENCY'] ?>)
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; vertical-align: middle; text-align: center;">
										PO<br>
										price/unit<br>
										(<?= $this->data['ORD_CURRENCY'] ?>)
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; font-weight: bold; border-bottom: 1px solid #000000; height: 50px; line-height: 120%; vertical-align: middle; width: 157px;">
										Possible error
									</td>
									<td style="width: 15px; border-bottom: 1px solid #000000; border-right: 1px solid #000000; font-size: 1px;">&nbsp;</td>
								</tr>
								<? $errorCount = 0 ?>
								<? foreach( $this->data['lineItems'] as $li) :?>

								<?php
									$errorCount ++;
									if ($displayErrorCount >= $errorCount) {
										$qot = explode('<ss>', $li['QUOTE_LI_DESC']);
										$ord = explode('<ss>', $li['ORDER_LI_DESC']);
								?>
								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px;">
										&nbsp;
									</td>
									<td style="width: 20px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px;">
										&nbsp;
									</td>
									<td style="width: 20px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-size: 1px; background: #FBE6E8;">
										&nbsp;
									</td>
									<td style="width: 15px; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; vertical-align: top; text-align:center;">
										<?= $li['OLI_ORDER_LINE_ITEM_NO'] ?> 
									</td>
      								<td style="width: 20px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>

									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #000000; vertical-align: top; word-break: break-all; overflow: hidden;">
										<?= $ord[0]?>
									</td>
									<td style="width: 20px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; vertical-align: top; text-align: center;">
										<? echo Myshipserv_Helper_NumberFormat::bankerNumberFormat($li['QLI_UNIT_COST']) . '<br>' . $li['QLI_UNIT']?>
									</td>
									<td style="width: 15px; font-size: 1px; border-right: 1px solid #000000; ">&nbsp;</td>
									<td style="width: 15px; font-size: 1px;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; vertical-align: top; text-align: center;">
										<? echo Myshipserv_Helper_NumberFormat::bankerNumberFormat($li['OLI_UNIT_COST']) . '<br>' . $li['OLI_UNIT']?>
									</td>
									<td style="width: 15px; font-size: 1px; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #D0021B; background: #FBE6E8; vertical-align: top;">
										PO line item unit price is 
										<? if ($li['QLI_UNIT_COST'] > $li['OLI_UNIT_COST']): ?>
											<? echo ($li['OLI_UNIT_COST'] != 0) ? round($li['QLI_UNIT_COST'] / $li['OLI_UNIT_COST']) : '' ?>x
										<? else: ?>
											<? echo ($li['QLI_UNIT_COST'] != 0) ? round($li['OLI_UNIT_COST'] / $li['QLI_UNIT_COST'] ) : ''; ?>x
										<? endif ?>
										<? echo ($li['QLI_UNIT_COST'] > $li['OLI_UNIT_COST']) ? ' lower' : ' higher'?> than quote unit price.
									</td>
									<td style="width: 15px;border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8;">&nbsp;</td>
								</tr>
								<tr>
									<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; height: 15px; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; font-size: 1px; border-bottom: 1px solid #000000; border-right: 1px solid #000000;">&nbsp;</td>
									<td style="width: 15px; font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">&nbsp;</td>
									<td style="font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">
										&nbsp;
									</td>
									<td style="width: 15px; border-right: 1px solid #000000; font-size: 1px; background: #FBE6E8; border-bottom: 1px solid #000000;">&nbsp;</td>
								</tr>
								<? } ?>
								<? endforeach ?>
							</table>
						
						</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 15px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<? endif ?>
					<? if ($errorCount - $displayErrorCount>0): ?>
					<tr>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; vertical-align: middle;" colspan="3">
							*This PO has a further <?= $errorCount - $displayErrorCount ?> possible errors
						</td>
					</tr>
					<? endif ?>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<?php if( $this->recepientType === Myshipserv_NotificationManager_Email_ErroneousTransaction::RECIPIENT_SUPPLIER && $this->sendToGsd === false ): ?>
					<tr>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #D0021B; vertical-align: middle;" colspan="3">
						
							<table style="width: 600px; border-collapse: collapse; table-layout: fixed; border-top: 1px solid #979797; border-left: 1px solid #979797;" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width: 15px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="width: 283px;background: #EFF1F5; border-right: 1px solid #979797; font-size: 1px; height: 10px;">&nbsp;</td>
									<td style="width: 16px; font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="width: 283px; background: #EFF1F5; border-right: 1px solid #979797; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; background: #EFF1F5; vertical-align: middle; line-height: 28px; height: 28px; border-right: 1px solid #979797;">
										<table style="width: 100%; border-collapse: collapse; " cellpadding="0" cellspacing="0" border="0" widht="100%">
											<tr>
												<td style="width: 39px; vertical-align: middle;"><img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/check.png" border="0" style="padding: 0; vertical-align: top;" alt="correct"></td>
												<td style="vertical-align: middle; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">If you think this is correct</td>
											</tr>	
										</table>
									</td>
									<td style="font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; background: #EFF1F5; vertical-align: middle; line-height: 28px; height: 28px; border-right: 1px solid #979797;">
										<table style="width: 100%; border-collapse: collapse; " cellpadding="0" cellspacing="0" border="0" widht="100%">
											<tr>
												<td style="width: 39px; vertical-align: middle;"><img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/x.png" border="0" style="padding: 0; vertical-align: top;" alt="incorrect"></td>
												<td style="vertical-align: middle; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">If you think this is <span style="color: #D0021B">not</span> correct</td>
											</tr>	
										</table>
									</td>
								</tr>
								<tr>
									<td style="font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="background: #EFF1F5; border-right: 1px solid #979797; font-size: 1px; height: 10px;">&nbsp;</td>
									<td style="font-size: 1px; background: #EFF1F5;">&nbsp;</td>
									<td style="background: #EFF1F5; border-right: 1px solid #979797; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td style="font-size: 1px;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px; height: 20px;">&nbsp;</td>
									<td style="font-size: 1px;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td colspan= "2" style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; vertical-align: top; line-height: 28px; height: 28px; border-right: 1px solid #979797; text-align: center;">
										<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td>&nbsp;</td>
												<td style="width: 250px; vertical-align: top;">
													<table style="border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0" width="250">
														<tr>
															<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #008B00;">&nbsp;</td>
														</tr>
														<tr>
															<td style="vertical-align: middle; height: 20px; width: 250px; background: #008B00; text-align: center;">	
																<a style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #FFFFFF; line-height: 20px;" href="<?= Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname;?>/supplier/erroneous-reply?answ=acc&id=<?php echo $this->order->ordInternalRefNo ?>&h=<?php echo md5($this->order->ordInternalRefNo.'_acc_ord') ?>">
																	Confirm correct as issued
																</a>
															</td>
														</tr>
														<tr>
															<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #008B00;">&nbsp;</td>
														</tr>
													</table>
													
												</td>
												<td>&nbsp;</td>
											</tr>
										</table>
									</td>
									<td colspan= "2" style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; vertical-align: top; line-height: 28px; min-height: 28px; border-right: 1px solid #979797; text-align: center;">
										<? if ($isStartSupplier): ?>
											<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td>&nbsp;</td>
													<td style="width: 250px; vertical-align: top;">
														
														<table style="border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0" width="250">
														<tr>
															<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
														</tr>
															<tr>
																<td style="width: 250px; height:20px; background: #D0021B; text-align: center; vertical-align: middle;">
																	<a style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #FFFFFF;  line-height: 20px;" href="<?=Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname;?>/supplier/erroneous-reply?answ=sen&id=<?php echo $this->order->ordInternalRefNo ?>&h=<?php echo md5($this->order->ordInternalRefNo.'_sen_ord') ?>">
																		Request buyer reissues PO
																	</a>
																</td>
															</tr>
															<tr>
																<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
															</tr>
														</table>
														
													<td>&nbsp;</td>
												</tr>
											</table>
										<? else: ?>
										<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="height: 85px; line-height: 20px; text-align:center; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
													Go to SmartSupplier or your own<br>
													system to issue a correcting POC<br>
													or request that the buyer reissues<br>
													the PO via the option below.<br>
												</td>
											</tr>
										</table>	
										<? endif ?>
									</td>
								</tr>
								
								<tr>
									<td style="font-size: 1px;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px; height: 15px;">&nbsp;</td>
									<td style="font-size: 1px;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px;">&nbsp;</td>
								</tr>
								<tr>
									<td colspan= "2" style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; vertical-align: middle; line-height: 28px; height: 28px; border-right: 1px solid #979797;">
										&nbsp;
									</td>
									<td colspan= "2" style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; color: #000000; vertical-align: middle; line-height: 28px; height: 28px; border-right: 1px solid #979797; text-align: center;">
										<? if ($isStartSupplier): ?>
											<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td>&nbsp;</td>
													<td style="width: 250px;">
														
														<table style="border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0" width="250">
															<tr>
																<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
															</tr>
															<tr>
																<td style="vertical-align: middle;  height: 20px; width: 250px; background: #D0021B; text-align: center;">
																	<a style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #FFFFFF; line-height: 20px;" href="<?= $this->startSupplierURL; ?>">
																		I will send a correcting POC
																	</a>
																</td>
															</tr>
															<tr>
																<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
															</tr>
														</table>
													<td>&nbsp;</td>
												</tr>
											</table>
										<? else: ?>

										<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td>&nbsp;</td>
													<td style="width: 250px;">

													<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0" width="250">
														<tr>
															<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
														</tr>
														<tr>
															<td style="width: 250px; height: 20px; background: #D0021B; text-align: center;">
																<a style="text-decoration: none; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #FFFFFF; vertical-align: middle; line-height: 20px;" href="<?= Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname;?>/supplier/erroneous-reply?answ=sen&id=<?php echo $this->order->ordInternalRefNo ?>&h=<?php echo md5($this->order->ordInternalRefNo.'_sen_ord') ?>">Request buyer reissues PO</a>
														</tr>
														<tr>
															<td style="font-size: 1px; height:5px; line-height: 1px; padding:0;background: #D0021B;">&nbsp;</td>
														</tr>
													</table>

												<td>&nbsp;</td>
												</tr>
											</table>

										<? endif ?>
									</td>
								</tr>
								<tr>
									<td style="font-size: 1px; border-bottom: 1px solid #979797;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px; height: 20px; border-bottom: 1px solid #979797;">&nbsp;</td>
									<td style="font-size: 1px; border-bottom: 1px solid #979797;">&nbsp;</td>
									<td style="border-right: 1px solid #979797; font-size: 1px; border-bottom: 1px solid #979797;">&nbsp;</td>
								</tr>
							</table>
							
						</td>
					</tr>
					<?php endif ?>
					<? if ($this->recepientType === Myshipserv_NotificationManager_Email_ErroneousTransaction::RECIPIENT_BUYER): ?>
								<tr>
									<td colspan="4">
											<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#ffffff;">&nbsp;</td>
													<td style="background-color:#ffffff;font-size: 16px;">Please re-issue the PO with the issue corrected. If you think the PO is</td>
													<td style="font-size: 1px; width: 20px;background-color:#ffffff;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#ffffff;">&nbsp;</td>
													<td style="background-color:#ffffff;font-size: 16px;">correct as issued please contact the supplier.</td>
													<td style="font-size: 1px; width: 20px;background-color:#ffffff;">&nbsp;</td>
												</tr>
												
												<tr>
													<td style="font-size: 1px; width: 20px;height: 20px;background-color:#ffffff;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#ffffff;">&nbsp;</td>
													<td style="font-size: 1px; width: 20px;background-color:#ffffff;">&nbsp;</td>
												</tr>
											</table>
									</td>
								</tr>
								<tr>
									<td colspan="4">
											<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
												<tr>
													<td style="font-size: 1px; width: 20px;height: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td colspan="2" style="background-color:#cbedf9;font-weight: bold;font-size: 16px;">Supplier contact details</td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;height: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="background-color:#cbedf9;font-size: 16px;">Contact:</td>
													<td style="background-color:#cbedf9;font-size: 16px;"><?= htmlentities($this->supplier->name); ?> (<?= htmlentities($this->quote->qotContact); ?>)</td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="background-color:#cbedf9;font-size: 16px;">Phone:</td>
													<td style="background-color:#cbedf9;font-size: 16px;"><?= htmlentities($this->quote->qotPhoneNo); ?></td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												  
												<tr>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="background-color:#cbedf9;font-size: 16px;">Email:</td>
													<td style="background-color:#cbedf9;"><?= htmlentities($this->quote->qotEmailAddress); ?></td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
												<tr>
													<td style="font-size: 1px; width: 20px;height: 20px;background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; background-color:#cbedf9;">&nbsp;</td>
													<td style="font-size: 1px; width: 20px;background-color:#cbedf9;">&nbsp;</td>
												</tr>
											</table>
									</td>
								</tr>
					<? endif ?>
					<tr>
						<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; text-align: center;">
							If you are unable to respond to this transaction via ShipServ, or require <br> other assistance visit our <a href="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/support/" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #0070BB;">support page</a> or email: <a href="mailto: support@shipserv.com" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #0070BB;">support@shipserv.com</a>
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
					</tr>
				</table>
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td style="height: 30px; font-size: 1px;">&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>

	







