<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<td>&nbsp;</td>
		<td style="height: 30px; font-size: 1px; width: 600px;">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>
			<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
					<td style="height: 80px; vertical-align: middle; background-color: #002f5f;">
						<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/logo.png" border="0" style="margin: 0; padding: 0;" alt="ShipServ">
					</td>
					<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					<td style="height: 20px; font-size: 1px;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					<td style="height: 30px; font-size: 1px;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
				</tr>
				<tr>
					<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;" colspan="3">
						Dear ShipServ User,
					</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					<td style="height: 15px; font-size: 1px;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
				</tr>
				<tr>
					<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;" colspan="3">

						Your request to join company member account "<?php echo strip_tags($this->data['company']['name']); ?>" on ShipServ has been approved. 
					</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					<td style="height: 50px; font-size: 1px;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" style="background: #E7F8FD;">
						<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
								<td style="font-size: 1px; height: 30px;">&nbsp;</td>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
							</tr>
							<tr>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
								<td>
									<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
										<tr>
											<td style="font-size: 1px; width: 44px; vertical-align: top;">
												<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/info-grey.png" alt="info">
											</td>
											<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;">
												<strong>About Company Member Accounts</strong><br>
												As a member of this company account you will be able to <br>
												submit reviews, post responses and access company specific data.
											</td>
										</tr>
									</table>
								</td>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
							</tr>
							<tr>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
								<td style="font-size: 1px; height: 30px;">&nbsp;</td>
								<td style="font-size: 1px; width: 20px;">&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
					<td style="height: 40px; font-size: 1px; border-bottom: 1px solid #BECBD7;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					<td style="height: 20px; font-size: 1px;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px;">&nbsp;</td>
				</tr>
				<tr>
					<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; text-align: center;" colspan="3">
						If you require assistance visit our <a href="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/support/" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #0070BB;">support page</a> or email: <a href="mailto: support@shipserv.com" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #0070BB;">support@shipserv.com</a>
					</td>
				</tr>
				<tr>
					<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
					<td style="height: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">
						&nbsp;
					</td>
					<td style="width: 20px; font-size: 1px; border-bottom: 1px solid #BECBD7;">&nbsp;</td>
				</tr>
			</table>
		</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td style="height: 30px; font-size: 1px;">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>

