<?php echo nl2br($this->text)?>
<br/><br/>
Dear Supplier,<br/><br/>

<?php echo $this->companyInfo["name"];?> is inviting you to join ShipServ Pages, the world's
most widely used marine & offshore supplier directory.<br/><br/>

Pages is a an online service which helps suppliers like you to win new
business from the maritime purchasing community. In fact in 2010 alone,
$3.6bn in goods was sourced and traded via ShipServ.<br/><br/>

Industry Associations, Trade bodies and other memberships also use Pages
to promote their approved members. <?php echo $this->companyInfo["name"];?> would like to add
you to their Pages network in this capacity.<br/><br/>

Signing up to ShipServ Pages is quick and simple. Follow this link now to
set up a free listing and join the <?php echo $this->companyInfo["name"];?> approved members list<br/><br/>

<a href="<?php echo $this->link;?>"><?php echo $this->link;?></a>


