<?php
$endorseeInfo = $this->reviewRequest->getEndorseeInfo();
?>
<html>
	<body style="background-color: #F0F0F0; font-size: 11px; font-family: Arial, Helvetica, sans-serif">
		<div style="padding:20px">
		<table width="554" cellpadding="0" cellspacing="0" border="0" style="font-size: 11px; font-family: Arial, Helvetica, sans-serif">
			<tr>
				<td><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/shipserv_pages_logotop.gif" width="554" height="56" border="0" alt="ShipServ Pages"/></td>
			</tr>
			<tr>
				<td style="padding: 10px 40px;font-size: 11px; font-family: Arial, Helvetica, sans-serif">
					<?php echo nl2br($this->reviewRequest->text);?>
				</td>
			</tr>
			<tr><td style="font-size:0"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/top_whitebox.gif" width="554" height="17" border="0" alt=""/></td></tr>
			<tr>
				<td>
					<table width="554" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
						<tr>
							<td width="14" style="font-size:0"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/left_whitebox.gif" width="14" height="151" border="0" alt=""/></td>
							<td align="center">
								<table width="526" cellpadding="20" cellspacing="0" border="0" bgcolor="#FFFFFF">
									<tr>
										<td style="font:bold 18px Arial">
											Please indicate your overall impression by clicking on one of the following options:
										</td>
									</tr>
								</table>
								<table width="526" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
									<tr>
										<td align="center"><div style="padding:0 0 10px 0;"><a href="<?php echo $this->data["links"]["positive"]?>"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/button_positive.gif" border="0" alt="POSITIVE"/></a></div></td>
										<td align="center"><div style="padding:0 0 10px 0;"><a href="<?php echo $this->data["links"]["neutral"]?>"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/button_neutral.gif" border="0" alt="NEUTRAL"/></a></div></td>
										<td align="center"><div style="padding:0 0 10px 0;"><a href="<?php echo $this->data["links"]["negative"]?>"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/button_negative.gif" border="0" alt="NEGATIVE"/></a></div></td>

									</tr>
								</table>
							</td>
							<td width="14" style="font-size:0"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/right_whitebox.gif" width="14" height="151" border="0" alt=""/></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td style="font-size:0" height="17"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/bottom_whitebox.gif" width="554" height="17" border="0" alt=""/></td>
			</tr>
			<tr>
				<td height="70" valign="middle" align="center">
					<a href="<?php echo $this->data["ignoreLink"]?>"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/ineverused_button.gif" border="0" width="499" height="46" alt="I have never traded with this supplier"/></a>
				</td>
			</tr>
			<tr>
				<td style="padding: 10px 40px;font-size: 11px; font-family: Arial, Helvetica, sans-serif">
					You can also respond (and provide more detailed feedback) by clicking this link: <a href="<?php echo $this->data["links"]["neutral"]?>"><?php echo $this->data["links"]["neutral"]?></a>

					<br/><br/>Thanks in advance for helping both <?php echo $endorseeInfo["SPB_NAME"]?> and the ShipServ community.
				</td>
			</tr>
			<tr>
				<td height="17" valign="middle"><img src="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/images/layout_v2/endorsement/email/dotts_line.gif" width="554" height="7" border="0" alt=""/></td>
			</tr>
			<tr>
				<td style="padding: 10px 40px; font-size: 11px; font-family: Arial, Helvetica, sans-serif">
					To change notification settings or unsubscribe from this email <a href="<?echo  Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$_SERVER['HTTP_HOST'];?>/profile/notifications">click here</a>
				</td>
			</tr>
		</table>
		</div>
	</body>
</html>


<table>
<tr>
</tr>
</table>

