<?
$green = "#338e02";
$grey = "#959ba3";
$red = "#f40921";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<title></title>
	<style media="all" type="text/css">
		td {
			font-family: Arial, Helvetica, sans-serif;
		}
	</style>
</head>
<body style="margin:0; padding:0; font-size: 12px; font-family: Arial, Helvetica, sans-serif; color: #2e3235; background-color: #f5f7fa;">
<div style="margin:0; padding:10px; font-size: 12px; font-family: Arial, Helvetica, sans-serif; color: #2e3235; background-color: #f5f7fa;">
	<h1 style="font-size: 18px; font-weight: bold; color: #008b00; text-align: center; margin:0; padding:20px 0;font-family: Arial, Helvetica, sans-serif !important;">Congratulations! You have just sent first Quote through ShipServ Match</h1>
	<table cellpadding="0" cellspacing="0" border="0" style="width: 635px; height: 1000px; padding:0; margin: 0 auto;font-size: 12px; font-family: Arial, Helvetica, sans-serif; color: #2e3235; ">
		<tbody>
			<tr>
				<td valign="top" style="width:320px; padding:0; margin:0;">
					<h2 style="display:block; margin: 0 5px 5px 0; padding: 15px; font-family: Arial, Helvetica, sans-serif !important; font-size: 16px; color: #2e3235 !important; font-weight: bold; background-color: #e9edf1;">Quote summary</h2>
					<table cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #d6dce4; margin: 0; padding: 12px; width: 312px;">
						<tbody>
							<tr>
								<td style="margin:0; padding:0 0 10px 0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">RFQ Ref.</td>
								<td style="font-family: Arial, Helvetica, sans-serif !important; font-size: 13px; font-weight: bold; margin:0; padding:0 0 10px 0;">UO793-22</td>
							</tr>
							<tr>
								<td style="margin:0; padding:0 0 10px 0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">Buyer name:</td>
								<td style="font-size: 13px; font-weight: bold; margin:0; padding:0 0 10px 0;">Golden Gate Ltd</td>
							</tr>
							<tr>
								<td style="margin:0; padding:0 0 10px 0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">Vessel name:</td>
								<td style="font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: bold; margin:0; padding:0 0 10px 0;">FSL Tokyo</td>
							</tr>
							<tr>
								<td style="margin:0; padding:0 0 10px 0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">Delivery time:</td>
								<td style="font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: bold; margin:0; padding:0 0 10px 0;">12 June 2012</td>
							</tr>
							<tr>
								<td style="margin:0; padding:0 0 10px 0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">Delivery port:</td>
								<td style="font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: bold; margin:0; padding:0 0 10px 0;">Copenhagen, DK</td>
							</tr>
							<tr>
								<td style="margin:0; padding:0; width: 100px;font-family: Arial, Helvetica, sans-serif !important;font-size: 13px; font-weight: normal;">Total value:</td>
								<td style="font-size: 13px; font-weight: bold; margin:0; padding:0;">$ 20 000</td>
							</tr>
						</tbody>
					</table>
					<h3 style="margin:0; padding: 20px 0 15px 0; font-family: Arial, Helvetica, sans-serif !important; font-size: 16px; font-weight: bold; color: #2e3235 !important">What is ShipServ Match?</h3>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">ShipServ Match is an innovative new service which gives suppliers the chance to win new business from buyers for which they were not at first considered. This PO proves it works as the original RFQ was 'powered by ShipServ Match.'</p>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">
						<strong>How does ShipServ Match work?</strong><br />
						When sending an RFQ a buyer indicates that they want ShipServ to find additional suppliers. We use innovative and sophisticated technology to find additional suppliers who are highly relevant - we call these Matches. From our TradeNet platform, we then send the RFQ to Matched suppliers and give them a chance to quote. You did this and yours was the winning Quote.
					</p>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">
						<strong>How do I get more Matches?</strong><br />
						We have millions of RFQs per year through TradeNet and, from now, we'll be selecting a number of these suitable for Matching. 
						<strong><span style="color: red;">There are some things you need to do to increase the number of Match RFQs we send you - please see the rest of this email.</span></strong>
					</p>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">
						<strong>How do you choose the suppliers to Match?</strong><br />
						Finding excellent Matches is key and we have developed, and continue to refine, new technology for this. You can help us by ensuring your Premium Profile is very well completed - see box to the right. ShipServ Match is only available to Premium Listers.
					</p>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">
						<strong>Will this cost me?</strong><br />
						At the moment, the Match campaigns are free to suppliers (and buyers). We do plan on charging suppliers for this service in the future but the charge will be directly related to winning business you otherwise would not have been considered for.
					</p>
					<p style="font-family: Arial, Helvetica, sans-serif !important;margin: 0 0 15px 0; padding:0 5px 0 0; line-height: 1.5;">
						<strong>What to do next?</strong><br />
						To increase your chance of getting further RFQs through Match you need to click the Start campaign button to the right.
					</p>
				</td>
				<td valign="top" style="padding:0; margin:0;">
					<table cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #d6dce4; margin: 0; padding: 0; width: 315px;">
						<tbody>
							<tr>
								<td style="background-color: #fff; border-bottom: 1px solid #d6dce4; padding: 12px 5px 0 12px;">
									<h2 style="font-family: Arial, Helvetica, sans-serif !important;display:block; margin: 3px 0 5px 0; padding: 0; font-size: 16px; font-weight: bold; color: #2E3235 !important">If you want to receive more RFQs</h2>
									<p style="margin: 0 0 5px 0; padding:0; line-height: 1.2; font-size: 11px;">
										A key part of how we find excellent Matches is the information you have added to your Company Profile in ShipServ Pages. <strong>It's vital this information is as complete as possible. This information is also presented to buyer (see below) and help him decide whether to accept your quote.</strong>
									</p>
									<h3 style="font-family: Arial, Helvetica, sans-serif !important;display:block; margin: 0 0 5px 0; padding: 0; font-size: 14px; font-weight: bold; color: #2E3235 !important">Your Profile Complete Score</h3>
									<p style="float: right; color: <?php echo $red;?>; font-size: 15px; font-weight: bold; font-family: Arial, Helvetica, sans-serif !important;padding:0; margin:0;">30%</p>
									<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/warning.jpg" alt="" border="0" style="float: right;margin: 0;padding:0; padding-right: 5px;">
									<div style="width: 230px; height: 12px; margin:0; padding:0; border: 1px solid #c2c2c2;position: relative;">
										<div style="width: 30%; height:12px; margin:0; padding:0; float: left; top:0; left:0; background-color: <?php echo $red;?>"><img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/ind_red.jpg" alt="" width="100%" height="12" style="width: 100%; height: 12px; float: left;" /></div>
									</div>
									<table cellpadding="0" cellspacing="0" style="margin:0; padding:0; width: 232px; height: 4px;">
										<tr>
											<td style="margin:0; padding:0;width: 22px; border-left: 1px solid #c2c2c2;border-right: 1px solid #c2c2c2;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2; font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 22px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
											<td style="margin:0; padding:0;width: 23px; border-left: 0;border-right: 1px solid #c2c2c2;font-size: 1px;line-height: 4px;">&nbsp;</td>
										</tr>
									</table>
									<div style="width: 295px; margin: 2px 0 0 0; padding:0; height: 21px;">
										<div style="float: left; margin-left: -3px; font-size: 7.5px; color:#525c64;">0%</div>
										<div style="float: left;margin-left: 102px; font-size: 7.5px; color:#525c64;">50%</div>
										<div style="float: left;margin-left: 99px; font-size: 7.5px; color:#525c64;">100%</div>
									</div>
									<div style="margin:0; padding:0;">
										<a href="" style="font-family: Arial, Helvetica, sans-serif !important;display: block; background-color: #13b5ea; color: #fff; margin: 0 5px 10px 0; padding: 5px 10px; font-size: 11px; font-weight: bold; text-decoration: none; width: 145px; text-align: center; float: left;">Update company profile &gt;</a>
										<a href="" style="display: block; background-color: #13b5ea; color: #fff; margin: 0 5px 10px 0; padding: 5px 10px; font-size: 11px; font-weight: bold; text-decoration: none; width: 99px; text-align: center; float: right; margin-right: 10px;">Completion tips &gt;</a>
									</div>
									<h3 style="font-family: Arial, Helvetica, sans-serif !important;display:block; margin: 0; line-height: 3;padding: 0; font-size: 14px; font-weight: bold; clear: both; color: #2E3235 !important;" >This is what the buyer sees:</h3>
								</td>
							</tr>
							<tr>
								<td style="background-color: #e1f3fa; border-bottom: 1px solid #d6dce4; padding: 12px;"><a href="" style="margin:0; padding:0;color: #00386e;font-size: 11px; font-weight: bold; text-decoration: none;font-family: Arial, Helvetica, sans-serif !important;">HMS Hanseatic Marine Services GmbH & Co. KG<br /><span style="color: #13b5ea;">(Expert Supplier)</span></a></td>
							</tr>
							<tr>
								<td style="background-color: #e1f3fa; padding: 12px 3px 12px 3px;">
									<table width="310" cellpadding="0" cellspacing="0">
										<tbody>
											<tr>
												<td style="width: 75px; border-right: 2px solid #71cae8; height: 300px;">
													<span style="display: block; float: right;width: 10px; height: 2px; background-color: #71cae8; font-size: 2px; line-height: 2px; margin-top: 26px;"></span>
													<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/trade_rank_icon.jpg" alt="Trade Rank" style="margin-left: 12px;" border="0" />
													<div style="text-align: center;">
														<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rank_full_star.jpg" alt="" border="0" style="float: left;" />
														<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rank_full_star.jpg" alt="" border="0" style="float: left;" />
														<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rank_full_star.jpg" alt="" border="0" style="float: left;" />
														<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rank_half_star.jpg" alt="" border="0" style="float: left;" />
														<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rank_star.jpg" alt="" border="0" style="float: left;" />
													</div>
												</td>
												<td style="margin:0; padding: 0 0 0 5px;" valign="top">
													<h4 style="margin: 0 0 3px 0; margin-bottom: 3px;padding: 0; font-size: 11px; font-weight: bold; color: #000 !important;">Reviews:</h4>
													<table style="margin: 0; padding: 5px 0 5px 0; background-color: #fff; border:1px solid #d6dce4;" width="100%">
														<tbody>
															<tr>
																<td style="width: 118px; border-right: 1px dotted #000; margin:0; padding:0 5px 0 0;">
																	<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/pos_rev.jpg" alt="" border="0" style="float: left;">
																	<p style="color: #008b00; font-size: 10px; font-weight: bold; margin: 3px 0 8px 0; padding:0; padding-left: 24px;font-family: Arial, Helvetica, sans-serif !important;">4 positive reviews</p>
																	<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/neu_rev.jpg" alt="" border="0" style="float: left;">
																	<p style="color: #939ba1; font-size: 10px; font-weight: bold;margin: 10px 0 8px 0; padding:0;padding-left: 24px;font-family: Arial, Helvetica, sans-serif !important;">0 neutral reviews</p>
																	<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/neg_rev.jpg" alt="" border="0" style="float: left;">
																	<p style="color: #e81e24; font-size: 10px; font-weight: bold;margin: 10px 0 8px 0; padding:0;padding-left: 24px;font-family: Arial, Helvetica, sans-serif !important;">0 negative reviews</p>
																</td>
																<td style="margin:0; padding:0 0 0 5px;">
																	<p style="margin:0; padding:0; font-size: 10px; font-weight: normal; color: #000; margin-bottom:0;font-family: Arial, Helvetica, sans-serif !important;">
																		Items as described:
																	</p>
																	<div style="margin:0; padding:0;height: 12px; max-height: 12px; margin-bottom: 4px;">
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_half_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_star.jpg" alt="" border="0" style="float: left;" />
																	</div>
																	<p style="margin:0; padding:0; font-size: 10px; font-weight: normal; color: #000; clear: both;margin-bottom:0;font-family: Arial, Helvetica, sans-serif !important;">
																		On-time delivery:
																	</p>
																	<div style="margin:0; padding:0;height: 12px; max-height: 12px; margin-bottom: 4px;">
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_half_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_star.jpg" alt="" border="0" style="float: left;" />
																	</div>
																	<p style="margin:0; padding:0; font-size: 10px; font-weight: normal; color: #000; clear: both;margin-bottom:0;font-family: Arial, Helvetica, sans-serif !important;">
																		Customer service:
																	</p>
																	<div style="margin:0; padding:0; height: 12px;">
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_full_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_half_star.jpg" alt="" border="0" style="float: left;" />
																		<img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/new/rate_star.jpg" alt="" border="0" style="float: left;" />
																	</div>
																</td>
															</tr>
														</tbody>
													</table>
													<h4 style="margin: 3px 0 3px 0; margin-top: 3px; margin-bottom:3px; padding: 0; font-size: 11px; font-weight: bold; color: #000 !important;font-family: Arial, Helvetica, sans-serif !important;">Trading Performance:</h4>
													<table style="margin: 0; padding: 5px; background-color: #fff; border:1px solid #d6dce4;" width="100%">
														<tbody>
															<tr>
																<td style="margin:0; padding:0;">
																	<p style="font-size: 10px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		<strong><span style="color:#e52929;">35 buyers</span> (with <span style="color:#e52929;">861 transactions</span>) have traded with this Supplier in last 2 years on TradeNet including:</strong>
																	</p>
																	<p style="font-size: 10px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		Hoegh LNG Fleet Management AS, Prestige Cruise Holdings, Inc., MSC Ship Management Ltd, Green Shipping AS, Anders Utkilens Rederi A/S.
																	</p>
																	<a href="" style="color: #005aad; font-size: 11px; font-weight: bold; margin: 0; padding:0; text-decoration: none;font-family: Arial, Helvetica, sans-serif !important;">View all buyers</a>
																</td>
															</tr>
														</tbody>
													</table>
													<h4 style="margin: 3px 0 3px 0; margin-top: 3px; margin-bottom: 3px;padding: 0; font-size: 11px; font-weight: bold; color: #000 !important;font-family: Arial, Helvetica, sans-serif !important;">Verification System:</h4>
													<table style="margin: 0; padding: 5px; background-color: #fff; border:1px solid #d6dce4;" width="100%">
														<tbody>
															<tr>
																<td style="margin:0; padding:0;">
																	<p style="font-size: 11px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		<strong>Verified as Agent for:</strong>
																	</p>
																	<p style="font-size: 10px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		<strong>Hanseatic Marine Services (HMS)</strong> (Authorised Agent)
																	</p>
																	<p style="font-size: 11px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		<strong>Unverified as Agent for:</strong>
																	</p>
																	<p style="font-size: 10px; color: #3b3f42; margin: 0 0 4px 0;font-family: Arial, Helvetica, sans-serif !important;">
																		<strong>Herborner</strong> (Authorised Agent), <strong>Rational</strong> (Authorised Agent), <strong>Unitor</strong> (Authorised Agent)
																	</p>
																</td>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="2" style="margin: 0; padding: 0;">
					<table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-size: 11px; border-top: 1px dotted #d7dade; padding-top: 10px; padding-bottom: 10px;">
						<tr>
							<td style="padding-right:4px;font-family: Arial, Helvetica, sans-serif !important;">ShipServ &copy; 2014<span style="color: #d7dade;">&nbsp;&nbsp;|&nbsp;&nbsp;</span><a href="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/legal-notes/terms-and-conditions/" style="color: #00386e; text-decoration: none;font-family: Arial, Helvetica, sans-serif !important;">Terms &amp; Conditions</a><span style="color: #d7dade;">&nbsp;&nbsp;|&nbsp;&nbsp;</span><a href="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/privacy-policy/" style="color: #00386e; text-decoration: none;font-family: Arial, Helvetica, sans-serif !important;">Privacy Policy</a></td>
							<td style="text-align:right;"><img src="<?php echo Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->hostname; ?>/images/match/email/logo_foot.png" alt="ShipServ"></td>
						</tr>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</div>
</body>
</html>
