<?php
$this->CDNLink()->appendStylesheet('/css/endorsements.css');
$this->CDNLink()->appendStylesheet('/css/textboxlist.css');
$this->CDNLink()->appendStylesheet('/css/supplier/supplier.css');
$this->CDNLink()->appendStylesheet('/css/supplier/dt.css');

$this->headTitle('DanishTools, Drills & Counter sinks, Standard & Pro Quality for High Performance', 'SET');
$this->headMeta()->appendName('description', 'DANISHTOOLS.com - Specialist High Quality Cutting Tools, Select from a wide range of Drills & Counter Sinks, Standard & Pro Quality for High Performance');

$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
                     array('name' => 'Search Results',
						   'url'  => $this->backToSearch()->getUrl()),
					 array('name' => 'Supplier Profile',
						   'url'  => '/supplier/profile/'));
?>
<div id="main_content_area">
	<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
	<div class="content_wide">
		<div class="content_wide_header">

			<h1 class="profile">DANISHTOOLS.com</h1>
			
			<h2>Copenhagen, Denmark</h2>
			
			<a href="/enquiry/index/clearBasket/1/tnid/<?=$this->tnid;?>" rel="nofollow" class="send_enquiry_button"></a>
			
		</div>
		<div class="content_wide_nav">
			<ul>
				<li class="off" id="profile_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>" class="profile_toggle">Profile</a>
				</li>
				<li class="off" id="contact_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#contact_box" class="contact_toggle">Contact</a>
				</li>
				<li class="off" id="reviews_toggle">
					<a href="/reviews/supplier/s/danishtools-com-<?=$this->tnid;?>#reviews" class="reviews_toggle" id="reviewsToggleText">Reviews</a>
				</li>
				<li class="off" id="catalogue_toggle">
					<a class="catalogue_toggle" href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#catalogue">Catalogue</a>
				</li>
			</ul>
		</div>
		<div class="content_wide_body">
			<div class="cont">
				<div class="top"></div>
				<div class="image">
					<img src="/img/supplier/dt/hand-machine-taps.png" alt="DanishTools Drills & Counter Sinks" title="DanishTools Drills & Counter Sinks" />
				</div>
				<div class="textContainer">
					<div class="left">
						<h1>DRILLS / COUNTER SINKS</h1>
						<p>
							<strong>CHOOSE THE RIGHT TOOL</strong> <br />
							Standard quality for general use  <br />
							PRO quality for high performance <br />
						</p>
					</div>
					<div class="right">
						<p class="bm">
							<strong><i>HOW TO ORDER</i></strong><br />
							1937 PRO Normal 4-20x2
						</p>
						<p class="bm">
							<strong>TO ORDER - PLEASE STATE:</strong><br />
							Type No., Quality, Size
						</p>
					</div>
					<h2>DRILLS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom: 15px;">
						<thead>
							<tr>
								<th width="131">Item</th>
								<th width="61">Type No.</th>
								<th width="71">Quality</th>
								<th width="103">Size</th>
								<th width="182">Range</th>
								<th>Suitable for</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td rowspan="2">DIN 338 HSS Ground</td>
								<td>1339</td>
								<td>Standard</td>
								<td>Normal</td>
								<td>1,0-13,0 X 0,1</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>1338</td>
								<td>PRO</td>
								<td>Normal</td>
								<td>
									0,3-13,0 X 0,1<br/>
									13,5-20,0 X 0,5
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td rowspan="2">DIN 338 HSSCO Ground</td>
								<td>7339</td>
								<td>Standard</td>
								<td>Normal</td>
								<td>1,0-13,0 X 0,1</td>
								<td>Stainless Steel</td>
							</tr>
							<tr>
								<td>7338</td>
								<td>PRO</td>
								<td>Normal</td>
								<td>
									1,0-13,0 x 0,1<br />
									13,5-16,0 X 0,5
								</td>
								<td>Stainless Steel</td>
							</tr>
							<tr>
								<td rowspan="2">
									DIN 338 HSS<br />
									Reduced shank
								</td>
								<td>0339N</td>
								<td>Standard</td>
								<td>Reduced shank</td>
								<td>10,5 - 20,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>1338N</td>
								<td>PRO</td>
								<td>Reduced shank</td>
								<td>10,5 - 25,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 338 HSS TCT tip</td>
								<td>6338</td>
								<td>Standard</td>
								<td>Normal</td>
								<td>3,0-13,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 338 HSS TCT</td>
								<td>6338T</td>
								<td>PRO</td>
								<td>Normal</td>
								<td>3,0-13,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 1897 HSS Ground</td>
								<td>1897</td>
								<td>PRO</td>
								<td>Short</td>
								<td>3,0 - 10,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Double ended Ground</td>
								<td>2897</td>
								<td>PRO</td>
								<td>Double ended</td>
								<td>2,5-6,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td rowspan="2">DIN 340 HSS Ground</td>
								<td>1341</td>
								<td>Standard</td>
								<td>Long</td>
								<td>
									2,5-10,0 X 0,1<br />
									10,5-13,0 X 0,5
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>1340</td>
								<td>PRO</td>
								<td>Long</td>
								<td>
									2,5-10,0 X 0,1<br />
									10,5-13,0 X 0,5
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td rowspan="3">DIN 1869 HSS Ground</td>
								<td>1869-1</td>
								<td>PRO</td>
								<td>Extra long</td>
								<td>Serie I 2,5-13,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>1869-2</td>
								<td>PRO</td>
								<td>Extra long</td>
								<td>Serie II 3,0-13,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>1869-3</td>
								<td>PRO</td>
								<td>Extra long</td>
								<td>Serie III 3,5-13,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 345 HSS Rolled</td>
								<td>0349</td>
								<td>Standard</td>
								<td>Morse taper Shank</td>
								<td>
									10,5-40,0 X 0,5<br />
									41,0-60,0 X 0,5
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 345 HSS Ground</td>
								<td>1345</td>
								<td>PRO</td>
								<td>Morse taper Shank</td>
								<td>10,5-30,0 X 0,5</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>
									Center drill DIN 333<br />
									A HSS
								</td>
								<td>0333</td>
								<td>PRO</td>
								<td>Normal</td>
								<td>2,5-6,3</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Sheet drill HSS</td>
								<td>1935</td>
								<td>PRO</td>
								<td>Normal</td>
								<td class="nopadding">
									<table width="100%" cellpadding="0" cellspacing="0" border="0" class="noborder">
										<tr>
											<td width="33%" class="cellborder">3-14</td>
											<td width="33%" class="cellborder">4-20</td>
											<td>16-30,5</td>
										</tr>
									</table>
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Sheet drill HSSCO</td>
								<td>1935T</td>
								<td>PRO</td>
								<td>Normal</td>
								<td class="nopadding">
									<table width="100%" cellpadding="0" cellspacing="0" border="0" class="noborder">
										<tr>
											<td width="33%" class="cellborder">3-14</td>
											<td width="33%" class="cellborder">4-20</td>
											<td>16-30,5</td>
										</tr>
									</table>
								</td>
								<td>Stainless Steel</td>
							</tr>
							<tr>
								<td>Step drill HSS</td>
								<td>1938</td>
								<td>PRO</td>
								<td>Normal</td>
								<td class="nopadding">
									<table width="100%" cellpadding="0" cellspacing="0" border="0" class="noborder">
										<tr>
											<td width="33%" class="cellborder">4-12x1</td>
											<td width="33%" class="cellborder">4-20x2</td>
											<td>4-30x2</td>
										</tr>
									</table>
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Step drill HSS-TiN</td>
								<td>1938T</td>
								<td>PRO</td>
								<td>Normal</td>
								<td class="nopadding">
									<table width="100%" cellpadding="0" cellspacing="0" border="0" class="noborder">
										<tr>
											<td width="33%" class="cellborder">4-12x1</td>
											<td width="33%" class="cellborder">4-20x2</td>
											<td>4-30x2</td>
										</tr>
									</table>
								</td>
								<td>Stainless Steel</td>
							</tr>
							<tr>
								<td colspan="6" class="center bold italic">
									How to order: 1937 PRO NORMAL 4-20x2&nbsp;&nbsp;&nbsp;&nbsp;Comply to: Step drill HSS PRO NORMAL 4-20x2
								</td>
							</tr>
						</tbody>
					</table>
					<h2>COUNTER SINKS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th width="131">Item</th>
								<th width="61">Type No.</th>
								<th width="71">Quality</th>
								<th width="103">Size</th>
								<th width="182">Range</th>
								<th>Suitable for</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>DIN 335C 90&deg; HSS</td>
								<td>1930</td>
								<td>PRO</td>
								<td>Straight shank</td>
								<td>5,0-31,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 335D 90&deg; HSS</td>
								<td>1931</td>
								<td>PRO</td>
								<td>Morse taper shank</td>
								<td>16,0-50,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>DIN 334C 60&deg;</td>
								<td>1920</td>
								<td>PRO</td>
								<td>Straight shank</td>
								<td>6,3-25,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Counter sink 120&deg;</td>
								<td>1912</td>
								<td>PRO</td>
								<td>Straight shank</td>
								<td>6,3-25,0</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Taper countersink 90&deg;</td>
								<td>8374</td>
								<td>PRO</td>
								<td>DIN8374</td>
								<td>M3-M10</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Taper countersink 180&deg;</td>
								<td>8376</td>
								<td>PRO</td>
								<td>DIN8376</td>
								<td>M3-M10</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>Taper countersink 90&deg;</td>
								<td>8378</td>
								<td>PRO</td>
								<td>DIN8378</td>
								<td>M3-M12</td>
								<td>Low alloy steel</td>
							</tr>
						</tbody>
					</table>
					<div class="clear"></div>
				</div>
				<div class="logo">
					<img src="/img/supplier/dt/dn-logo.png" border="0" alt="Danishtools Thread Cutting Tools since 1898" title="Danishtools Thread Cutting Tools since 1898" />
					<div>Danishtools.com<br />
					Info@danishtools.com<br />
					Copenhagen, Denmark<br />
					Tel: +45 7027 5727 Fax: +45 3173 2639</div>
				</div>
			</div>
		</div>
		<div class="content_wide_footer_shadow"></div>
	</div>
	<div class="zone">
		<div style="padding-top: 20px;"></div>
		<?php echo $this->partial('general-google-ads.phtml'); ?>
	</div>
</div>