<?php
$this->CDNLink()->appendStylesheet('/css/endorsements.css');
$this->CDNLink()->appendStylesheet('/css/textboxlist.css');
$this->CDNLink()->appendStylesheet('/css/supplier/supplier.css');
$this->CDNLink()->appendStylesheet('/css/supplier/dt.css');

$this->headTitle('DanishTools, Buy Hand & Machine Taps, Marine Hand Tools, HSS Standard, HSS Pro, & PM Pro', 'SET');
$this->headMeta()->appendName('description', 'DANISHTOOLS.com - Specialist in High Quality Cutting Tools, Select from a wide range of Hand & Machine Taps, HSS Standard, HSS Pro, PM Pro & HSSE Standard ');

$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
                     array('name' => 'Search Results',
						   'url'  => $this->backToSearch()->getUrl()),
					 array('name' => 'Supplier Profile',
						   'url'  => '/supplier/profile/'));
?>
<div id="main_content_area">
	<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
	<div class="content_wide">
		<div class="content_wide_header">
			
			<h1 class="profile">DANISHTOOLS.com</h1>
			
			<h2>Copenhagen, Denmark</h2>
			
			<a href="/enquiry/index/clearBasket/1/tnid/<?=$this->tnid;?>" rel="nofollow" class="send_enquiry_button"></a>
			
		</div>
		<div class="content_wide_nav">
			<ul>
				<li class="off" id="profile_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>" class="profile_toggle">Profile</a>
				</li>
				<li class="off" id="contact_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#contact_box" class="contact_toggle">Contact</a>
				</li>
				<li class="off" id="reviews_toggle">
					<a href="/reviews/supplier/s/danishtools-com-<?=$this->tnid;?>#reviews" class="reviews_toggle" id="reviewsToggleText">Reviews</a>
				</li>
				<li class="off" id="catalogue_toggle">
					<a class="catalogue_toggle" href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#catalogue">Catalogue</a>
				</li>
			</ul>
		</div>
		<div class="content_wide_body">
			<div class="cont">
				<div class="top"></div>
				<div class="image">
					<img src="/img/supplier/dt/hand-machine-taps.png" alt="DanishTools Hand Taps & Machine Taps" title="DanishTools Hand Taps & Machine Taps" />
				</div>
				<div class="textContainer">
					<div class="left">
						<h1>TAPS</h1>
						<p>
							<strong>CHOOSE THE RIGHT TOOL</strong> <br />
							Standard quality for general use  <br />
							PRO quality for high performance <br />
						</p>
						<p>
							<strong>
								WE OFFER A RANGE OF ODD SIZES NOT MENTIONED<br />
								ANY TYPE OR SIZE NOT MENTIONED - PLEASE SEND REQUEST 
							</strong>
						</p>
					</div>
					<div class="right">
						<p class="bm">
							<strong><i>HOW TO ORDER</i></strong><br />
							0110 - 3 M52
						</p>
						<p class="bm">
							<strong>TO ORDER - PLEASE STATE:</strong><br />
							Type No., Thread Type, Size
						</p>
						<p>
							<strong>FOR REQUESTS  -  PLEASE STATE:</strong><br />
							Tap type, Thread Type, Size, Use for
						</p>
					</div>
					<h2>HAND TAPS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th width="172">&nbsp;</th>
								<th width="117">
									Type No. Sets
								</th>
								<th width="107">
									Type No. Sets - Left hand
								</th>
								<th width="150">
									<table class="noborder" cellpadding="0" cellspacing="0" border="0" width="100%">
										<tr>
											<td colspan="3" class="bold">
												Add Type no.
											</td>
										</tr>
										<tr>
											<td width="33%" class="bold">
												Taper
											</td>
											<td width="33%" class="bold">
												Second
											</td>
											<td class="bold">
												Bottom
											</td>
										</tr>
									</table>
								</th>
								<th>
									Suitable for:
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									HSS Standard
								</td>
								<td>0100 -</td>
								<td>0109 -</td>
								<td>
									<table class="noborder" cellpadding="0" cellspacing="0" border="0" width="100%">
										<tr>
											<td width="33%">
												1
											</td>
											<td width="33%">
												2
											</td>
											<td>
												3
											</td>
										</tr>
									</table>
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>
									HSS PRO
								</td>
								<td>0110 -</td>
								<td>0119 -</td>
								<td>
									<table class="noborder" cellpadding="0" cellspacing="0" border="0" width="100%">
										<tr>
											<td width="33%">
												1
											</td>
											<td width="33%">
												2
											</td>
											<td>
												3
											</td>
										</tr>
									</table>
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>
									HSS PRO
								</td>
								<td>0114 -</td>
								<td></td>
								<td>
									<table class="noborder" cellpadding="0" cellspacing="0" border="0" width="100%">
										<tr>
											<td width="33%">
												1
											</td>
											<td width="33%">
												2
											</td>
											<td>
												3
											</td>
										</tr>
									</table>
								</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td colspan="5" class="center bold italic">
									How to order: 0110-3 M52&nbsp;&nbsp;&nbsp;&nbsp;Comply to: Hand tap HSS PRO BOTTOM M52
								</td>
							</tr>
						</tbody>
					</table>
					<table class="noborder margin left" cellpadding="0" cellspacing="0" border="0" width="100%">
						<tr>
							<td width="144">Stock Available:</td>
							<td width="194">M1- M52</td>
							<td>MF 2- MF 52</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UNC 4-40 - UNC 2"</td>
							<td>UNF 4-48 - UNF 1&frac12;"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UN 1 1/8" x 8 - UN 2&frac12;" x 8</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>NPT 1/8" - NPT 2"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSW 1/8" - BSW 2"</td>
							<td>BSF 1/8" - BSF 1"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSP 1/16" - BSP 3"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td>Also available:</td>
							<td colspan="2">UNEF, NPTF, NPSM, NPSF, BSPT, BSPP, BA, PG, TR, DIN 477</td>
						</tr>
					</table>
					<h2>MACHINE TAPS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th>&nbsp;</th>
								<th colspan="2">
									Spiral flute<br />
									Type No.
								</th>
								<th colspan="2">
									Gun Nose<br />
									Type No.
								</th>
								<th>
									Suitable for
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td width="94">HSS Standard</td>
								<td width="91">0151</td>
								<td rowspan="6" width="137" class="nopadding"><img src="/img/supplier/dt/hand-bottom-hole.png" border="0"/></td>
								<td width="83">0171</td>
								<td rowspan="6" width="137" class="nopadding"><img src="/img/supplier/dt/hand-gt-hole.png" border="0"/></td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSSE Standard</td>
								<td>0150</td>
								<td>0170</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSSE PRO</td>
								<td>0152</td>
								<td>0172</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>PM PRO</td>
								<td>0155-22</td>
								<td>0175-22</td>
								<td>Stainless steel</td>
							</tr>
							<tr>
								<td>PM PRO</td>
								<td>0155-23</td>
								<td>0175-23</td>
								<td>High Alloy steel</td>
							</tr>
							<tr>
								<td>PM PRO</td>
								<td>0155-31</td>
								<td>0175-31</td>
								<td>Aluminum</td>
							</tr>
							<tr>
								<td colspan="6" class="bold italic">
									How to order: 0150 UNC 4-40&nbsp;&nbsp;&nbsp;&nbsp;Comply to: Machine tap spiral flute HSS Standard UNC 4-40
								</td>
							</tr>
						</tbody>
					</table>
					<table class="noborder margin left" cellpadding="0" cellspacing="0" border="0" width="100%">
						<tr>
							<td width="144">Stock Available:</td>
							<td width="194">M 2 - M45</td>
							<td>MF 2 - MF42</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UNC 4 - 40 - UNC 2"</td>
							<td>UNF 5 - 44 - UNF 1&frac12;"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UN 1 1/8" x 8 - UN 2&frac12;" x 8</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>NPT 1/8" - NPT 2"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSW 1/8" - BSW 2"</td>
							<td>BSF 1/8" - BSF 1"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSP 1/16" - BSP 3"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td>Also available:</td>
							<td colspan="2">UNEF, NPTF, NPT, NPSM, NPSF, BSPT, BSPP, BA, PG, TR, DIN 477</td>
						</tr>
					</table>
					<div class="clear"></div>
				</div>
				<div class="logo">
					<img src="/img/supplier/dt/dn-logo.png" border="0" alt="Danishtools Thread Cutting Tools since 1898" title="Danishtools Thread Cutting Tools since 1898" />
					<div>Danishtools.com<br />
					Info@danishtools.com<br />
					Copenhagen, Denmark<br />
					Tel: +45 7027 5727 Fax: +45 3173 2639</div>
				</div>
			</div>
		</div>
		<div class="content_wide_footer_shadow"></div>
	</div>
	<div class="zone">
		<div style="padding-top: 20px;"></div>
		<?php echo $this->partial('general-google-ads.phtml'); ?>
	</div>
</div>