<?php
$this->CDNLink()->appendStylesheet('/css/endorsements.css');
$this->CDNLink()->appendStylesheet('/css/textboxlist.css');
$this->CDNLink()->appendStylesheet('/css/supplier/supplier.css');
$this->CDNLink()->appendStylesheet('/css/supplier/dt.css');

$this->headTitle('DanishTools, Hand & Machine Taps, Marine Hand Tools, HSS Standard, HSS Pro, & PM Pro', 'SET');
$this->headMeta()->appendName('description', 'DANISHTOOLS.com - Specialist High Quality Cutting Tools, Select from a wide range of Round Dies, Hexagon Nut Dies & Square Dies');

$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
                     array('name' => 'Search Results',
						   'url'  => $this->backToSearch()->getUrl()),
					 array('name' => 'Supplier Profile',
						   'url'  => '/supplier/profile/'));
?>
<div id="main_content_area">
	<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
	<div class="content_wide">
		<div class="content_wide_header">

			<h1 class="profile">DANISHTOOLS.com</h1>
			
			<h2>Copenhagen, Denmark</h2>
			
			<a href="/enquiry/index/clearBasket/1/tnid/<?=$this->tnid;?>" rel="nofollow" class="send_enquiry_button"></a>
			
		</div>
		<div class="content_wide_nav">
			<ul>
				<li class="off" id="profile_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>" class="profile_toggle">Profile</a>
				</li>
				<li class="off" id="contact_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#contact_box" class="contact_toggle">Contact</a>
				</li>
				<li class="off" id="reviews_toggle">
					<a href="/reviews/supplier/s/danishtools-com-<?=$this->tnid;?>#reviews" class="reviews_toggle" id="reviewsToggleText">Reviews</a>
				</li>
				<li class="off" id="catalogue_toggle">
					<a class="catalogue_toggle" href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#catalogue">Catalogue</a>
				</li>
			</ul>
		</div>
		<div class="content_wide_body">
			<div class="cont">
				<div class="top"></div>
				<div class="image">
					<img src="/img/supplier/dt/hand-machine-taps.png" alt="DanishTools Round, Hexagon Nut & Square Dies" title="DanishTools Round, Hexagon Nut & Square Dies" />
				</div>
				<div class="textContainer">
					<div class="left">
						<h1>DIES</h1>
						<p>
							<strong>CHOOSE THE RIGHT TOOL</strong> <br />
							Standard quality for general use  <br />
							PRO quality for high performance <br />
						</p>
						<p>
							<strong>
								WE OFFER A RANGE OF ODD SIZES NOT MENTIONED<br />
								ANY TYPE OR SIZE NOT MENTIONED - PLEASE SEND REQUEST 
							</strong>
						</p>
					</div>
					<div class="right">
						<p class="bm">
							<strong><i>HOW TO ORDER</i></strong><br />
							0884-22 UNC &frac14;"
						</p>
						<p class="bm">
							<strong>TO ORDER - PLEASE STATE:</strong><br />
							Type No., Thread Type, Size
						</p>
						<p>
							<strong>FOR REQUESTS  -  PLEASE STATE:</strong><br />
							Die type, Thread Type, Size, Use for
						</p>
					</div>
					<h2>ROUND DIES, DIE NUT (HEX) and SQUARE DIES</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th width="137">&nbsp;</th>
								<th width="137">&nbsp;</th>
								<th width="117">
									Type No.
								</th>
								<th width="158">
									Type No. Sets - Left hand
								</th>
								<th>
									Suitable for:
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td rowspan="4">Round Die</td>
								<td>HSS Standard</td>
								<td>0881</td>
								<td>&nbsp;</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSS PRO</td>
								<td>0880</td>
								<td>0889</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSS PRO Tol. 6G</td>
								<td>0888</td>
								<td>&nbsp;</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSSE PRO</td>
								<td>0884-22</td>
								<td>&nbsp;</td>
								<td>Stainless steel</td>
							</tr>
							<tr>
								<td rowspan="2">Die Nut (Hex)</td>
								<td>Standard</td>
								<td>0861</td>
								<td>&nbsp;</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>PRO</td>
								<td>0860</td>
								<td>&nbsp;</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td rowspan="2">Square Die</td>
								<td>HSS Standard</td>
								<td>0810</td>
								<td>0819</td>
								<td>Low alloy steel</td>
							</tr>
							<tr>
								<td>HSSE Standard</td>
								<td>0820</td>
								<td>0829</td>
								<td>Stainless steel</td>
							</tr>
							<tr>
								<td colspan="5" class="center bold italic">
									How to order: 0884-22 UNC &frac14;"&nbsp;&nbsp;&nbsp;&nbsp;Comply to: Round die HSSE PRO UNC &frac14;" for Stainless Steel
								</td>
							</tr>
						</tbody>
					</table>
					<table class="noborder margin left" cellpadding="0" cellspacing="0" border="0" width="100%">
						<tr>
							<td width="144">Stock Available:</td>
							<td width="194">M1 - M52</td>
							<td>MF 2 - MF 52</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UNC 4-40 - UNC 2"</td>
							<td>UNF 4-48 - UNF 1&frac12;"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UN 1 1/8" x 8 - UN 2&frac12;" x 8</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>NPT 1/8" - NPT 2"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSW 1/8" - BSW 2"</td>
							<td>BSF 1/8" - BSF 1"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSP 1/16" - BSP 3"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSP 1/8" - BSP 3"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSW 1/8" - BSW 1"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td>Also available:</td>
							<td colspan="2">UNEF, NPTF, NPSM, NPSF, BSPT, BSPP, BA, PG, TR, DIN 477</td>
						</tr>
					</table>
					<div class="clear"></div>
				</div>
				<div class="logo">
					<img src="/img/supplier/dt/dn-logo.png" border="0" alt="Danishtools Thread Cutting Tools since 1898" title="Danishtools Thread Cutting Tools since 1898" />
					<div>Danishtools.com<br />
					Info@danishtools.com<br />
					Copenhagen, Denmark<br />
					Tel: +45 7027 5727 Fax: +45 3173 2639</div>
				</div>
			</div>
		</div>
		<div class="content_wide_footer_shadow"></div>
	</div>
	<div class="zone">
		<div style="padding-top: 20px;"></div>
		<?php echo $this->partial('general-google-ads.phtml'); ?>
	</div>
</div>