<?php
$this->CDNLink()->appendStylesheet('/css/endorsements.css');
$this->CDNLink()->appendStylesheet('/css/textboxlist.css');
$this->CDNLink()->appendStylesheet('/css/supplier/supplier.css');
$this->CDNLink()->appendStylesheet('/css/supplier/dt.css');

$this->headTitle('DanishTools, Thread Gauges & Thread Repair Sets, Plug & Ring Gauge Pro', 'SET');
$this->headMeta()->appendName('description', 'DANISHTOOLS.com - Specialist High Quality Cutting Tools, Select from a wide range of Thread Gauge & Thread Repair Sets, Plug Gauges Pro & Ring Gauge Pro');

$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
                     array('name' => 'Search Results',
						   'url'  => $this->backToSearch()->getUrl()),
					 array('name' => 'Supplier Profile',
						   'url'  => '/supplier/profile/'));
?>
<div id="main_content_area">
	<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
	<div class="content_wide">
		<div class="content_wide_header">

			<h1 class="profile">DANISHTOOLS.com</h1>
			
			<h2>Copenhagen, Denmark</h2>
			
			<a href="/enquiry/index/clearBasket/1/tnid/<?=$this->tnid;?>" rel="nofollow" class="send_enquiry_button"></a>
			
		</div>
		<div class="content_wide_nav">
			<ul>
				<li class="off" id="profile_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>" class="profile_toggle">Profile</a>
				</li>
				<li class="off" id="contact_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#contact_box" class="contact_toggle">Contact</a>
				</li>
				<li class="off" id="reviews_toggle">
					<a href="/reviews/supplier/s/danishtools-com-<?=$this->tnid;?>#reviews" class="reviews_toggle" id="reviewsToggleText">Reviews</a>
				</li>
				<li class="off" id="catalogue_toggle">
					<a class="catalogue_toggle" href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#catalogue">Catalogue</a>
				</li>
			</ul>
		</div>
		<div class="content_wide_body">
			<div class="cont">
				<div class="top"></div>
				<div class="image">
					<img src="/img/supplier/dt/hand-machine-taps.png" alt="DanishTools Thread Gauges  & Repair Sets" title="DanishTools Thread Gauges  & Repair Sets" />
				</div>
				<div class="textContainer">
					<div class="left">
						<h1>THREAD GAUGES</h1>
						<h2>THREAD GAUGE<br/>THREAD REPAIR SET</h2>
					</div>
					<div class="right">
						<p class="bm">
							<strong><i>HOW TO ORDER</i></strong><br />
							0710 M2
						</p>
						<p class="bm">
							<strong>TO ORDER - PLEASE STATE:</strong><br />
							Type No., Thread Type, Size
						</p>
					</div>
					<div class="center">
						<strong>ANY TYPE OR SIZE NOT MENTIONED - PLEASE REQUEST</strong>
					</div>

					<table cellspacing="0" cellpadding="0" border="0" width="100%" class="noborder left">
						<tr>
							<td width="410">
								<h2>PLUG GAUGES PRO</h2>
								<table width="295" cellpadding="0" cellspacing="0" border="0" class="center nomargin">
									<thead>
										<tr>
											<th width="73">&nbsp;</th>
											<th width="85">Type No.</th>
											<th>Type No. Left hand</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Go</td>
											<td>0710</td>
											<td>0719</td>
										</tr>
										<tr>
											<td>NoGo</td>
											<td>0720</td>
											<td>0729</td>
										</tr>
										<tr>
											<td>Go/ NoGo</td>
											<td>0730</td>
											<td>0739</td>
										</tr>
									</tbody>
								</table>
							</td>
							<td>
								<h2>RING GAUGES PRO</h2>
								<table width="295" cellpadding="0" cellspacing="0" border="0" class="center nomargin">
									<thead>
										<tr>
											<th width="73">&nbsp;</th>
											<th width="85">Type No.</th>
											<th>Type No. Left hand</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Go</td>
											<td>0740</td>
											<td>0749</td>
										</tr>
										<tr>
											<td>NoGo</td>
											<td>0750</td>
											<td>0759</td>
										</tr>
										<tr>
											<td colspan="3" class="bold center italic">How to order: 0710 M2</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</table>
					<table class="noborder margin left" cellpadding="0" cellspacing="0" border="0" width="100%">
						<tr>
							<td width="144">Stock Available:</td>
							<td width="194">M1 - M52</td>
							<td>MF 2 - MF 52</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>UNC 4-40 - UNC 2"</td>
							<td>UNF 4-48 - UNF 1&frac12;"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>NPT 1/8" - NPT 2"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSW 1/8" - BSW 2"</td>
							<td>BSF 1/8" - BSF 1"</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>BSP 1/16" - BSP 3"</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td>Types of thread on Stock:</td>
							<td colspan="2">UNEF, NPTF, NPSM, BSPT, PG, TR</td>
						</tr>
					</table>

					<h2>THREAD REPAIR SETS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom: 20px;">
						<thead>
							<tr>
								<th>Set of:</th>
								<th>Type No.</th>
								<th colspan="2">
									<table width="100%" class="noborder center nomargin" cellpadding="0" cellspacing="0" border="0">
										<tr>
											<td colspan="2" class="bold">Internal Thread</td>
										</tr>
										<tr>
											<td width="50%" class="bold">Inch</td>
											<td class="bold">mm</td>
										</tr>
									</table>
								</th>
								<th colspan="2">
									<table width="100%" class="noborder center nomargin" cellpadding="0" cellspacing="0" border="0">
										<tr>
											<td colspan="2" class="bold">External Thread</td>
										</tr>
										<tr>
											<td width="50%" class="bold">Inch</td>
											<td class="bold">mm</td>
										</tr>
									</table>
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td rowspan="3" width="91">Internal & external thread</td>
								<td width="73">0100ZIE-1</td>
								<td width="130">5/16" - 5/8"</td>
								<td with="121">8 - 16 mm</td>
								<td width="133">5/32" - &frac34;"</td>
								<td>4 - 19 mm</td>
							</tr>
							<tr>
								<td>0100ZIE-2</td>
								<td>5/16" - 13/16"</td>
								<td>8 - 20 mm</td>
								<td>5/32" - &frac34;"</td>
								<td>4 - 19 mm</td>
							</tr>
							<tr>
								<td>0100ZIE-3</td>
								<td>5/16" - 1.1/4"</td>
								<td>8 - 32 mm</td>
								<td>5/32" - 1.1/2"</td>
								<td>4 - 38 mm</td>
							</tr>
							<tr>
								<td rowspan="2">External thread</td>
								<td>0100ZE-1</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>5/32" - 1.1/2"</td>
								<td>4 - 38 mm</td>
							</tr>
							<tr>
								<td>0100ZE-2</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
								<td>5/32" - 6"</td>
								<td>4 - 152 mm</td>
							</tr>
							<tr>
								<td rowspan="3">Internal thread</td>
								<td>0100ZI-1</td>
								<td>5/16" - 13/16"</td>
								<td>8 - 20 mm</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>0100ZI-2</td>
								<td>5/16" - 1.1/4"</td>
								<td>8 - 32 mm</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>0100ZI-3</td>
								<td>7/8" - 2.5/8"</td>
								<td>22 - 68 mm</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" class="center bold italic">
									How to order: 0100ZE-2&nbsp;&nbsp;&nbsp;&nbsp;Comply to Thread Repair set external thread 5/32" - 6"&nbsp;&nbsp;&nbsp;&nbsp;4 - 152 mm
								</td>
							</tr>
						</tbody>
					</table>
					<div class="clear"></div>
				</div>
				<div class="logo">
					<img src="/img/supplier/dt/dn-logo.png" border="0" alt="Danishtools Thread Cutting Tools since 1898" title="Danishtools Thread Cutting Tools since 1898" />
					<div>Danishtools.com<br />
					Info@danishtools.com<br />
					Copenhagen, Denmark<br />
					Tel: +45 7027 5727 Fax: +45 3173 2639</div>
				</div>
			</div>
		</div>
		<div class="content_wide_footer_shadow"></div>
	</div>
	<div class="zone">
		<div style="padding-top: 20px;"></div>
		<?php echo $this->partial('general-google-ads.phtml'); ?>
	</div>
</div>