<?php
$this->CDNLink()->appendStylesheet('/css/endorsements.css');
$this->CDNLink()->appendStylesheet('/css/textboxlist.css');
$this->CDNLink()->appendStylesheet('/css/supplier/supplier.css');
$this->CDNLink()->appendStylesheet('/css/supplier/dt.css');

$this->headTitle('DanishTools, Thread Cutting Sets, Auxiliaries Tap Wrench, Die Stock & Tap Extension', 'SET');
$this->headMeta()->appendName('description', 'DANISHTOOLS.com - Specialist High Quality Cutting Tools, Select from a wide range of Thread Cutting Sets Hand Taps & Dies, Auxiliaries Tap Wrench, Die Stock, Tap Extension');

$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
                     array('name' => 'Search Results',
						   'url'  => $this->backToSearch()->getUrl()),
					 array('name' => 'Supplier Profile',
						   'url'  => '/supplier/profile/'));
?>
<div id="main_content_area">
	<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
	<div class="content_wide">
		<div class="content_wide_header">

			<h1 class="profile">DANISHTOOLS.com</h1>
			
			<h2>Copenhagen, Denmark</h2>
			
			<a href="/enquiry/index/clearBasket/1/tnid/<?=$this->tnid;?>" rel="nofollow" class="send_enquiry_button"></a>
			
		</div>
		<div class="content_wide_nav">
			<ul>
				<li class="off" id="profile_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>" class="profile_toggle">Profile</a>
				</li>
				<li class="off" id="contact_toggle">
					<a href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#contact_box" class="contact_toggle">Contact</a>
				</li>
				<li class="off" id="reviews_toggle">
					<a href="/reviews/supplier/s/danishtools-com-<?=$this->tnid;?>#reviews" class="reviews_toggle" id="reviewsToggleText">Reviews</a>
				</li>
				<li class="off" id="catalogue_toggle">
					<a class="catalogue_toggle" href="/supplier/profile/s/danishtools-com-<?=$this->tnid;?>#catalogue">Catalogue</a>
				</li>
			</ul>
		</div>
		<div class="content_wide_body">
			<div class="cont">
				<div class="top"></div>
				<div class="image">
					<img src="/img/supplier/dt/hand-machine-taps.png" alt="DanishTools Thread Cutting Sets & Auxiliaries" title="DanishTools Thread Cutting Sets & Auxiliaries" />
				</div>
				<div class="textContainer">
					<div class="left">
						<h1>THREAD CUTTING SETS</h1>
						<p>
							<strong>SETS</strong> <br />
							<strong>TOOLSHOP SHELVES</strong> <br />
							<strong>AUXILIARIES</strong> <br />
						</p>
					</div>
					<div class="right">
						<p class="bm">
							<strong><i>HOW TO ORDER</i></strong><br />
							0100ZT M3 - M12
						</p>
						<p class="bm">
							<strong>TO ORDER - PLEASE STATE:</strong><br />
							Type No., Thread Type, Size
						</p>
					</div>
					<div class="center">
						<strong>ANY TYPE OR SIZE NOT MENTIONED - PLEASE REQUEST</strong>
					</div>
					<h2>SETS</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th colspan="6" align="center">Wooden case with Round or Square Dies HSS, Hand taps, wrenches and die stock</th>
							</tr>
							<tr>
								<th>&nbsp;</th>
								<th>Type No.</th>
								<th colspan="4">
									Thread Type and Size
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td rowspan="4" width="111">ROUND DIES HSS</td>
								<td rowspan="4" width="129">0100 ZT</td>
								<td width="71">M2 - M5</td>
								<td with="132">UNC &frac14;" - UNC 3/4"</td>
								<td width="110">BSW &frac14;" - BSW 3/4"</td>
								<td>BSP 1/8" - BSP 1"</td>
							</tr>
							<tr>
								<td>M3 - M12</td>
								<td>UNC &frac14;" - UNC 1"</td>
								<td>&nbsp;</td>
								<td>BSP 1/8" - BSP 2"</td>
							</tr>
							<tr>
								<td>M3 - M24</td>
								<td>UNF &frac14;" - UNF 3/4"</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>M3 - M30</td>
								<td>UNF &frac14;" - UNF 1"</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td rowspan="2">SQUARE DIES HSS</td>
								<td rowspan="2">0100 ZTS</td>
								<td>M3 - M12</td>
								<td>UNC 5-40 - UNC 5/8"</td>
								<td>BSW 1/8" - BSW 5/8"</td>
								<td>BSP 1/8" - BSP 3/4"</td>
							</tr>
							<tr>
								<td>M3 - M16</td>
								<td>UNF 5-44 - UNC 5/8"</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td colspan="6" class="center bold italic">
									How to order: 0100ZT M3 - M12 &frac14;"&nbsp;&nbsp;&nbsp;&nbsp;Comply to: Round Die HSS, Hand taps, Wrench, Die stock, M3 - M12
								</td>
							</tr>
						</tbody>
					</table>
					<table class="noborder margin left" cellpadding="0" cellspacing="0" border="0" width="100%">
						<tr>
							<td width="144">Also available:</td>
							<td>
								Range of cassettes of Round dies, Hand taps, Wrench and Die stock in M3-12 and M3-20<br />
								Range of cassettes with Hand taps or Machine taps - Standard or PRO with / without drills M3-M12
							</td>
						</tr>
					</table>
					<h2>TOOLSHOP SHELVES - with HAND TAPS and SQUARE DIES HSS - FOR WALL MOUNTING</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th>Type No.</th>
								<th colspan="4">Thread Type and Size</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>0100 ZR</td>
								<td>M3 - M16</td>
								<td>UNC 5-40 - UNC 5/8"</td>
								<td>BSW 1/8" - BSW 5/8"</td>
								<td>BSP 1/8" - BSP &frac34;"</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td>M18 - M27</td>
								<td>UNF 5-44 - UNF 5/8"</td>
								<td>&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
						</tbody>
					</table>
					<center><img src="/img/supplier/dt/tt-shelf.png" border="0" alt="Tooltop Shelves" style="margin-bottom: 15px;"/></center>
					<h2>AUXILIRIES</h2>
					<table cellpadding="0" cellspacing="0" border="0" width="475" style="margin-bottom:20px;">
						<thead>
							<tr>
								<th width="113">&nbsp;</th>
								<th width="130">Type No.</th>
								<th>Type and Size</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td rowspan="2">TAP WRENCH</td>
								<td>1130</td>
								<td>No.0 - No.7</td>
							</tr>
							<tr>
								<td>1100</td>
								<td>With ratchet</td>
							</tr>
							<tr>
								<td rowspan="3">DIE STOCK</td>
								<td>1150</td>
								<td>Round die 16x5 to 90x36</td>
							</tr>
							<tr>
								<td>1720</td>
								<td>Square Die HSS No. 1 and No. 3</td>
							</tr>
							<tr>
								<td>1720PM</td>
								<td>Square Die HSSE No. 1</td>
							</tr>
							<tr>
								<td>TAP EXTENSION</td>
								<td>1155</td>
								<td>2.1 mm - 20 mm</td>
							</tr>
						</tbody>
					</table>
					<div class="clear"></div>
				</div>
				<div class="logo">
					<img src="/img/supplier/dt/dn-logo.png" border="0" alt="Danishtools Thread Cutting Tools since 1898" title="Danishtools Thread Cutting Tools since 1898" />
					<div>Danishtools.com<br />
					Info@danishtools.com<br />
					Copenhagen, Denmark<br />
					Tel: +45 7027 5727 Fax: +45 3173 2639</div>
				</div>
			</div>
		</div>
		<div class="content_wide_footer_shadow"></div>
	</div>
	<div class="zone">
		<div style="padding-top: 20px;"></div>
		<?php echo $this->partial('general-google-ads.phtml'); ?>
	</div>
</div>