CREATE TABLE "SSERVDBA"."AJWP_SESSION_HISTORY"
  (
    "ASH_DATE_TIME" DATE NOT NULL ENABLE,
    "ASH_IP"         VARCHAR2(90 BYTE),
    "ASH_BROWSER"    VARCHAR2(90 BYTE),
    "ASH_USR"        NUMBER(8,0),
    "ASH_ROW_TYPE"   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ASH_ROW_ID"     NUMBER(19,0) NOT NULL ENABLE,
    "ASH_SESSION_ID" NUMBER(19,0) NOT NULL ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "SSERVDBA"."ASH_N1" ON "SSERVDBA"."AJWP_SESSION_HISTORY"
  (
    "ASH_DATE_TIME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "SSERVDBA"."ASH_N2" ON "SSERVDBA"."AJWP_SESSION_HISTORY"
  (
    "ASH_IP",
    "ASH_BROWSER",
    "ASH_USR"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;