CREATE TABLE "SSERVDBA"."AJWP_PAGES_INQUIRY"
  (
    "PIN_ID"               NUMBER(8,0) NOT NULL ENABLE,
    "PIN_NAME"             VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "PIN_COMPANY"          VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "PIN_EMAIL"            VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "PIN_PHONE"            VARCHAR2(100 BYTE),
    "PIN_INQUIRY_TEXT"     VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "PIN_USR_USER_CODE"    NUMBER(8,0) NOT NULL ENABLE,
    "PIN_SPB_SUP_ORG_CODE" NUMBER(8,0),
    "PIN_SPB_BRANCH_CODE"  NUMBER(8,0),
    "PIN_CREATED_BY"       VARCHAR2(80 BYTE) NOT NULL ENABLE,
    "PIN_CREATION_DATE" DATE NOT NULL ENABLE,
    "PIN_LAST_UPDATE_BY" VARCHAR2(80 BYTE) NOT NULL ENABLE,
    "PIN_LAST_UPDATE_DATE" DATE NOT NULL ENABLE,
    "PIN_PSS_ID"          NUMBER(8,0),
    "PIN_STATUS"          VARCHAR2(20 BYTE),
    "PIN_PST_ID"          NUMBER(8,0),
    "PIN_RECIPIENT_COUNT" NUMBER(8,0),
    "PIN_HAS_ATTACHMENT"  NUMBER(1,0),
    "PIN_APP_VERSION"     VARCHAR2(20 BYTE),
    "PIN_GEODATA"         VARCHAR2(4000 BYTE),
    "PIN_SESSION_ID"      NUMBER(12,0),
    CONSTRAINT "AJWP_PAGES_INQUIRY_PK" PRIMARY KEY ("PIN_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SSERVDBA"."AJWP_PAGES_INQUIRY_PK" ON "SSERVDBA"."AJWP_PAGES_INQUIRY"
  (
    "PIN_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  CREATE INDEX "SSERVDBA"."AJWP_PIN_N1" ON "SSERVDBA"."AJWP_PAGES_INQUIRY"
    (
      "PIN_SESSION_ID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
    TABLESPACE "USERS" ;