CREATE TABLE "SSERVDBA"."AJWP_PAGES_STATISTICS_SUPPLIER"
  (
    "PSS_ID"               NUMBER(8,0) NOT NULL ENABLE,
    "PSS_SPB_SUP_ORG_CODE" NUMBER(8,0) NOT NULL ENABLE,
    "PSS_SPB_BRANCH_CODE"  NUMBER(8,0) NOT NULL ENABLE,
    "PSS_VIEW_DATE" DATE NOT NULL ENABLE,
    "PSS_VIEWER_IP_ADDRESS"      VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "PSS_BROWSER"                VARCHAR2(90 BYTE) NOT NULL ENABLE,
    "PSS_USR_USER_CODE"          NUMBER(8,0),
    "PSS_SOURCE"                 VARCHAR2(20 BYTE),
    "PSS_PST_ID"                 NUMBER(10,0),
    "PSS_CONTACT_DETAILS_VIEWED" NUMBER(1,0),
    "PSS_IS_SIGNIN_DECLINED"     VARCHAR2(1 BYTE),
    "PSS_URL_OF_REFERRER"        VARCHAR2(1000 BYTE),
    "PSS_APP_VERSION"            VARCHAR2(20 BYTE),
    "PSS_USER_AGENT"             VARCHAR2(512 BYTE),
    "PSS_GEODATA"                VARCHAR2(4000 BYTE),
    "PSS_SESSION_ID"             NUMBER(12,0),
    CONSTRAINT "AJWP_PAGES_ST_SUPP_PK" PRIMARY KEY ("PSS_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "SSERVDBA"."AJWP_PAGES_ST_SUPP_PK" ON "SSERVDBA"."AJWP_PAGES_STATISTICS_SUPPLIER"
  (
    "PSS_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  CREATE INDEX "SSERVDBA"."AJWP_PSS_N1" ON "SSERVDBA"."AJWP_PAGES_STATISTICS_SUPPLIER"
    (
      "PSS_SESSION_ID"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    )
    TABLESPACE "USERS" ;