<?php 
    $options =  Shipserv_Profile_Menuoptions::getInstance()->getAnalyseTabOptions();
?>
    <div id="sidebar">
        <div class="topBar"></div>
        <ul id="nav">
            <?php foreach ($options as $option): ?>
                 <li<? if ($option['selected']): ?> class="selected"<? endif ?>>
                     <? if ($option['selected']): ?>
                        <?= $option['title'] ?>
                     <? else: ?>
                        <a href="<?= $option['href'] ?>"><?= $option['title'] ?></a>
                     <? endif ?>
                 </li>
            <?php endforeach ?>
        </ul>
    </div>
