<li>
	<!-- Questions Navigation -->
	<p class="qnav">
		<a rel="#q1" href="#q1" class="question">What is brand verification?</a>
		<a rel="#q2" href="#q2" class="question">Does this happen for every brand?</a>
		<a rel="#q3" href="#q3" class="question">How will I add a brand?</a>
		<a rel="#q4" href="#q4" class="question">How do I tell the difference between brands with owner and those without?</a>
		<a rel="#q5" href="#q5" class="question">What does verified, not yet verified and other brands mean?</a>
		<a rel="#q6" href="#q6" class="question">Why is brand verification important to me?</a>
		<a rel="#q7" href="#q7" class="question">What if the brand owner doesn't verify my status as an Authorized Agent, Installer/Repairer or Certified Genuine/Original spares of the brand?</a>
		<a rel="#q8" href="#q8" class="question">Can I remind brand owners to verify me?</a>
		<a rel="#q9" href="#q9" class="question">What if the brand owner rejects my status as 'Authorised Agent/ Installer/Repairer or Certified Genuine/Original spares their brand?</a>
		<a rel="#q10" href="#q10" class="question">I supply a brand but I don't see it in your list to be verified. What do I do?</a>
	</p>

	<!-- Question 1 -->
    <h3 id="q1">What is brand verification?</h3>
    <p>Brand verification enables brand owners to check a supplier claiming to be Authorized Agent, Installer/Repairer or Certified Genuine/Original spares for their brand. If you list a brand on your profile and claim that you are an authorised agent, the brand owner company will be notified, and can verify that and then approve it for you.</p>

    <!-- Question 2 -->
    <h3 id="q2">Does this happen for every brand?</h3>
    <p>No. In some cases the brand owner didn't claim their brand verification tool.</p>

    <!-- Question 3 -->
    <h3 id="q3">How will I add a brand?</h3>
    <p>Please contact us at <a href="mailto:support@shipserv.com">support@shipserv.com</a></p>
    <p>Note that the requested brands are subject for approval and the number of brands that can be added to your profile will depend on your listing level.</p>
    <!--
    <p>You may do so by clicking on Update Company Profile on the <a href="#" class="goUpd">Company Profile Page</a> and then go to Step 4: Brands in the Self Service Tool. See  <a href="#" class="goUpd">here</a> how to access the Self Service Tool. </p>
    <p>Note that the requested brands are subject for approval and the number of brands that can be added to your profile will depend on your listing level.</p>
    -->

     <!-- Question 4 -->
    <h3 id="q4">How do I tell the difference between brands with owner and those without?</h3>
    <p>For brands that do have an owner you will notice a green flag next to the brand name and the note 'pending verification' in the 'Not yet verified' section. Brands without an owner will not show this flag, they will be just listed under 'Not yet verified' section.</p>
    <p>As a supplier, you can suggest us the name of the brand owner for the brands you supply and we will contact them and offer to set them the brand management service on Pages.</p>

    <!-- Question 5 -->
    <h3 id="q5">What does verified, not yet verified and other brands mean?</h3>
    <p>'Verified as Agent' means that the manufacturer/brand owner company has verified and approved your status as Authorized Agent, Installer/Repairer or Certified Genuine/Original spares for that particular brand.</p>
    <p>'Not yet verified' means that the manufacturer/brand owner company has been informed that you listed yourself as an Authorized Agent, Installer/Repairer or Certified Genuine/Original spares for their brand but has not yet approved your status.</p>
    <p>'Other brands supplied' means that you have not claimed to be Authorized Agent, Installer/Repairer or Certified Genuine/Original spares of the brand. Basically, if you don't select any authorisation level, then the brand will be displayed under 'Other brands supplied'.</p>

    <!-- Question 6 -->
    <h3 id="q6">Why is brand verification important to me?</h3>
    <p>To be listed and verified as an Authorized Agent, Installer/Repairer or Certified Genuine/Original spares for a brand has a major impact on your ranking in search results.  Basically, all suppliers that are verified as authorised agents/installers/repairers will be listed before suppliers that are not.</p>

    <!-- Question 7 -->
    <h3 id="q7">What if the brand owner doesn't verify my status as an Authorized Agent, Installer/Repairer or Certified Genuine/Original spares of the brand?</h3>
    <p>When you list a brand on your profile and claim to be an Authorized Agent, Installer or Repairer or Certified Genuine/Original spares, the brand owner will receive a notification of that and instructions as how to approve your status. Until the brand owner approves you, you will see the 'not yet verified' message next to the brand name.</p>

    <!-- Question 8 -->
    <h3 id="q8">Can I remind brand owners to verify me?</h3>
    <p>There is no means by which you can remind a brand owner to verify you. However, ShipServ support team is aware of pending verifications and has a system to remind owners of their pending requests for verification.</p>

    <!-- Question 9 -->
    <h3 id="q9">What if the brand owner rejects my status as 'Authorised Agent/Installer/Repairer or Certified Genuine/Original spares their brand?</h3>
    <p>Then, that brand will be deleted from your profile. We will send you an email informing you about this.</p>

    <!-- Question 10 -->
    <h3 id="q10">I supply a brand but I don't see it in your list to be verified. What do I do?</h3>
    <p>There is a button at the bottom of the page that allows you to request a new brand to be added. After we have added the brand to our system, it will also show in your profile.</p>
</li>