<li>
	<!-- Questions Navigation -->
	<p class="qnav">
		<a rel="#q1" href="#q1" class="question">As a supplier why should I be on, or stay on, ShipServ Pages?</a>
		<a rel="#q2" href="#q2" class="question">How else can I get help?</a>
		<a rel="#q3" href="#q3" class="question">How do I give feedback on Pages?</a>
		<a rel="#q4" href="#q4" class="question">How many people visit Pages?</a>
		<a rel="#q5" href="#q5" class="question">What makes ShipServ Pages any better than a normal offline directory or yellow pages? We stopped being in those years ago!</a>
	</p>

	<!-- Question 1 -->
    <h3 id="q1">As a supplier why should I be on, or stay on, ShipServ Pages?</h3>
	<p>ShipServ Pages is busier than ever. More buyers than ever before are registered to use Pages RFQs. We achieved this traffic increase through natural growth, more returning buyers and SEO (search engine optimisation) activity that our marketing team carries out on an ongoing basis. All this is designed to drive more RFQs and profile views to our suppliers.</p>

	<!-- Question 2 -->
	<h3 id="q2">How else can I get help?</h3>
	<p>If you have a Premium Profile please feel free to contact your account manager. The contact information for existing customer support can be found online at: <a href="/info/support/"><?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/support/</a></p>

	<!-- Question 3 -->
	<h3 id="q3">How do I give feedback on Pages?</h3>
	<p>If you have a question specifically about your profile, contact your account manager. If you want to give general feedback, click <a href="/help/contact">here</a>.</p>

	<!-- Question 4 -->
	<h3 id="q4">How many people visit Pages?</h3>
	<p>You can see this data on the Pages homepage (<a href="https://www.shipserv.com/search/">https://www.shipserv.com/search/</a>) on the right hand side. It is a regularly updated measure of the visitor numbers in the last 7 days.</p>
	<p>By the end of 2012 we are expecting around 2.8 million searches on Pages. You don't have to be logged on to use Pages so we don't know exactly who those visitors are, but as we are a specialist shipping search engine, the vast majority traffic will be qualified buyers from the shipping industry.</p> 
	<p>We also know that many buyers and purchasing managers that are on our TradeNet platform use Pages (they like to use Pages to find new suppliers and then add these suppliers into their RFQs, which they send out using the TradeNet functionality).</p>

	<!-- Question 5 -->
	<h3 id="q5">What makes ShipServ Pages any better than a normal offline directory or yellow pages? We stopped being in those years ago!</h3>
	<p>A few things make Pages different:</p>
	<ul>
		<li>Pages is measurable so you can see the return on your investment. When you get an RFQ from Pages you can identify that it came from your Profile. In addition, our account managers will provide you with usage data on your ShipServ profile, and so you will be able to see how many RFQs you got, and also how many times your profile was viewed, and how many times your contact details were viewed.</li>
		<li>It's the world's largest maritime search engine.</li>
		<li>Pages is growing at about 100% a year, in contrast to many offline directories.</li>
		<li>It is a search engine/yellow pages and many buyers DO use it just to get your contact details to contact you offline. BUT, also, many buyers use it to actually send their RFQs to suppliers. With this real functionality, it's a far more powerful new business generator than an offline directory.</li>
		<li>Because it's online, you can always keep it up to date.</li>
		<li>New tools - control & measure, see our New Supplier Tools Page <a href="/help/new-features-help">here</a></li>
	</ul>

	<!-- Question 6 -->
	<h3 id="q6"></h3>
	<p></p>
</li>