<li>
	<!-- Questions Navigation -->
	<p class="qnav">
		<a rel="#q1" href="#q1" class="question">Why am I receiving more RFQs in my SmartSupplier inbox?</a>
		<a rel="#q2" href="#q2" class="question">What is the benefit?</a>
		<a rel="#q3" href="#q3" class="question">Do I need to do anything special to respond to these RFQs?</a>
		<a rel="#q4" href="#q4" class="question">How can I block a buyer with whom I do not wish to do business?</a>
		<a rel="#q5" href="#q5" class="question">How do I increase the number and/or quality of the RFQs I receive?</a>
		<a rel="#q5" href="#q6" class="question">Why are there no line items in my Pages RFQs?</a>
	</p>

	<!-- Question 1 -->
    <h3 id="q1">Why am I receiving more RFQs in my SmartSupplier inbox?</h3>
	<p>We know how important it is to find new business.  To make sure you do not miss out on any leads, we will now send RFQs from both ShipServ TradeNet and ShipServ Pages to your SmartSupplier. </p>

	<!-- Question 2 -->
	<h3 id="q2">What is the benefit?</h3>
	<p>With all your RFQs now in one place they can be processed quicker and more efficiently.</p>

	<!-- Question 3 -->
	<h3 id="q3">Do I need to do anything special to respond to these RFQ's?</h3>
	<p>No. Just respond the same way you would to any other RFQ. All RFQs received from ShipServ Pages will be marked 'ShipServ Pages from [Buyer name]' in your SmartSupplier inbox.</p>

	<!-- Question 4 -->
	<h3 id="q4">How can I block a buyer with whom I do not wish to do business?</h3>
	<p>Simply log in to your Pages account and maintain the blocked list from there.  To find out more about blocking a buyer please <a href="/help/sellerfaq/maximise" class="goMax">click here</a>.</p> 
	<p>If you have any difficulty doing so, our customer support will be happy to assist you. Email <a href="mailto:support@shipserv.com">support@shipserv.com</a>.</p>

	<!-- Question 5 -->
	<h3 id="q5">How do I increase the number and/or quality of the RFQs I receive?</h3>
	<p>We recommend you look carefully at your listing on ShipServ Pages and specifically what categories and brands you have selected. You might need to change them, delete some, or add to them. You need to access the <a href="/help/sellerfaq/update" class="goUpd">Self Service Tool</a> to make changes to your listing. It might help to talk this through with an account manager so please feel free to <a href="/help/contact">contact us</a>.</p>

	<!-- Question 6 -->
	<h3 id="q6">Why are there no line items in my Pages RFQs?</h3>
	<p>The current structure of the Pages RFQ means that we can only accept free text instead of line items, but we are looking to address this in the near future.</p>
</li>