<li>
	<!-- Questions Navigation -->
	<p class="qnav">
		<a rel="#q1" href="#q1" class="question">How can I edit my profile or access my SIR/RFQ Inbox?</a>
		<a rel="#q2" href="#q2" class="question">Who's responsibility is it to fill out and keep updating my profile?</a>
		<a rel="#q3" href="#q3" class="question">Is it important to have a good quality, well filled out profile?</a>
	</p>

	<!-- Question 1 -->
    <h3 id="q1">How can I edit my profile or access my SIR/RFQ Inbox?</h3>
    <p><strong>Option A - Through ShipServ Pages</strong></p>
    <p><strong>Step 1:</strong> Log into <a href="<?php echo 'https://' . $_SERVER['HTTP_HOST'] . '/auth/cas/login?x=0&pageLayout=new'; ?>">ShipServ Pages</a> using your Pages username and password.</p>
    <p><strong>Step 2:</strong> Go into 'Profile' tab, and then ‘Company Profile’ on the left side menu. There you can see your profile complete score and ‘Update Company Profile’ button. You will then be redirected to the <strong><u>Self Service Tool</u></strong>.</p>
    <img src="/img/help/supplier/04.jpg" border="0" width="660"/>
    <p>You can also go to ‘My companies’ and see all the companies you are connected to, their Profile Complete Score and the Edit Profile button option, as below:</p>
    <img src="/img/help/supplier/05.jpg" border="0" width="660"/>
    <p><strong>VERY IMPORTANT</strong> - You need to be registered as a user and connected to your company to edit the profile. For step-by-step instructions of how to register and connect, click <a href="/help/sellerfaq/register" class="goReg">here</a></p>
    <p>After you log in, you can see your RFQ Inbox in the menu at the left hand side of the screen.</p>
    <p><strong>Option B - Through SmartSupplier</strong></p>
    <p>This option is only available if you have taken our SmartSupplier option.</p>
    <p>Click on marketing when SmartSupplier is opened. This takes you directly to the log in screen of the self service tool.</p>
    <img src="/img/help/supplier/06.jpg" border="0"/>

    <!-- Question 2 -->
    <h3 id="q2">Who's responsibility is it to fill out and keep updating my profile?</h3>
    <p>It's yours, the company listed. Not ShipServ's.</p>

    <!-- Question 3 -->
    <h3 id="q3">Is it important to have a good quality, well filled out profile?</h3>
    <p>Yes, our statistics show that good quality, well filled out profiles get many more views and RFQs than poorly filled out ones.</p>
    <p>We also know that 60% of profiles are significantly incomplete. In other words, 60% of suppliers can benefit immediately if they went in and better completed their profile.</p>
    <p>Why is a well completed, well written Profile so important?</p>
    <p>For 2 reasons:</p>
    <p>Better profiles make buyers more confident in the company and more likely to want to include you in the RFQ they are sending</p>
    <p>We use data from all sections of your Profile to find the best search results for buyers. So the more comprehensive your profile and the more you include about your business, the more likely it is that you appear in search results.</p>
</li>