<?php
$showMap = (int)Myshipserv_Config::getIni()->google->services->maps->display;

$this->compressedScript()->appendFile('/js/lib/selectmenu/jquery.ui.widget.js')
                         ->appendFile('/js/lib/datatables.js')
                         ->appendFile('/js/lib/highcharts/highcharts.js');
if ((int)Myshipserv_Config::getIni()->google->services->maps->display === 1) {
    $this->compressedScript()->appendFile('https://maps.googleapis.com/maps/api/js?key=' . $this->googleMapsApiKey . '&sensor=false');
}


$this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic', 'all')
                 ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic', 'all')
                 ->appendStylesheet('/css/jquery.ui.smoothness.css', 'all')
                 ->appendStylesheet('/css/spr.css', 'all')
                 ->appendStylesheet('/css/grid.css', 'all')
                 ->appendStylesheet('/css/datatables.css', 'all');

$this->getHelper('Requirejs')->addModule('backbone/spr/views/mainView')
   ->addDefinition('buyer/branches', json_encode($this->buyerBrances))
   ->addDefinition('spr/anonim', (int)Myshipserv_Spr_Anonymize::getStatus())
   ->addDefinition('spr/hideFilter', 1)
   ->addDefinition('spr/shipmate', $this->shipmate)
   ->addDefinition('spr/showMap', $showMap)
   ->addDefinition('spr/showCustomRange', (int)$this->showCustomRange);
?>
<script>
	window.isPrint = true;
</script>
<div id="body">
	<div id="content">
		<div id="renderContainer" class="container"></div>
	</div>
</div>
<div class="clear"></div>
