<?
	$this->CDNLink()->appendStylesheet('/css/style.css');
?>

<div class="content_wide new clearfix zz">
	
	<?=$this->partial('/style/subnav.phtml', $this)?>
	
	<div class="content_right">
		<div class="zz header"><h2>Style Guidelines - Useful Bits</h2></div>
		<p>Useful bits &amp; bobs which didn't fit anywhere else...</p>
		<h3 class="zz">Dotted Horizontal Line</h3>
		<p>You can you use a dotted rule like this:</p>
		<hr class="dotted" />
		<p>... to devide content. Code:</p>
		<pre class="code">
			&lt;hr class="dotted" /&gt;
		</pre>
	</div>
</div>
