<?php
$this->compressedScript()->appendFile('/js/jquery.auto-complete.js')
						 ->appendFile('/js/jquery.metadata.js')
						 ->appendFile('/js/jquery.color.js')
						 ->appendFile('/js/my-companies.js');

$this->requirejs()->addModule('help')
				  ->addModule('modal');
				  
$breadcrumbs = array(array('name' => 'Home',
						   'url'  => '/search'),
               array('name' => 'Profile',
						   'url'  => '/profile'),
			   array('name' => 'RFQs from Pages',
						   'url'  => '/profile/company-enquiry'));		 

$statistic = $this->statistic;
$this->headLink()->appendStylesheet('/css/transition.css');
?>
<script>
$(document).ready(function(){
	$(".enquiry").each(function(){
		if ($(this).find('.enquiry-detail-2').innerHeight() > 80){
			$(this).find('.more-text-available').show();
		}
	})
	
	$(".enquiry-detail-button").live('click', function(){
		if( ( $(this).attr("accountType") == "PREPAY" || $(this).attr("accountType") == "PAYASYOUGO" ) && $(this).attr("status") == "ignored" ) {
			if( confirm("You WILL BE charged viewing this RFQ!") ){
				location.href = $(this).attr('link');
			}
		} else {
			location.href = $(this).attr('link');
		}
	});

	$(".archived-enquiry-detail-button").live('click', function(){

		if( $(this).html() == 'more' )
		{
			$('#enquiry-' + $(this).attr('id') + ' .enquiryText' ).css({'max-height':'inherit'});
			$(this).html('less');
			$(this).attr('title', 'click here to see less of this message');
		}else{
			$('#enquiry-' + $(this).attr('id') + ' .enquiryText' ).css({'max-height':'80px'});
			$(this).html('more');
			$(this).attr('title', 'click here to see more of the message');
		}
			
	});

	$(".archived-enquiry-detail-button-page").live('click', function(){
		var url = "/profile/company-enquiry-detail/type/v/id/<?= $this->params['id']?>/enquiryId/" + $(this).attr('link');
		url += '/r/<?= $this->uri()->obfuscate($_SERVER['REQUEST_URI']);?>';
		location.href = url;
	});

	// bind action for top right utility buttons (export, print, etc)
	$('#exportToExcel').live('click', function(){
		if ($(this).is('.disabled')) return false;
		
		$(this).addClass('disabled');
		$(this).find('button').text('Exporting');
		var object = $(this);
		
		var url = '/profile/export-enquiry-to-excel?tnid=' + $('input[name="tnid"]').val();
		
		$.ajax({
			url: url,
			type: 'GET',
			cache: false,
		    error: function(request, textStatus, errorThrown) {
		    	var response = eval('(' + request.responseText + ')');
		    	alert("ERROR " + request.status + ": " + response.error);	
				object.removeClass('disabled');
				object.attr('disabled', false);
				object.find('button').text('Exporting');
		    },
			success: function( response ){
				object.removeClass('disabled');
				object.attr('disabled', false);
				object.text('Export to Excel');

				if( typeof response.data != "undefined"){
					location.href='/profile/download?fileName=' + response.data;
				}else{
					alert("Sorry, there is a problem exporting this report. Please try again.")
				}
				return false;
			}
		});	
		return false;
	});    
});
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->CDNLink()->css('/css/profile.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->CDNLink()->css('/css/profile/company-enquiry.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->CDNLink()->css('/css/profile/user-management.css'); ?>" />

<div id="main_content_area">	
	<div class="clear"></div>
	<div class="content_wide">
		<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
		<div class="content_new-wide_body">
			<?php
			echo $this->partial('profile/title-menu.phtml',
				array(
					'menuItems' => $this->profileMenuHelper->getTopLevelMenu($this->ownerDetails['ownerName'], '', $this->pendingCompanies),
					'menuItemsCompany' => $this->profileMenuHelper->getCompanyMenu($this->companyDetail['name'], $this->companyDetail['type'], $this->companyDetail['id'], 'company-enquiry', $this->pendingUsers, $isAdmin)
				)
			);
			?>
			<div class="profile-body-right enquiries">
				<div class="zz header">
					<h2>RFQs from Pages</h2>
					<?php /*
                    <form>
                        <div class="zz medium dblue button add_btn">
                            <a href="#" id="exportToExcel" class="button" title="Export to Excel">Export to Excel</a>
                        </div>
                        <input id="enq-tnid" type="hidden" value="<?= $this->supplier->tnid ?>" maxlength="6" size="6" name="tnid" style="float:left; height:13px; padding:2px; margin-top:0px;" />
                    </form>
                    */ ?>
				</div>
				<div class="profileContent">
					
					ShipServ has improved your RFQ inbox - <a href="/trade">Click here</a> to view.
					<br /><br />(We’ve also moved it to the Trade tab.)
					
					<?php /*
					<?php if( $this->supplier->tnid != "" ){?>
						<div class="clear"></div>
					<?php
						echo $this->partial('profile/enquiry-list.phtml', array(
							'config' => $this->config,
							'enquiries' => $this->enquiries,
							'statistic' => $this->statistic,
							'supplier' => $this->supplier,
							'user' => $this->user,
							'isShipservMode' => $this->user->isShipservUser(),
							'period' => $this->period,
							'params' => $this->params,
							'currentPage' => $this->currentPage,
							'totalFound' => $this->totalFound,
							'pageSize'	=> $this->pageSize
						));
					?>
					
					<?php } else {?>
							<div class="clear intro"></div>
							<?if( $this->params['tnid'] != "" ){?>
							Supplier: <?= $this->params['tnid'] ?> cannot be found
							<?}else{?>
							Please choose your company:
							<select id="tnidSelector">
								<option>Please select</option>
								<?foreach($this->myCompanies as $company): ?>
								<option value="<?php echo $company['id']?>" <?php echo ($company['id'] == $this->supplierProfile->tnid )?'selected="selected"':'';?>><?php echo $company['name']?></option>
								<?endforeach?>
							</select>		
							<?}?>
					<?php }?>
					*/?>
					
				</div>
			</div>
		</div>
	</div>
</div>
