<?php
    $this->headLink()->appendStylesheet('/css/transition.css');            
    $this->headLink()->appendStylesheet('/css/profile.css');
    $this->headLink()->appendStylesheet('/css/uniform.default.new.css');
    $this->headLink()->appendStylesheet('/css/profile/targetCustomers.css');
    
    $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic', 'all');
    $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic', 'all');
    $this->headLink()->appendStylesheet('/css/jquery.ui.smoothness.css', 'all');
    
    $this->getHelper('Requirejs')->addModule('backbone/profile/targetCustomers/views/mainView')
                                 ->addDefinition('profile/targetCustomers/tab', "'" . $this->params['tab'] . "'")
                                 ->addDefinition('match/url', "'" . Myshipserv_Config::getMatchUrl() . "'");

    $breadcrumbs = array(array('name' => 'Home',
                               'url'  => '/search'),
                         array('name' => 'Profile',
                               'url'  => '/profile'),
                         array('name' => 'Active Promotion',
                               'url'  => '/profile/target-customers'));
?>
<div id="main_content_area">
	<div class="clear"></div>
	<div class="content_wide">
		<?php echo $this->partial('profile/breadcrumbs.phtml', array('breadcrumbs' => $breadcrumbs)); ?>
		<div class="content_new-wide_body">
            <?php
                $isAdmin = false;
                foreach((array)$this->myCompanies as $company){ if( $company['id'] == $this->companyDetail['id'] ){ if( $company['amAdmin'] ) { $isAdmin = true; } } }
                echo $this->partial('profile/title-menu.phtml',
                    array(
                        'menuItems' => $this->profileMenuHelper->getTopLevelMenu($this->ownerDetails['ownerName'], '', $this->pendingCompanies),
                        'menuItemsCompany' => $this->profileMenuHelper->getCompanyMenu($this->companyDetail['name'], $this->companyDetail['type'], $this->companyDetail['id'], 'target-customers', $this->pendingUsers, $isAdmin)
                    )
                );
            ?>
			<div class="profile-body-right companyProfile targetCust">
				<h1 class="styled">
                    
                    <span>Active Promotion</span>
                </h1>
                <div class="cont pending">
                    <div class="infoBox">
                        <div class="leftBox">
                            <h2>Customers Pending Decision</h2>
                            <p>
                                It is important that you take action on the following customers  and decide if you wish<br />
                                to actively promote yourself to them or exclude them from active promotion.<br />
                            </p>
                            <a href="#" class="btn medium white transparent-blue howitworks">How it works</a>
                        </div>
                        <div class="transRightBox">
                        		<a href="#" class="btn medium link-blue settings">Settings</a>
                        </div>
                    </div>
                    <ul class="tabs">
                        <li class="tab pending active">
                            <img src="/img/profile/targetCustomers/pendingIconOn.png" alt="pending" /> <span>Pending Decision</span>
                        </li><li class="tab targeted">
                            <img src="/img/profile/targetCustomers/targetedIcon.png" alt="targeted" /> <span>Active Promotion</span></li><li class="tab excluded last"><img src="/img/profile/targetCustomers/excludedIcon.png" alt="excluded" /> <span>Excluded</span></li>
                    </ul>
                    <div class="data">
                        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="pendingTable">
                            <thead>
                                <tr>
                                    <th class="sb">
                                        SR<br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="sbinfo shTooltip" data-tooltipelement="tooltip-sr-text" />
                                    </th>
                                    <th class="tnid">TNID</th>
                                    <th class="name left">Name</th>
                                    <!--<th class="since">Pending<br /> since</th>-->
                                    <th class="location">Location</th>
                                    <th class="vesselNo">Number of Vessels</th>
                                    <th class="vesselTypes">Vessel type(s)</th>
                                    <th class="ordVal">
                                        Order Value <br />
                                        <span style="font-size: 12px; font-weight: normal;">last 12months<br />
                                        (USD)</span><br />
                                         <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="ordvalinfo shTooltip" data-tooltipelement="tooltip-ord-text" />
                                    </th>
                                    <th class="lastTxnDate">Date of last transaction</th>
                                    <th class="action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="cont targeted" style="display: none;">
                    <div class="infoBox">
                        <div class="leftBox">
                            <h2>Active Promotion Customers</h2>
                            <p>
                                ShipServ will actively promote you to these companies to<br />
                                help you to win and retain them as regular customers.
                            </p>
                        </div>
                        
                        <div class="rightBox">
                            <div class="light">
                                <p>
                                    • This status will be locked <span class="defLock"></span><br />
                                    &nbsp;&nbsp;once an order has been received<br /><br />
                                    • Stop actively promoting customers by<br />
                                    &nbsp;&nbsp;excluding them if they are not locked<br />
                                </p>
                            </div>
                            <div class="dark">
                                <span class="medium">You will pay:</span> <span class="large rate"></span><span class="percent">%</span><br />
                                for orders from<br />
                                these customers
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <ul class="tabs">
                        <li class="tab pending">
                            <img src="/img/profile/targetCustomers/pendingIcon.png" alt="pending" /> <span>Pending Decision</span>
                        </li><li class="tab targeted active">
                            <img src="/img/profile/targetCustomers/targetedIconOn.png" alt="targeted" /> <span>Active Promotion</span></li><li class="tab excluded last"><img src="/img/profile/targetCustomers/excludedIcon.png" alt="excluded" /> <span>Excluded</span></li>
                    </ul>
                    <div class="data">
                        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="targetedTable">
                            <thead>
                                <tr>
                                    <th class="sb">
                                        SR<br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="sbinfo shTooltip" data-tooltipelement="tooltip-sr-text" />
                                    </th>
                                    <th class="tnid">TNID</th>
                                    <th class="name left">Name</th>
                                    <th class="since">
                                        Actively<br />
                                        promoted<br />
                                        since
                                    </th>
                                    <th class="location">Location</th>
                                    <th class="vesselNo">Number of Vessels</th>
                                    <th class="vesselTypes">Vessel type(s)</th>
                                    <th class="targetedBy">
                                        Actively<br />
                                        promoted by
                                    </th>
                                    <th class="rfqRec">
                                        RFQs<br /> 
                                        received<br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="rfqrecinfo shTooltip" data-tooltipelement="tooltip-rfq-text"/>
                                    </th>
                                    <th class="qotRate">
                                        Quote<br /> 
                                        rate<br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="qotinfo shTooltip" data-tooltipelement="tooltip-qot-text" />
                                    </th>
                                    <th class="ordVal">
                                        Order value<br />
                                        <span>since lock date<br />
                                        (USD)</span>
                                    </th>
                                    <th class="action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="cont excluded" style="display: none;">
                    <div class="infoBox">
                        <div class="leftBox">
                            <h2>Excluded Customers</h2>
                            <p>
                                ShipServ will NOT actively promote you to these companies. <br />
                                Only list companies that you consider to be existing and secure<br />
                                customers or companies that you do not wish to trade with.
                            </p>
                        </div>
                        
                        <div class="rightBox">
                            <div class="light">
                                <p>
                                    To actively promote yourself to these<br />
                                    customers click on the 'Promote' button
                                </p>
                            </div>
                            <div class="dark">
                                <span class="medium">You will pay:</span> <span class="large rate"></span><span class="percent">%</span><br />
                                for orders from<br />
                                these customers
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <ul class="tabs">
                        <li class="tab pending">
                            <img src="/img/profile/targetCustomers/pendingIcon.png" alt="pending" /> <span>Pending Decision</span>
                        </li><li class="tab targeted">
                            <img src="/img/profile/targetCustomers/targetedIcon.png" alt="targeted" /> <span>Active Promotion</span></li><li class="tab excluded active last"><img src="/img/profile/targetCustomers/excludedIconOn.png" alt="excluded" /> <span>Excluded</span></li>
                    </ul>
                    <div class="data">
                        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="excludedTable">
                            <thead>
                                <tr>
                                    <th class="sb">
                                        SR<br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="sbinfo shTooltip" data-tooltipelement="tooltip-sr-text" />
                                    </th>
                                    <th class="tnid">TNID</th>
                                    <th class="name left">Name</th>
                                    <th class="since">
                                        Excluded<br />
                                        since
                                    </th>
                                    <th class="location">Location</th>
                                    <th class="vesselNo">
                                        Number<br />
                                        of<br />
                                        Vessels
                                    </th>
                                    <th class="vesselTypes">Vessel type(s)</th>
                                    <th class="excludedBy">Excluded by</th>
                                    <th class="ordVal">
                                        Order Value<br />
                                        <span>last 12months <br />
                                        (USD)</span><br />
                                        <img src="/img/profile/targetCustomers/infoicon.png" alt="info" class="ordvalinfo shTooltip" data-tooltipelement="tooltip-ord-text" />
                                    </th>
                                    <th class="lastTxnDate">
                                        Date of last<br />
                                        transaction
                                    </th>
                                    <th class="action">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
			</div>
            <div class="profile-body-right companyProfile targetCustSet" style="display: none;">
                <h1 class="styled">
                    
                    <span>Active Promotion Settings</span>
                </h1>
                <div class="cont settings">
                    <div class="tab-list-holder">
                    		<div	 id="settings-subcat" class="selected">Sub-Category/Brand Preferences</div>
                    		<div	 id="settings-notifications">Notifications</div>
                		    <a href="#" class="btn medium link-blue closeSettings">Back to Customers Pending Decision</a>
                    </div>
                    
                    <div class="settings-tab1">
                        <div class="blueBox" style="line-height: 1.2;">
                            Select which admin users should receive notification emails relating to Active Promotion. Only Admin users can view and change Active Promotion functionality.
                        </div>
                        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="settingsTable">
                            <thead>
                                <tr>
                                    <th class="name left">Name</th>
                                    <th class="email left">Email address</th>
                                    <th class="receive">Receive notifications</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <div class="greyBox">
                            <h2>Maximum Quotes per Buyer</h2>
                            <input type="checkbox" name="maxQotTrue" id="maxTrue" />
                            <label for="maxQotTrue">Maximum comparison quotes per buyer</label>
                            <select name="maxQot" id="maxQotDrop">
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100" selected="selected">100</option>
                            </select>
                        </div>
                        <div class="settingsButton">
                            <input type="button" name="saveSettings" class="button green medium" value="Save">
                            <div class="clear"></div>
                        </div>
                    </div>
                    
                    <div class="settings-tab2">

                    <form class="filters">
                        <div class="top-selector">
                            	<label>
                            		<div class="select">
                            			<select name="segments">
                            				<option value="" disabled selected>Select Category</option>
                            			</select>
                            		</div>
                            		<p class="save-confirmation bg-mediumGreen"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;You have updated your settings</p>
                            	</label>
                        </div>
                        	<div id="keyworListContainer">
                        		<div id="keyworListContainer-col1" class="col"></div>
                        		<div id="keyworListContainer-col2" class="col"></div>
                        		<div id="keyworListContainer-col3" class="col"></div>
                        		<div id="keyworListContainer-col4" class="col"></div>
                        		<div class="clear"></div>
                        	</div>
                       	<div class="al-right">
                            	<a href="#" class="btn medium white transparent-blue cat-settings-clear-all">Clear All</a>
                            	<a href="#" class="btn medium link-blue cat-settings-select-all">Select All</a>
                            	<a href="#" class="btn medium green transparent-blue cat-settings-save">Save</a>
                        	</div>
                        	<div class="no-items-message">
                        		<p>
                            		There is no item associated with this category.
                        		</p>
                        	</div>
                    </form>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
		</div>
	</div>
</div>
<div id="waiting" style="display: block;">
    <div class="waitingMessage">Loading...</div>
    <div class="waitingMask"></div>
</div>
<div id="modal" class="promotePopup">
    <div class="modalBody">
        <h1 class="styled">Promote</h1>
        <div class="modalContent">
            <p class="marginBottom">ShipServ will actively promote you to this customer</p>
            <p class="marginBottom custName" style="font-size: 18px; font-weight: bold;"></p>
            <p>• You will pay <span class="rate"></span>% for orders from this customer</p>
            <p>• This status will be locked <span class="defLock"></span> once an order is received</p>
            <p>• You can exclude this buyer at a later date if they have not been locked</p>
            <div class="buttons">
                <input type="button" name="pmote" value="Add to active promotion list" class="button medium green" />
                <input type="button" name="cancel" value="Cancel" class="button medium" />
            </div>
        </div>
    </div>
</div>
<div id="modalX" class="excludePopup">
    <div class="modalBody">
        <h1 class="styled">Exclude</h1>
        <div class="modalContent">
            <p class="marginBottom">ShipServ will NOT actively promote you to this customer</p>
             <p class="marginBottom custName" style="font-size: 18px; font-weight: bold;"></p>
            <p>• You will pay <span class="rate"></span>% for orders from this customer</p>
            <p>• You can elect to actively promote yourself to this customer at a later date</p>
            <div class="buttons">
                <input type="button" name="xclude" value="Add to exclusion list" class="button medium black" />
                <input type="button" name="cancel" value="Cancel" class="button medium" />
            </div>
        </div>
    </div>
</div>

<div id="tooltip-sr-text" style="display: none">
	This buyer has enabled<br>
	Supplier Recommendations.<br>
	If you target this buyer you<br>
	will have a significantly<br>
	higher chance of receiving<br>
	RFQs from them.
</div>

<div id="tooltip-ord-text" style="display: none">
	<div style="text-align: center">
        	Value of orders<br>
        	sent to you from<br>
        	this buyer in last<br>
        	12 months.
	</div>
</div>

<div id="tooltip-rfq-text" style="display: none">
	<div style="text-align: center">
		Since<br>
		Active Promotion<br>
		initiated
	</div>
</div>

<div id="tooltip-qot-text" style="display: none">
	<div style="text-align: center">
		For RFQs since<br>
		Active Promotion<br>
		initiated
	</div>
</div>
