<?php
	$this->CDNLink()->appendStylesheet('/css/uniform.default.new.css');
	$this->CDNLink()->appendStylesheet('/css/forgot-password.css');
	$this->getHelper('Requirejs')->addModule('backbone/user/restlogin/views/forgotPass');
?>

<div class="loginBox forgot standard">
	<div class="center">
		<h2 class="styled grey green">Change Password</h2>
		<div class="formContainer">
			<form id="netIdBean" class="new" action="" method="post">
				<fieldset>
					<div class="row">
                        <?php if (!$this->username): ?>
						<label class="resetPassword" for="password">Please enter your Username or Email address <sup>*</sup></label>
						<input type="text"  value="<?php echo $this->username; ?>" id="username" name="username" />
						<?php if ($this->validation['error3'] !== ''): ?>
							<div class="error"><?php echo $this->validation['error3']; ?></div>
						<?php endif ?>
                        <?php else: ?>
                            <label class="resetPassword" for="password">Username</label>
                            <input type="hidden"  value="<?php echo $this->username; ?>" id="username" name="username" />
                            <p class="disabled-user"><?php echo $this->username; ?></p>
                        <?php endif ?>
                    </div>

					<div class="row">
						<label class="resetPassword" for="password">New Password <sup>*</sup></label>
						<input type="password"  value="" id="password" name="password" />
						<?php if ($this->validation['error1'] !== ''): ?>
							<div class="error"><?php echo $this->validation['error1']; ?></div>
						<?php endif ?>
					</div>

					<div class="row">
						<label class="resetPassword" for="confirmPassword">Confirm New Password <sup>*</sup></label>
						<input type="password"  value="" id="confirmPassword" name="confirmPassword" />
						<?php if ($this->validation['error2'] !== ''): ?>
							<div class="error"><?php echo $this->validation['error2']; ?></div>
						<?php endif ?>
					</div>

					<?php if ($this->validation['general'] !== ''): ?>
						<div class="row">
							<div class="error" style="top:0"><?php echo $this->validation['general']; ?></div>
						</div>	
					<?php endif ?>
				</fieldset>
	            <div class="btnDiv">
	            	<input type="submit" value="Update Password" id="password-submit" name="password-submit" class="button medium green">
	            </div>
		    </form>
		</div>
	</div>
	<div class="clear"></div>
</div>

   



