<?php
	$this->CDNLink()->appendStylesheet('/css/uniform.default.new.css');
	$this->CDNLink()->appendStylesheet('/css/forgot-password.css');
	$this->getHelper('Requirejs')->addModule('backbone/user/restlogin/views/forgotPass');
?>
<div class="loginBox forgot wide">
	<div class="center">
	        <h2 class="styled grey blue">Change Password Request Expired (<?php echo $this->error; ?>)</h2>
			<br/>
			<p>
				Your request to change your password has already expired. Click <a href="/auth/cas/passwordManager?pmTask=forgotPassword">here</a> to request again.
			</p>
   	</div>
	<br/>
	<div class="clear"></div>
</div>
