<?php
$this->CDNLink()->appendStylesheet('/css/uniform.default.new.css');
$this->CDNLink()->appendStylesheet('/css/forgot-password.css');
$this->getHelper('Requirejs')->addModule('backbone/user/restlogin/views/forgotPass');
?>
<div class="loginBox forgot wide">
    <div class="center">
        <h2 class="styled grey blue">Password Changed</h2>
        <br/>
        <p>
            Your password has been successfully updated.
        </p>
    </div>
    <br/>
    <div class="clear"></div>
</div>
