<?php
$this->headLink()->appendStylesheet('/css/login.css');
?>

<div class="loginBox" style="display: block !important; ">
	<div class="right">
		<h2 class="styled grey blue">New User?</h2>
		<h3>First time using ShipServ?</h3>
		<h4>Join us today!</h4>
		<p><span>It's FREE</span> and it will takes less than 2 minutes.</p>
		<input type="button" name="register" value="Register" class="button medium lblue" />
	</div>
	<div class="left">
		<h2 class="styled grey green">Existing User?</h2>
		<div class="formContainer">
			<?php
			if (is_array($this->errors['top']))
			{
				?>
				<div id="form_error" style="margin: 0 0 10px 0px;">
					<?php
					foreach ($this->errors['top'] as $error)
					{
						if (!is_array($error))
						{
							?>
							<form class="new">
								<div class="error"><?php echo $error; ?></div>
							</form>
							<?php
						}
					}
					?>
				</div>
				<?php
			}
			?>
		
			<form class="new" id="login-form" action="/user/forgotten-password" method="post">
				<input type="hidden" id="loginRedirectUrl" name="redirectUrl" value="<?php echo $this->redirectUrl; ?>" />
				<input type="hidden" value="<?= $benc?>" name="benc" />
				
			
				<fieldset>
					<input type="hidden" name="act" value="login" />
					<label for="loginUsername">Email: <sup>*</sup></label>
					<input type="email" name="loginUsername" />
					<div class="clear"></div>
				<input type="submit" name="signIn" class="button medium green" value="Sign in and continue" />
			</form>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div id="supplier_detail_box"></div>

<div id="main_content_area">
	<div class="content_slim" id="login">
		<form id="loginForm" method="post" action="/user/forgotten-password">
			<div class="content_slim_wrapper">
				<div class="content_slim_header">
					<h1>Forgotten Password</h1>
				</div>
				
				<?php
				if ($this->success)
				{
					?>
					<div id="modal_form">
						<div class="modal_left" style="float:none;">
							<div class="form_inner">
								<div class="form_inner_body">
									<p>Your password was sent to your email address</p>
									<p><a href="/user/register-login">Click here to continue</a></p>
								</div>
							</div>
						</div>
					</div>
					<div class="clear"></div>
					<div class="the_corner_piece"></div>
					<div class="content_wide_footer_shadow"></div> 
					<?php
				}
				else
				{
					?>
					<div id="modal_form">
						<div class="modal_left" style="float:none;">
							<div class="form_inner">
								<div class="form_inner_body">
									<div <?php if($this->errors['forgEmail']){?>class="form_error"<?}?>>
										<p class="label">Email*</p>  			
										<?php
										if ($this->errors['forgEmail'])
										{
											foreach ($this->errors['forgEmail'] as $key => $value)
											{
												?>
												<p><?php echo $value; ?></p>
												<?php
											}
										}
										
										if ($this->errors['forgEmail'])
										{
											?>
											<div class="error_msg_arrow"></div>
											<?php
										}
										?>
									</div>
									<input type="text" <?php if ($this->errors['forgEmail']) { echo 'class="error"'; } ?> id="forgEmail" name="forgEmail" value="<?php echo $this->formValues['forgEmail']; ?>" />
								</div>
							</div>
						</div>
						<div class="clear"></div>
                        <div class="form_buttons">
                            <input type="submit" class="send_password png" id="forgSend" name="forgSend" value="" />
                            <div class="clear"></div>
                        </div>
					</div>
					<div class="content_wide_footer_shadow"></div> 
					
					<?php
				}
				?>
			</div>
		</form>
	</div>	   
</div>