<?php
	$this->headLink()->appendStylesheet('/css/user.css');	
?>

<section class="grey registration-header clearfix">
	<div class="wrapper">
		<div class="left">
			<h2>Forgotten Password?</h2>
		</div>
	</div>	
</section>

<section class="white">
	<div class="wrapper">
		<div class="forgotten-password-wrapper">
			<form class="forgotten-password" action="" method="post">
				<p>Enter a username or email address:</p>
				<input id="forgotten-password" name="netId" class="required" tabindex="1" type="text" type="text" value="<?php echo _htmlspecialchars($this->netId); ?>" size="22" autocomplete="false"/>
				<?php if ($this->error !== ''): ?>
					<div class="error"><?php echo _htmlspecialchars($this->error); ?></div>
				<?php endif ?>				
				<input class="btn green" type="submit" value="Send Password" name="sendPass">
			</form>	
		</div>
	</div>
</section>
