<?

/**
 * When included on a page, this will render AND THEN REMOVE error and success flash messages from their session store
 * This means that a pending message will usually be displayed on the next including page if this partial is omitted.
 */

$sessionNamespace = Myshipserv_Helper_Session::getNamespaceSafely('Myshipserv_Flashmessages');

if (isset($sessionNamespace->errorMessages) && is_array($sessionNamespace->errorMessages)) {
	$this->errorMessages = $sessionNamespace->errorMessages;
}
if (isset($sessionNamespace->successMessages) && is_array($sessionNamespace->successMessages)) {
	$this->successMessages = $sessionNamespace->successMessages;
}

/*Leave the UL wrappers in so that JS can add messages in. Styling should make empty list invisible*/?>
<ul class="error messages general <?=empty($this->errorMessages) ? 'empty' : ''?>">
	<?if(!empty($this->errorMessages)):?>
		<?foreach($this->errorMessages as $errorMessage):?>
			<li><?=$errorMessage?></li>
		<?endforeach?>
	<?endif?>
</ul>

<ul class="success messages general <?=empty($this->successMessages) ? 'empty' : ''?>">
	<?if(!empty($this->successMessages)):?>
		<?foreach($this->successMessages as $successMessage):?>
			<li><?=$successMessage?></li>
		<?endforeach?>
	<?endif?>
</ul>

<?
	$sessionNamespace->successMessages = array();
	$sessionNamespace->errorMessages = array();
?>