<div class="google_zone_ad">
	<h4>ADVERTISEMENTS</h4>
	
	<script type='text/javascript'>
	var googletag = googletag || {};
	googletag.cmd = googletag.cmd || [];
	(function() {
	var gads = document.createElement('script');
	gads.async = true;
	gads.type = 'text/javascript';
	var useSSL = 'https:' == document.location.protocol;
	gads.src = (useSSL ? 'https:' : 'http:') + 
	'//www.googletagservices.com/tag/js/gpt.js';
	var node = document.getElementsByTagName('script')[0];
	node.parentNode.insertBefore(gads, node);
	})();
	</script>

	<script type='text/javascript'>
	googletag.cmd.push(function() {
	googletag.defineSlot('/1007555/RSComponents_ProfileBanner_AdUnit', [180, 300], 'div-gpt-ad-1409746740678-0').addService(googletag.pubads());
	googletag.defineSlot('/1007555/RSComponents_ProfileBanner_AdUnit2', [180, 300], 'div-gpt-ad-1409746740678-1').addService(googletag.pubads());
	googletag.defineSlot('/1007555/RSComponents_ProfileBanner_AdUnit3', [180, 300], 'div-gpt-ad-1409746740678-2').addService(googletag.pubads());
	googletag.pubads().enableSingleRequest();
	googletag.enableServices();
	});
	</script>
	<!-- RSComponents_ProfileBanner_AdUnit1 -->
	<div id='div-gpt-ad-1409746740678-0' style='width:180px; height:300px;'>
	<script type='text/javascript'>
	googletag.cmd.push(function() { googletag.display('div-gpt-ad-1409746740678-0'); });
	</script>
	</div>
	<br />

	<!-- RSComponents_ProfileBanner_AdUnit2 -->
	<div id='div-gpt-ad-1409746740678-1' style='width:180px; height:300px;'>
	<script type='text/javascript'>
	googletag.cmd.push(function() { googletag.display('div-gpt-ad-1409746740678-1'); });
	</script>
	</div>
	<br />

	<!-- RSComponents_ProfileBanner_AdUnit3 -->
	<div id='div-gpt-ad-1409746740678-2' style='width:180px; height:300px;'>
	<script type='text/javascript'>
	googletag.cmd.push(function() { googletag.display('div-gpt-ad-1409746740678-2'); });
	</script>
	</div>
	<br />
</div>