<html>
<head>
	<title></title>
</head>
<body>
	<table style="width: 100%; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td>&nbsp;</td>
			<td style="height: 30px; font-size: 1px; width: 600px;">&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>
				<table style="width: 600px; border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
						<td style="height: 80px; vertical-align: middle; background-color: #002f5f;">
							<img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/reminders/logo.png" border="0" style="margin: 0; padding: 0;" alt="ShipServ">
						</td>
						<td style="width: 20px; background-color: #002f5f;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 50px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000;">
							Dear ShipServ Member,
						</td>
						<td style="width: 20px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 25px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;">
							This is a notification to inform you that a ShipServ Buyer has been automatically added to your Active Promotion Exclude List. As a result, ShipServ will NOT actively promote you to this buyer. If you wish to edit this setting, click the button below.
						</td>
						<td style="width: 20px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 25px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;">
							This buyer is now locked on the targeted list. 
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 30px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;">
							<table style="width: 100%; border-collapse: collapse; table-layout: fixed; border: 1px solid #979797;" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="background: #EFF1F5; border-bottom: 1px solid #D0D0D0;">
										<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td style="height: 12px; font-size: 1px;" colspan="3">&nbsp;</td>
											</tr>
											<tr>
												<td style="width: 15px;"></td>
												<td style="width: 35px;"><img src="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/wp-content/themes/shipserv/images/email/targetbuyers/locked.png" border="0" alt="locked"></td>
												<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5; height: 25px; vertical-align: middle;">Buyer Details:</td>
											</tr>
											<tr>
												<td style="height: 12px; font-size: 1px;" colspan="3">&nbsp;</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td style="background: #FFFFFF;">
										<table style="width: 100%; border-collapse: collapse; table-layout: auto;" cellpadding="0" cellspacing="0" border="0">
											<tr>
												<td colspan="4" style="font-size: 1px; height: 20px;">&nbsp;</td>
											</tr>
											<tr>
												<td style="font-size: 1px; width: 25px;">&nbsp;</td>
												<td>
													<? if ($this->logoUrlIsValid): ?>
														<img width="165" style="width: 165px;" src="<?= $this->logoUrl ?>" alt="logo">
													<? endif ?>
												</td>
												<td style="font-size: 1px; width: 10px;">&nbsp;</td>
												<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5; height: 25px; vertical-align: middle;">
													Company: <?= $this->buyerInfo['BYB_NAME'] ?><br>
													Date of order: <?= $this->ordDate ?><br>
													PO number: <?= $this->lockOrdRefNo ?><br>
													Locked until: <?= $this->validTill ?>
												</td>
											</tr>
											<tr>
												<td colspan="4" style="font-size: 1px; height: 20px;">&nbsp;</td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
						<td style="width: 20px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 30px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #000000; line-height: 1.5;">
							<a href="<?= Myshipserv_Helper_ApplicationProtocol::getInstance()->getProtocolURL().$this->domain ?>/profile/target-customers/type/v/id/" style="font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: #0070BB;">Edit your Buyer Targeting Settings</a>
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 30px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #000000; text-align: center;">
							If you require further information or assistance visit our <a href="<?php echo Myshipserv_Config::getCorporateSiteUrl() ?>/info/support/" style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #0070BB;">support page</a><br> or email: <a href="mailto: support@shipserv.com" style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #0070BB;">support@shipserv.com</a>
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
					<tr>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
						<td style="height: 20px; font-size: 1px;">
							&nbsp;
						</td>
						<td style="width: 20px; font-size: 1px;">&nbsp;</td>
					</tr>
				</table>
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td style="height: 30px; font-size: 1px;">&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
</body>
</html>