<style>
	.rating input{
		margin-top:10px;
	}
	.rating{
		float:left;
		text-align:center;
		vertical-align:middle;
		font-weight:bold;
		margin-right:2px;
		padding:10px;
		
		background: -moz-linear-gradient(top,  rgba(255,255,255,0) 0%, rgba(204,204,204,0.65) 100%); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,0)), color-stop(100%,rgba(204,204,204,0.65))); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top,  rgba(255,255,255,0) 0%,rgba(204,204,204,0.65) 100%); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top,  rgba(255,255,255,0) 0%,rgba(204,204,204,0.65) 100%); /* Opera 11.10+ */
		background: -ms-linear-gradient(top,  rgba(255,255,255,0) 0%,rgba(204,204,204,0.65) 100%); /* IE10+ */
		background: linear-gradient(top,  rgba(255,255,255,0) 0%,rgba(204,204,204,0.65) 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00ffffff', endColorstr='#a6cccccc',GradientType=0 ); /* IE6-9 */
		
	}
	
	.score{
		clear:both;
		border:1px solid #E3E4E7;
		padding:10px 20px 10px 20px;
	}
	
	.score .footer div{
		font-size:12px;
		float:left;
	}
	.green{
	color: #51A21A;
	}
	
	.grey{
	color: #7A7A7A;
	}
	
	.red{
		color: #F32629;
	}
	.content_wide .container{
		margin-left:40px;
		width:880px;
	}
	.container h2{
		font-weight:bold;
		font-size:18px;
		color:#32ADEC;
	}
	.score .inner-container{
		margin-top:20px;
		margin-bottom:30px;
	}
	.container textarea{
		width:860px;
		border:1px solid #E3E4E7;
		padding:10px;
	}
	.content_wide h1{
		margin-top:30px;
		margin-left:20px;
		font-size:18px;
		font-weight:bold;
	}
    
    .content_wide .searchFeedback .questionPane .result {
        text-align: center;
        line-height: 28px;
    }
</style>

<div class="content_wide new clearfix">
	<div class="header">
		<div class="heading">
			<h1>Customer Satisfaction Survey</h1>
		</div>
	</div>
	<div class="searchFeedback" style="background-color:white; border:0px; margin:0px; width:550px; margin-left:230px; margin-bottom:100px;">
		<div class="questionPane">
			<div class="result"><img src="/images/search-feedback/ok_icon.jpg" /> <div>Thank you for your response!</div></div>
		</div>
	</div>

</div>
