<?php 
	$survey = $this->survey;
	$this->requirejs()->addModule('survey/index');
	
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->CDNLink()->css('/css/survey/index.css'); ?>" />

<div class="content_wide new clearfix">
	<div class="header">
		<div class="heading">
			<h1>Customer Satisfaction Survey</h1>
		</div>
	</div>
	<div class="container">
		<div style="font-size:12px; "><img src="/images/icons/large/blue/info.png" width="20" align="middle" style="float:left;" /><div style="margin-top:5px; margin-left:10px;float:left;">Please help us to improve our services by answering this question:</div></div>
		<br /><br />
		<form id="form-survey" method="post" action="/survey">
			<input type="hidden" name="email" value="<?php echo strtolower($this->params["email"])?>" />
			<input type="hidden" name="surveyId" value="<?php echo $this->params["surveyId"]?>" />

			<br />
			<h2>How likely is it that you would recommend ShipServ's services to your friends or colleagues?</h2>
			<br />
			<div class="score">
				<div class="inner-container">
					<div style="float:left; font-size:12px; vertical-align:middle; margin-top:30px;	margin-right:40px;">Please select:</div>
					<?php 
					for( $i=0; $i<=10; $i++){
						if( $i <= 3 )
						{
							$colorClass="red";
						}
						else if( $i >= 4 && $i < 7 )
						{
							$colorClass = "grey";
						}
						else if( $i > 6 )
						{
							$colorClass = "green";
						}
						?><div class="rating <?php echo $colorClass;?>"><label><?php echo $i;?><br /><input type="radio" name="question[1]" value="<?php echo $i;?>"></label></div><?php 
					}?>
					<div class="clear"></div>
					<div class="footer">
						<div class="red" style="margin-left:120px;">Not at all likely</div>
						<div class="grey" style="margin-left:140px;">Neutral</div>
						<div class="green" style="margin-left:120px;;">Extremely likely</div>
					</div>
				</div>
			</div>
			<br />
			<br />
			<h2>Why did you score ShipServ in this way?</h2>
			<br />
			<div>
				<div style="font-size:12px; margin-top:-10px; margin-bottom:5px;">Please feel free to add your comments below (optional):</div>
				<textarea name="question[2]"></textarea>
			</div>
			<br />
			<br />
								
			<input type="image" src="/images/search-feedback/button_send_feedback.jpg"	id="sendFeedbackBtn" />
			<br />
			<br />
			<br />
			<br />
		</form>
	</div>
</div>
