
<div class="modal_left">
	
	<div class="form_inner">
		<div class="form_inner_header">
		
			<p>Enquiry Functionality coming soon</h3>
	
			<p>Please click outside of this window to close it</p>
			
		</div>
		
		<div class="form_inner_footer">&nbsp;</div>
	</div>
	
	<?php
	/*
	<form enctype="multipart/form-data" id="signupForm" method="post" action="/enquiry/send">
	  
	<div class="form_inner">
		<div class="form_inner_header">
			<p>Subject, or item required</p>
			<input type="text" /> 
		</div>
		<div class="form_inner_body">
			<p>Message</p>
			 <textarea id="enquiryBody" name="enquiryBody"></textarea>
			<div class="file_uploader_box" style="display:none;">
				 <input type="file" name="enquiryFile[]" /><br/><br/>
				 <input type="file" name="enquiryFile[]" /><br/><br/>
				 <input type="file" name="enquiryFile[]" /><br/><br/>
			</div>
		</div>
		<div class="form_inner_footer">
			<a class="file_uploader" href="#" title="" style="float:left;"><img src="/images/layout_v2/buttons/add_attachment_button.gif" alt="Attach Items" /></a>
			<p style="float:left;line-height:18px;margin-left:-20px;" class="subtext">Attach up to three documents</p> 
		</div> 
	</div>
	
	<div class="form_element" style="height: 290px;">
		<p>Your email</p>
		<input id="enquiryEmail" name="enquiryEmail" type="text" /> 
		<p class="subtext">Replies will be sent to this address, plus a copy of  your message</p>
		
		<p>Your name</p>
		<input type="text" id="enquiryFirstName" name="enquiryFirstName" value="<?php echo $this->user->firstName; ?>" />
		
		<p>Your company</p>
		<input type="text" id="enquiryCompanyName" name="enquiryCompanyName" value="" />
		
		<p>Your phone number</p>
		<input type="text" id="enquiryPhone" name="enquiryPhone" value="" />
	</div>
	
	<div class="form_buttons">
		<!--a href="#" title="" style="float:left;"><img src="/images/layout_v2/buttons/find_more_suppliers_button.gif" alt="Find More" /></a-->
		
		<?php
		if ($this->requiresLogin)
		{
			?>
			<a href="#modal_login" name="modal" style="float:right;"><img src="/images/layout_v2/buttons/send_now_button.gif" alt="Send Now" /></a>
			<?php
		}
		else
		{
			?>
			<input type="image" src="/images/layout_v2/buttons/send_now_button.gif" />
			<?php
		}
		?> 
		<div class="clear"></div> 
	</div>
	</form>
	
	</div>
	
	<div class="modal_right">
		<a href="#" class="close"><img src="/images/layout_v2/buttons/add_recipients_button.gif" alt="Find More" /></a>
		
		<h1>Send to:</h1>
		
		<?php
		foreach ($this->supplierBasket as $value)
		{
			?>
			<p><a href=""><?php echo $value;?></a></p> 
			<?php
		}
		?>
	
	</div> 
	
	<div class="clear"></div>
	*/ ?>
</div>