<div id="supplier_detail_box">   
	<a class="back_to_results_button" href="#"><img src="<?php echo $this->CDNLink()->image('/images/layout_v2/buttons/back_to_results_button.gif'); ?>" alt="contact supplier" /></a> 
</div>

<div id="main_content_area" style="margin-top:20px;"> 
    
<div class="content_wide">
	
	 <div class="content_wide_header">
	 <h1>RFQ Form</h1>
	 </div>
			
	<div id="modal_form">
		<div class="modal_left">
			<div class="form_inner"> 
				<div class="form_inner_body">

					<p style="padding:20px 0 20px 0;font-size:18px;font-weight:bold;text-align:center;"><?php echo $this->message;?></p>
					
				</div>
			</div>
		</div>
		<div class="clear"></div>
    </div> 

</div>