<?php if (Myshipserv_Config::displaySirOutdatedAlert()): ?>
<div class="general-alert">
    <div>
        <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
        <span>Important</span>
    </div>
    <div>
        <span>
            This report does not include profile stats for the new Search released on 13 September 2020. Contact your account manager to get your new search profile statistics.
        </span>
    </div>
</div>
<?php endif; ?>
